### ISSUE TITLE
running tests broken

### ISSUE THREAD

**Issue by hartzis** [acdlite/recompose#106]
There seems to be a dependency issue, possibly related to `babel-relay-plugin`.

If you do a fresh `clone` and `npm install` then `npm test` you get a lot of these errors:

```Module build failed: ReferenceError: Unknown plugin "./src/packages/recompose-relay/babelRelayPlugin" specified in "base" at 0```

any thoughts? it is currently blocking all PR's

**Comment by acdlite** [comment]
Sorry I'll look at this some time today

**Comment by hartzis** [comment]
Looks like they are passing now.
