### ISSUE TITLE
React 15.0.0-rc1 key warning 

### ISSUE THREAD

**Issue by zeroshine** [acdlite/recompose#112]
React 15.0.0-rc1 add a new warning.
- Elements will now warn when attempting to read ref and key from the props.  

recompose seems touch key from props, so this warning shows up

> `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop.

**Comment by acdlite** [comment]
Thanks for the bug report. This can be fixed by using `hasOwnProperty` here: https://github.com/acdlite/recompose/blob/ca7c6d33de8afa4e48cee299ba9a16feba4b1d76/src/packages/recompose/createElement.js#L7

I'll fix soon!

**Comment by acdlite** [comment]
Closed by #113. It'll go out in the next release.
