### ISSUE TITLE
To curry, or not to curry?

### ISSUE THREAD

**Issue by acdlite** [acdlite/recompose#117]
I'm considering dropping the automatic currying of Recompose helpers.

- It doesn't play nicely with Flow or TypeScript
- It makes it more costly for libraries to import individual modules, because it bloats the bundle size. For example, if you import `recompose/withProps`, the code that implements currying is larger than the code needed to implement `withProps()` itself.
- It's not clear how much utility it actually provides. In my own use, I almost always call helpers of n arity with n or n-1 arguments.
- Arguably, it adds to the learning curve, and makes Recompose seem more special or foreign than it really is.

Instead, I propose that we remove automatic currying and instead move toward an API like React Redux's `connect()`.

```js
// Before: all these forms work
helper(a, b, c)(BaseComponent)
helper(a, b, c, BaseComponent)
helper(a)(b)(c)(BaseComponent)
// etc.

// After: only this form
helper(a, b, c)(BaseComponent)
```

Note that this is still compatible with `compose()`

What do you think?

**Comment by acdlite** [comment]
Closed by #118. This will go out in the next release.

**Comment by dralletje** [comment]
Oh dang, I did use the n-arity form pretty often, but I guess that is an easy to fix

**Comment by BjornMelgaard** [comment]
it was bad decision
