### ISSUE TITLE
Lodash 4 breaks IE8

### ISSUE THREAD

**Issue by joshacheson** [acdlite/recompose#130]
Hey there.

Curious if we're willing to use Lodash < 4 moving forward in the interest of IE8 support. I'm willing to do the work for a PR that would facilitate this.

edit: in at least one case (`withHelpers`), static class properties are being used again (uses of static class properties were previously removed in https://github.com/acdlite/recompose/pull/69). Should we consider tightening the babel plugins so that regressions like this don't occur? Alternatively I'm happy to maintain an ie8 fork of the project.

**Comment by acdlite** [comment]
`withHelpers` doesn't have any static class properties. It has a normal class property, but so do several other helpers. I thought it was only static properties that were a problem?

I'm not keen on continuing to support IE8 given that React itself has dropped support. If you would like to maintain an IE8 fork I'd be happy to link to it in the README.
