### ISSUE TITLE
Would you please tell me how to add your library?

### ISSUE THREAD

**Issue by dannyxx001** [acdlite/recompose#131]
Hello, I'm a intern from [cdnjs](https://github.com/cdnjs/cdnjs). I want to add your library, however, I don't know which files I should pick. Would you please tell me how to add your library? Thank you.

**Comment by mrtnbroder** [comment]
There is no packaged file for you to use (yet). @acdlite would have to include another build step which concatenates everything for you into one file.

I'd be happy to help @acdlite, if you want that.

**Comment by dannyxx001** [comment]
OK, thank you for your response. If your file is ready, just notify me. Thanks. :)

**Comment by acdlite** [comment]
@mrtnbroder If you want to work on that that'd be sweet :)

**Comment by acdlite** [comment]
@dannyxx001 Not sure how cdnjs works, but a Recompose bundle is now published with each npm release, and therefore accessible via npmcdn: https://npmcdn.com/recompose@0.18.0/build/Recompose.min.js

**Comment by acdlite** [comment]
Closing this. Let me know if you need further action from me.

**Comment by dannyxx001** [comment]
Sorry for late response. I think your work is enough and I have tried to add your library. See [cdnjs/#7888](https://github.com/cdnjs/cdnjs/pull/7888#event-660783014). Thanks for your collaboration.
