### ISSUE TITLE
`withProps` passes undefined for props

### ISSUE THREAD

**Issue by calebmer** [acdlite/recompose#139]
When trying to use the `withProps(props => …)` enhancer, `props` is undefined. To understand this the built code looks like (annotated to point out the relevant bits):

```js
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };

var _isFunction = require('lodash/isFunction');
var _isFunction2 = _interopRequireDefault(_isFunction);
var _createHelper = require('./createHelper');
var _createHelper2 = _interopRequireDefault(_createHelper);
var _createElement = require('./createElement');
var _createElement2 = _interopRequireDefault(_createElement);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var withProps = function withProps(input) {
  return function (BaseComponent) {
    // Is `getProps` defined here for hosting?
    var getProps = void 0;
    // Why is `getProps` getting passed to `input`?
    var props = (0, _isFunction2.default)(input) ? input(getProps) : input;

    return function (ownerProps) {
      // Because here `getProps` gets redefined?
      getProps = function getProps() {
        return ownerProps;
      };
      return (0, _createElement2.default)(BaseComponent, _extends({}, ownerProps, props));
    };
  };
};

exports.default = (0, _createHelper2.default)(withProps, 'withProps');
```

Using the code in this repo with the REPL on the Babel site it works, [link](http://babeljs.io/repl/#?evaluate=true&presets=es2015%2Creact%2Cstage-0&code=import%20isFunction%20from%20'lodash%2FisFunction'%0Aimport%20createHelper%20from%20'.%2FcreateHelper'%0Aimport%20mapProps%20from%20'.%2FmapProps'%0A%0Aconst%20withProps%20%3D%20input%20%3D%3E%0A%20%20mapProps(props%20%3D%3E%20(%7B%0A%20%20%20%20...props%2C%0A%20%20%20%20...(%0A%20%20%20%20%20%20isFunction(input)%0A%20%20%20%20%20%20%20%3F%20input(props)%0A%20%20%20%20%20%20%20%3A%20input%0A%20%20%20%20)%0A%20%20%7D))%0A%0Aexport%20default%20createHelper(withProps%2C%20'withProps')).

**Comment by istarkov** [comment]
Already fixed, not published yet.
https://github.com/acdlite/recompose/pull/137

**Comment by calebmer** [comment]
👍
