### ISSUE TITLE
Is eslint props validation possible with recompose?

### ISSUE THREAD

**Issue by joshburgess** [acdlite/recompose#150]
Is there a way to get props validation warnings working with recompose like with the eslint-plugin-react/prop-types rule?

**Comment by wuct** [comment]
I don't think there is a way currently. Here is [a releated issue](https://github.com/yannickcr/eslint-plugin-react/issues/322) opened in `eslint-plugin-react`.

**Comment by joshburgess** [comment]
Interesting. Thanks for the link.

**Comment by acdlite** [comment]
Closing since there's not much we can do here. I've also looked into using Flow types but haven't found any success adding types to higher-order components.

**Comment by winkler1** [comment]
@acdlite Not sure if you've seen - the Flow docs have this example of Flow annotations for HOC's: https://github.com/facebook/flow/blob/master/website/docs/ref/react.doc.js#L201.

**Comment by acdlite** [comment]
@winkler1 I've seen that, but it's not really an HoC. It's more of a container component. Need a way to type annotate a function that returns a component. I asked some FB people and they said they'll be working on the problem soon.

Unless I'm mistaken, in which case a PR or issue showing how to do it would be great :)

**Comment by arronmabrey** [comment]
@joshburgess I opened a PR that adds a failing test case to the issue in the eslint-plugin-react project that @wuct mentioned above.

- issue: https://github.com/yannickcr/eslint-plugin-react/issues/322
- failing test case pr: https://github.com/yannickcr/eslint-plugin-react/pull/762 

Hopefully with that we can get props validation warnings working with recompose
