### ISSUE TITLE
Provide a JSFiddle to play around with recompose

### ISSUE THREAD

**Issue by gajus** [acdlite/recompose#152]

**Comment by acdlite** [comment]
Oops this was accidentally closed when I merged #154, which adds a UMD bundle to the release step.

**Comment by acdlite** [comment]
Ugh I am just failing at GitHub today :D

**Comment by acdlite** [comment]
Added to readme!

**Comment by istarkov** [comment]
Hello World jsbin example, meet recompose 0.18!!!!
https://jsbin.com/qiwiradohu/edit?js,output
