### ISSUE TITLE
removal of lifecycle

### ISSUE THREAD

**Issue by SeeThruHead** [acdlite/recompose#164]
hey there, started trying to use this library, following along with the docs. I need to add a lifecycle function. But it seems like I can't as 0.18 doesn't have lifecycle. Do you have an example of how I might do this? Thanks!

**Comment by acdlite** [comment]
Hi! `lifecycle()` is back in 0.19, with a slightly different API: https://github.com/acdlite/recompose/releases/tag/v0.19.0
