### ISSUE TITLE
How to handle deep objects with onlyUpdateForKeys?

### ISSUE THREAD

**Issue by rtkhanas** [acdlite/recompose#166]
Hey, @acdlite , I just started browsing this library and really like it, thank you.

I wanted to ask a question, but unfortunately, could not see appropriate tag on stackoverflow, so decided to do it here. 

`recompose` uses shallow comparison in `onlyUpdateForKeys` implementation. But what is the best way to handle components if I need something like `deep rendering`? In my case I don't use Immutable.js, so `{a:'1'} !== {a:'1'}`, so component is triggered to be re-rendered. Could you suggest, please, how to handle this with recompose?

Thank you!

**Comment by istarkov** [comment]
Hey ;-) in your case 
1) you could use https://github.com/acdlite/recompose/blob/master/docs/API.md#shouldupdate directly
2) you could use mapProps to transform deep object structure into non deep, then use `onlyUpdateForKeys`

BTW IMHO in most cases using non [pure](https://github.com/acdlite/recompose/blob/master/docs/API.md#pure) shallow equality can cause a lot of problems in the future, so I recommend you to work with plain js objects as with immutable data (you don't need immutable.js to use the same behavior) and trying to use just `pure` HOC or nothing whenever it possible.

**Comment by rtkhanas** [comment]
For sure, I'm trying to write pure components with plain object props as much as possible, but I just found few places where it is a bit weird to have all props as a non-deep tree from logical point of view.
I think 1st solution is not really cool, since writing `shouldUpdate` will cause some messy code, I would like to generalize it somehow. But, `mapProps` feature looks really useful, thank you!

**Comment by wuct** [comment]
In addition, there is [`flattenProp`](https://github.com/acdlite/recompose/blob/master/docs/API.md#flattenprop) which is a shortcut for `mapProps`.

**Comment by rtkhanas** [comment]
It looks really useful when I have a strict structure of my property.

But what if I have, for instance, `style` object with wide range of possible properties which I cannot validate using `propTypes`? Seems like in this case the bast way is to implement `shouldUpdate` manually and do something like shallow compare in there.

**Comment by acdlite** [comment]
> Seems like in this case the bast way is to implement `shouldUpdate` manually and do something like shallow compare in there.

Yes, this is what we would suggest.

Though I tend to agree with @istarkov that, if you must implement `shouldComponentUpdate` (and usually, you shouldn't), you should probably stick with shallow equality.

**Comment by wuct** [comment]
@acdlite Maybe we should add a line to the README to tell people use a **recompose** tag on SO?

**Comment by damianobarbati** [comment]
Does `onlyUpdateForKeys` support lodash `get` syntax?
i.e: 
```
@onlyUpdateForKeys(['prop1', 'obj.nestedProp.nestedProp2'])
```

**Comment by istarkov** [comment]
@damianobarbati  no, and will not
