### ISSUE TITLE
Wrap and hoist statics

### ISSUE THREAD

**Issue by SeeThruHead** [acdlite/recompose#169]
looking for a way to wrap a component in another, while hoisting statics
i'm trying this
```
const wrapClass = classes => comp => nest(({ children }) => <div classes={classes}>{children}</div>, comp);

 const Search = wrapClass(styles.searchResults)(SearchResults);
```

Sidenote, I realize this isn't an issue, so if there's a better forum for me to ask these kinds of things, or if you don't accept support req's please let me know.

thanks!

**Comment by acdlite** [comment]
Recompose has a helper called [`hoistStatics()`](https://github.com/acdlite/recompose/blob/master/docs/API.md#hoiststatics) that takes a higher-order component and returns a new order-component that has the same behavior, and also hoists static properties.

I believe this should work:

```js
const wrapAndHoist = Component => hoistStatics(
  BaseComponent => nest(Component, BaseComponent)
)
```

**Comment by SeeThruHead** [comment]
thanks!
