### ISSUE TITLE
Is it an alternative for Flux / Redux ??

### ISSUE THREAD

**Issue by VansonLeung** [acdlite/recompose#17]
From my first impression I would like to use it to replace my old lil Flux. Is it going to be developed like that?

**Comment by acdlite** [comment]
Recompose is not all that comparable to a full-blown state management solution like Flux or Redux. It's possible to replicate parts of Flux using Recompose's helpers — for instance, `withState()` and `withReducer()` are alternatives to using Flux for *component-local state* — but the focus of the library is on React components in general, by providing generic helpers for creating and augmenting their behavior.

There's some work to be done on clarifying the purpose / philosophy behind Recompose. I'll work on this.
