### ISSUE TITLE
Clarification needed on how getContext injects prop types

### ISSUE THREAD

**Issue by psachs21** [acdlite/recompose#170]
Hi. I've been playing around with recompose a bit and I've been liking it a lot, although I sometimes struggle to understand the ordering of the compose arguments.

I have the following example that doesn't do what I think it should:

```js
const enhance = compose(
  setPropTypes({
    val: PropTypes.string.isRequired
  }),
  setDisplayName('Test'),
  withProps(props => {
    console.log(props.bob);
    return props;
  }),
  getContext({
    bob: PropTypes.string
  })
);

const Comp2 =  enhance(({ val, bob }) => (
  <div>{val}{JSON.stringify(bob)}</div>
));

const enhance2 = compose(
  setDisplayName('Test2'),
  withContext({
    bob: PropTypes.string
  }, props => ({ bob: 'Nothing' }))
);

export default enhance2(() => <div><Comp2 val='hi bob'/></div>);
```

I would expect that I could access the context items inside withProps, but it does not seem to be the case. If I move getContext() to before withProps, it works as I expected it to (and console logs 'Nothing'). I thought compose worked right to left.

Any help in understanding this situation would be helpful.

**Comment by acdlite** [comment]
```js
const enhancer = compose(a, b, c)
```

is a shortcut for

```js
const enhancer = BaseComponent => a(b(c(BaseComponent))
```

Each higher-order passes injects props into its base component. So the base component passed to `c` is `BaseComponent`, the base component passed to `b` is `c(BaseComponent)`, and the base component passed to `a` is `b(c(BaseComponent))`.

So if `a`, `b`, or `c` injects props

```js
const enhancer = compose(a, getContext({ bob: PropTypes.string }, c)
```

those props are only available to the components to its right in the `compose` chain (in this case `c(BaseComponent)` and `BaseComponent`).
