### ISSUE TITLE
(rx-recompose) createEventHandler.js

### ISSUE THREAD

**Issue by b2whats** [acdlite/recompose#176]
why in your implementation you are using Observable.create, not Subject

original
```js
import { Observable } from 'rx'
import { createChangeEmitter } from 'change-emitter'

const createEventHandler = () => {
  const emitter = createChangeEmitter()
  const stream = Observable.create(observer =>
    emitter.listen(value => observer.onNext(value))
  )
  return {
    handler: emitter.emit,
    stream
  }
}

export default createEventHandler
```
subject
```js
import Rx from 'rx'

const createEventHandler = () => {
  const stream = new Rx.Subject()

  return {
    handler: (value) =>  stream.next(value),
    stream
  }
}

export default createEventHandler
```

**Comment by acdlite** [comment]
Hi! We eventually want to remove our dependency on RxJS, and instead maintain compatibility with any spec-compliant observable implementation (`core-js` just added Observable recently: https://github.com/zloirock/core-js/releases/tag/v2.4.0). Subject is not part of the spec; it's specific to RxJS. Most consumers will likely still use RxJS for its operators, but it won't be required.

I'm planning to make this transition once RxJS 5 (which is spec-compliant) is out of beta.
