### ISSUE TITLE
pass context to withHandlers (and others)

### ISSUE THREAD

**Issue by mrtnbroder** [acdlite/recompose#191]
I've just arrived at a point where I need access to the context object and not the props, but only the props are passed to `withHanders()`. This is probably the case for many other functions as well.

I'd suggest adding the context a second parameter to these functions where we pass props along.

Maybe this completely destroys the concept of recompose though, not sure. Whaddaya think @acdlite?

**Comment by SeeThruHead** [comment]
why not pass the context you need from getContext as props?

**Comment by istarkov** [comment]
Docs https://github.com/acdlite/recompose/blob/master/docs/API.md#getcontext

**Comment by mrtnbroder** [comment]
@SeeThruHead because I was too dumb looking at the API. Thanks! 😎
