### ISSUE TITLE
getContext overrides contextTypes, defined on the original Component

### ISSUE THREAD

**Issue by le0nik** [acdlite/recompose#197]
Shouldn't it be merged with the new contextTypes?

https://github.com/acdlite/recompose/blob/master/src/packages/recompose/getContext.js#L13

**Comment by acdlite** [comment]
That line is assigning `contextTypes` to a new component, not the input component.

**Comment by le0nik** [comment]
Ah. Exactly. Input component receives `context` anyway. Sorry.

**Comment by acdlite** [comment]
No need to apologize :)
