### ISSUE TITLE
withStateSelector proposal

### ISSUE THREAD

**Issue by istarkov** [acdlite/recompose#199]
Idea is to provide withState with *resetable* state. 
Sometimes when I work with `react-router` (not only) I don't want to recreate component to reset state after route has changed. 
The idea is to provide `withStateSelector(stateName, stateUpdaterName, selectorFactory)` HOC which will reset - recalculate `stateValue` every time selector return a new result.

This will be easy to use with [reselect](https://github.com/reactjs/reselect#createselectorinputselectors--inputselectors-resultfunc) library. Like
 ```javascript
  withStateSelector(
    'markers', 'setMarkers',
    () => createSelector(
      ({ route: { markersCount = 20 } }) => markersCount,
      (markersCount) => generateMarkers(markersCount)
    )
  ), 
```

The real code with example:

[Usage](https://github.com/istarkov/google-map-react/blob/master/develop/GMapOptim.js#L62-L69)
[Routes with params](https://github.com/istarkov/google-map-react/blob/master/develop/Main.js#L17-L19)
[withStateSelector source](https://github.com/istarkov/google-map-react/blob/master/develop/utils/withStateSelector.js)

Here every time route changed and got new `markersCount` param `createSelector` will return a new result, and state will be resetted.

PS: It's useful with controls like forms, which should use internal state until save 'button' / 'blur event' is pressed / occured.

**Comment by istarkov** [comment]
Also we could just extend withState - and to detect `selectors` if result of initial state call is function.

**Comment by istarkov** [comment]
Also to make it more same with `reselect` it's possible to pass to selector also the current `state`,
`this.selector(this.state.stateValue, nextProps)`

**Comment by jurgob** [comment]
+1 I need it too
