### ISSUE TITLE
withHandler receives synthetic event if using function updater form causing error

### ISSUE THREAD

**Issue by jeffbski** [acdlite/recompose#201]
I was experimenting with recompose in jsfiddle and found that we can't access event.target in handler if we are using the fn updater form. I don't understand why this is occurring, it seems like everything is synchronous, unless withHandlers is calling it asynchronously.

 Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the property `target` on a released/nullified synthetic event. This is set to null. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information.

Key snippets are below, fiddles include full code

Original fiddle using updateValue(str) works
https://jsfiddle.net/jeffbski/pw0a3y9r/
```js
const enhance = compose(
  withState('value', 'updateValue', ''),
  withHandlers({
    onChange: props => ev => {
      props.updateValue(ev.target.value) // works fine
    }
  })
)
```

However it fails if using updateValue(x => ev.target.value)
https://jsfiddle.net/jeffbski/j93frota/2/
```js
const enhance = compose(
  withState('value', 'updateValue', ''),
  withHandlers({
    onChange: props => ev => {
      props.updateValue(x => ev.target.value) // fails with synthetic event issue
    }
  })
)
```

So I am wondering why this is occurring and if there is anyway to fix it so handlers can be used with the function form of updater.

**Comment by mrblueblue** [comment]
You have to capture the value of the event target in a variable, and then use that in the `updateValue` callback.

It seems like by the time the callback happens, the target of that specific event is "released"

```js
 onChange: props => ev => {
   const value = ev.target.value
   props.updateValue(x => value)
}
```

**Comment by jeffbski** [comment]
So the updateValue function is calling it asynchronously and thus causing the issue. I wonder why that is the case.

**Comment by istarkov** [comment]
It is not the `withHandlers` problem, it is the React `setState` behavior.
https://facebook.github.io/react/docs/component-api.html
```
setState() does not immediately mutate this.state but creates a pending state transition. Accessing this.state after calling this method can potentially return the existing value.
```
So difference is that in 1st example you read `target.value` immediately, but in second just then callback be run

**Comment by istarkov** [comment]
So use persist or I use event copy `const my = {...evt}`

**Comment by jeffbski** [comment]
ok, thanks for the help. That makes sense.
