### ISSUE TITLE
branch proposal

### ISSUE THREAD

**Issue by galkinrost** [acdlite/recompose#202]
How about add wrapper-component into the branch decorator?

``` javascript
branch(predicate,
    ...,
    renderNothing,
    ReactCSSTransitionGroup
)(WrappedComponent)
```

**Comment by acdlite** [comment]
I had a similar idea, but it wouldn't be implemented in `branch` — it would be a new helper called `wrapComponent` (or similar):

```js
wrapComponent(OuterComponent)(InnerComponent)

// renders
<OuterComponent>
  <InnerComponent />
</OuterComponent>
```

So your example would look like

```js
compose(
  wrapComponent(ReactCSSTransitionGroup),
  branch(predicate,
    ...,
    renderNothing
  )
)(WrappedComponent)
```

**Comment by galkinrost** [comment]
As I understand it's the same as the nest decorator? The issue is that ReactCSSTransitionGroup triggers only when child component do mount or unmount. But branch component doesn't unmount itself only its left/right components.
