### ISSUE TITLE
Question: Defining expected propTypes prevents referential transparancy?

### ISSUE THREAD

**Issue by PAkerstrand** [acdlite/recompose#203]
I was just browsing the code and noticed that setting propTypes prevents us from calling the function transparently.. Is this because we would bypass the prop types warning system if we called the function directly rather than through React?
(Which means that it's not really an issue with referential transparency, but rather that we'd, unexpectedly, would no longer get prop type warning?)

If so, that should only be a "problem" during development, provided one uses some sort of Babel-transformation that removes propTypes, right? Like [babel-plugin-transform-react-remove-prop-types](https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types)

**Comment by acdlite** [comment]
I think the best thing would be to do an environment check, same as React.

```js
const isReferentiallyTransparentFunctionComponent = Component => Boolean(
  typeof Component === 'function' &&
  !isClassComponent(Component) &&
  !Component.defaultProps &&
  !Component.contextTypes &&
  !(process.env.NODE_ENV !== 'production' && Component.propTypes)
)
```

**Comment by PAkerstrand** [comment]
Sounds like a good idea
