### ISSUE TITLE
Unsubscribing for Kefir observables does not work

### ISSUE THREAD

**Issue by jeron-diovis** [acdlite/recompose#213]
<img width="645" alt="screenshot 2016-07-05 16 55 24" src="https://cloud.githubusercontent.com/assets/2756868/16586968/0da977d0-42d1-11e6-80eb-ac997fa70a3c.png">

Recompose expects subscription to be an object with `unsubscribe` method, while in Kefir `subscribe` method of "ES Observable" [returns just a function](https://github.com/rpominov/kefir/blob/master/src/interop/to-es-observable.js#L22).

**Comment by acdlite** [comment]
Interesting. This is clearly a bug with Kefir but until it's fixed, we should work around it.

**Comment by acdlite** [comment]
Filed a bug https://github.com/rpominov/kefir/issues/212
