### ISSUE TITLE
Question: How feasible is it to flatten components / lazily evaluate

### ISSUE THREAD

**Issue by juliankrispel** [acdlite/recompose#214]
I love recompose because it gets me closer to functional programming.

It's a little annoying (especially when viewing components with react dev tools) that every hoc creates a new react component by default.

- Would it be feasible to lazily evaluate some or most of the helpers provided by recompose?
- What architectural changes would it involve?

**Comment by istarkov** [comment]
Please have a look here https://github.com/acdlite/recompose/pull/182
That PR combines recompose HOCs into one.

**Comment by juliankrispel** [comment]
awesome thanks guys
