### ISSUE TITLE
"Warning: `ref` is not a prop" with onlyUpdateForPropTypes (React 15.2.1)

### ISSUE THREAD

**Issue by jschlieber** [acdlite/recompose#217]
Trying to enhance a functional stateless component with:

``` javascript
const enhance = compose(
  onlyUpdateForPropTypes,
  setPropTypes({
    page: PropTypes.object,
  })
);
```

yields warnings (React 15.2.1):

```
Warning: onlyUpdateForPropTypes(Breadcrumb): `ref` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://fb.me/react-special-props)
```

and

```
Warning: onlyUpdateForPropTypes(Breadcrumb): `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://fb.me/react-special-props)
```

**Comment by istarkov** [comment]
1) Your order of props is incorrect.

Example, no warnings
https://jsfiddle.net/1qsm0sbt/

**Comment by istarkov** [comment]
2) Looks like your warnings is new React 15.2 warnings, please read [React changelog](https://github.com/facebook/react/blob/master/CHANGELOG.md#react-dom)

**Comment by jschlieber** [comment]
Thanks. I know, there are new warnings in React 15.2.
I used the order from the ([API docs](https://github.com/acdlite/recompose/blob/master/docs/API.md#onlyupdateforproptypes))

**Comment by istarkov** [comment]
Oops looks like I'm wrong about order.
BTW no warnings https://jsfiddle.net/12z2g866/

**Comment by jschlieber** [comment]
Hmm... interesting. If I comment out `onlyUpdateForPropTypes`:
```javascript
const enhance = compose(
  // onlyUpdateForPropTypes,
  setPropTypes({
    page: PropTypes.object,
  })
);
```
the warnings disapear. Put it back in:
```javascript
const enhance = compose(
  onlyUpdateForPropTypes,
  setPropTypes({
    page: PropTypes.object,
  })
);
```
and the warnings are there again. Do you have a clue what could cause this behaviour?

**Comment by istarkov** [comment]
Could you provide jsfiddle with warning, If you see provided jsfiddles have no warnings

**Comment by acdlite** [comment]
It probably has to do with this line: https://github.com/acdlite/recompose/blob/master/src/packages/recompose/onlyUpdateForPropTypes.js#L22

**Comment by wuct** [comment]
I am going to close this issue because it's no longer active. Please feel free to reopen it if you have further questions.
