### ISSUE TITLE
[Idea/proposal] enforce ’functional stateless components’?

### ISSUE THREAD

**Issue by vectorsize** [acdlite/recompose#218]
I'm a big fan of [Deku](https://github.com/anthonyshort/deku/blob/master/docs/basics/components.md)'s API and how they enforce ’functional stateless components’ by passing everything as arguments to their life-cycle events.

It's easy to imagine how recompose could do something like that:

``` js
const enhance = lifecycle({
  componentDidMount(props) {
    // no "this" usage here
  }
})
```

Perhaps I'm overlooking certain cases where you might need accessing the object, but probably could also be passed as arguments.

However I'm not sure if you would be interested in doing that at all?
I really like recompose and the ideas behind it, and I'd love to see both ideas come together!

Any thoughts on that? would be happy to help if needed :)

**Comment by istarkov** [comment]
What the problem with using `this`?

**Comment by wuct** [comment]
I am going to close this issue because it's no longer active. Please feel free to reopen it if you have further input.
