### ISSUE TITLE
[rx] props stream never ends

### ISSUE THREAD

**Issue by jeron-diovis** [acdlite/recompose#220]
When `ComponentFromStream` is unmounted, it's obvious that `props$` stream will no more receive new values – i.e., it's ended.
So, maybe, it makes sense to call `observer.complete()` in `componentWillUnmount`?
It can simplify performing cleanup on unmount, without need to use `lifecycle` helper and implicitly convert our functional components into classes.

Before:

``` js
compose(
   mapPropsStream(props$ => {
       ...setup some handlers and cleanup function...
       return props$.combineLatest(...);
   }),
   lifecycle({
      componentWillUnmount() {
          this.props.doSomeCleanup();
      }
   }),
   MyFunctionalComponent
)
```

After:

``` js
componentFromStream(props$ => {
    ...setup some handlers and cleanup function...
    props$.doOnCompleted(doSomeCleanup);
    return props$.combineLatest(..., MyFunctionalComponent);
})
```

**Comment by istarkov** [comment]
rxjs5 contains `finally` operator https://github.com/ReactiveX/rxjs/blob/master/src/operator/finally.ts
which u can use for cleanup.

As current implementation already calls unsubscribe https://github.com/acdlite/recompose/blob/master/src/packages/recompose/componentFromStream.js#L49

**Comment by jeron-diovis** [comment]
Ok, `finally`.

Unsubscribing causes `complete` to be called? Can you explain? (I don't know spec)
Because now I'm using recompose with Kefir observables, and it's `onEnd` callbacks are not called when component is unmounted.

**Comment by jeron-diovis** [comment]
Also,
>which u can use for cleanup
How can I get access to that observer? It is only available [here](https://github.com/acdlite/recompose/blob/master/src/packages/recompose/componentFromStream.js#L14). I have only `props$` stream, nothing more.

**Comment by istarkov** [comment]
https://jsfiddle.net/2j2esxyL/
Click Off button, see `Done` in console.

**Comment by jeron-diovis** [comment]
Hmmm, ok, thanks for example.

Probably it's implementation details of particular lib. https://jsfiddle.net/0og8khvm/ – no message in console on clicking "OFF".

**Comment by umidbekkarimov** [comment]
@istarkov 

> rxjs5 contains finally operator

But `.finally` does not pass last stream value

```javascript
const enhancer = compose(
  connect((state) => ({ count: state }), {increment, decrement, cleanup}),
  mapPropsStream((propsStream) => {
    const cWUStream = propsStream
        .finally((props) => {
            // props === undefined
            props.cleanup()
        })
        .last()
        .do((props) =>{
            // never calls
            props.cleanup()
        })
        .startWith(null)

    return propsStream.combineLates(cWUStream, (props) => props)
  })
)


```

**Comment by wuct** [comment]
I agree we should call `observer.complete()` in `componentWillUnmount`. To achieve this feature, maybe we can bind the observer to the class properties and call it directly, instead of passing props via the `change-emitter`. Something like:

```js
  class ComponentFromStream extends Component {
    state = { vdom: null };

    observer = null

    props$ = config.fromESObservable({
      subscribe: observer => {
        this.observer = observer 
        return { unsubscribe: this.observer = null }
      },
      [$$observable]() {
        return this
      }
    });

    // Stream of vdom
    vdom$ = config.toESObservable(propsToVdom(this.props$));

    componentWillMount() {
      this.subscription = this.vdom$.subscribe({
        next: vdom => {
          this.setState({ vdom })
        }
      })
      this.observer.next(this.props)
    }

    componentWillReceiveProps(nextProps) {
      this.observer.next(nextProps)
    }

    shouldComponentUpdate(nextProps, nextState) {
      return nextState.vdom !== this.state.vdom
    }

    componentWillUnmount() {
      this.observer.complete(this.props) // call `complete`
    }

    render() {
      return this.state.vdom
    }
  }
```

It's just a quick solution comes into my mind. @istarkov how do you think?

**Comment by istarkov** [comment]
I don't think so
for now we have the same behavior for props$ as for any multicasted observable in original rxjs

[Example](https://jsfiddle.net/tbze0gp3/)

```
const props$ = Rx.Observable.interval(500).share();

const subscr = props$
  .finally(() => console.log('finally'))
  .last()
  .do(() => console.log('last'))
  .subscribe();

setTimeout(
  () => subscr.unsubscribe(),
  3000
);
```

`finally` is logged but `last` is not, as it's expected. 

The same we have at Recompose [Example](https://jsfiddle.net/zue113sz/1/)

So it's expected behavior.

**Comment by istarkov** [comment]
Looks like calling `complete` is a good idea. 
As props$ observable is really completed.

**Comment by wuct** [comment]
Yup, it's a good practice to call `complete` when a stream is completed.

**Comment by umidbekkarimov** [comment]
@wuct `componentFromStream` needs `change-emitter` to maintain multiple subscriptions to props stream, eg.:

```javascript
 mapPropsStream((props$) => {
   const a$ = props$.pluck('a')
   const b$ = props$.pluck('b')

   return props$.combineLatest($a, $b, (props, a, b) => ({...props, c: a + b}))
})
```

[Here](https://github.com/umidbekkarimov/recompose/commit/e1526499377022a7732578c8692d5e13d2c220e6#diff-e1d016e949035e1aa76916d1792cd9e2R55) add extra argument to `.emit` to solve this problem

**Comment by istarkov** [comment]
no need in second argument, checking that props is not an object is enough. so emitting without arguments will be complete call

**Comment by wuct** [comment]
@umidbekkarimov You are right. Thanks for correcting me.
