### ISSUE TITLE
branch to complicated

### ISSUE THREAD

**Issue by einarlove** [acdlite/recompose#226]
Been using [branch](https://github.com/acdlite/recompose/blob/master/docs/API.md#branch), but find it to complicated. Am I missing a use-case where you need to pass 3 arguments with 2 HOC?

This is how it is today
```jsx
recompose(
  branch(
    props => !!props.loading,
    () => props => <Loader name={props.name} />
    component => component
  )
)(Component)
```

Why can't it just be like this?
```jsx
recompose(
  branch(
    props => !!props.loading,
    props => <Loader name={props.name} />
  )
)(Component)
```

If this is against the purpose of branch, I would suggest adding:
```jsx
diverge(
  test: (props: Object) => boolean,
  to: Component,
): HigherOrderComponent
```

**Comment by acdlite** [comment]
How about if the third argument defaulted to the identity function? In the original design, I avoided default parameters because Recompose helpers used to be curried, but now it shouldn't be a problem.

**Comment by acdlite** [comment]
A PR for this would be appreciated!
