### ISSUE TITLE
Question: `lifecycle` and server-side rendering?

### ISSUE THREAD

**Issue by lukewestby** [acdlite/recompose#23]
If I have a component which should be able to return markup on the server but then hook into a browser API after being mounted I don't believe `lifecycle()` will work because `setup()` is called in the constructor and will throw when instantiated on the server.

A work-around would be to create an abstraction over setting up the component's client-side behavior which is just a no-op on the server, but React already provides `componentDidMount()` for this case and so seems less complex and more idiomatic.

Is there a plan for allowing lifecycle setup within `componentDidMount()` instead of the constructor?

**Comment by acdlite** [comment]
Not sure about this. If you need to use `componentDidMount()` or any of the other component lifecycle methods, at that point you should probably use a class component.

**Comment by lukewestby** [comment]
Thanks for the response, and I totally understand if you don't want to include this feature at the moment, but just for discussion now:

This library covers most of the useful `Component` API surface, which I think `componentDidMount()` is in at least in the case that I mentioned, and its stated intention seems to be to eliminate the need for extending `Component` or calling `React.createClass`in favor of functional style, so I guess I'm having a hard time understanding why `componentDidMount()` would not qualify. Could you explain why you think `componentDidMount()` is better handled by extending `Component`?

**Comment by istarkov** [comment]
IMHO: 
The most common case in componentDidMount is to use `refs` for component Dom events, for jQuery plugins like integration,  
(the other case is for events like `resize`)

But `refs` for stateless component is gone every new render, so it's impossible to use this common case.

**Comment by lukewestby** [comment]
I definitely see where you are coming from and agree when it comes to using `refs`. Another example that I have frequently encountered, however, is for components that need to update state on `window` scroll event for some visual effect, virtualization purposes, etc. In these cases `refs` haven't been necessary but I do need to call `window.addEventListener` on the client. I get that this use case might be too specific to warrant inclusion in the library itself. It would be totally fine to write a custom HoC and use `compose()` -- excellent API design, btw :smile: 

Thanks!

**Comment by acdlite** [comment]
I'm hesitant to add support for other lifecycle methods because lifecycle methods usually need to call `setState()` or save references to a subscription on the component instance. Both of these go against the functional nature of Recompose's API. I'm still not sure if the existing `lifecycle()` helper shouldn't be removed.

I'm going to close this issue, but if you have an idea for an API, please let me know :)
