### ISSUE TITLE
How can I access the ref of the BaseComponent or any level of the components?

### ISSUE THREAD

**Issue by stupidisum** [acdlite/recompose#232]

**Comment by wuct** [comment]
@stupidisum Would you mind to create a question on [StackOverflow](http://stackoverflow.com/) and use `recompose` tag? Because it is easier for other people to find and answer your question. Thanks in advance!

**Comment by stupidisum** [comment]
I got the error...
```
Creating the new tag 'recompose' requires at least 1500 reputation. Try something from the existing tags list instead.
```

**Comment by wuct** [comment]
@stupidisum Oops, would you mind to use `react` tag temporarily?

**Comment by montogeek** [comment]
Is this still valid? I can create it :)

**Comment by wuct** [comment]
@montogeek It would be great! Thanks in advance.

**Comment by stupidisum** [comment]
Thank you very much!

**Comment by montogeek** [comment]
Ok, the only way to create a tag is by asking a question, I am going to post this question

**Comment by montogeek** [comment]
There you go http://stackoverflow.com/questions/39418581/how-can-i-access-the-ref-of-the-basecomponent-or-any-level-of-the-components

**Comment by montogeek** [comment]
As a note from: http://stackoverflow.com/help/privileges/create-tags :
> However, note that:

> on some sites, new tags will be automatically culled and removed from the system if they are not > used by at least 1 other question in a 6 month period.
> meta tags, tags that cannot stand alone as the only tag on a question, are not allowed.

**Comment by stupidisum** [comment]
Thank you again for creating the question.

**Comment by wuct** [comment]
@montogeek Thanks a lot!

**Comment by wuct** [comment]
@stupidisum I have answered the question on the StackOverflow. I am going to close this issue. Please feel free to reopen it if you have further questions.

**Comment by wuct** [comment]
#239
