### ISSUE TITLE
onlyUpdateForPropTypes will still be supported?

### ISSUE THREAD

**Issue by deoqc** [acdlite/recompose#237]
From the [docs](https://facebook.github.io/react/warnings/dont-call-proptypes.html):
> In a future major release of React, the code that implements PropType validation functions will be stripped in production. Once this happens, any code that calls these functions manually (that isn't stripped in production) will throw an error.

I wonder the effect on `onlyUpdateForPropTypes`, will it still be supported?

**Comment by istarkov** [comment]
I think it still be supported, 
As i read correctly not `static propTypes` will be stripped, but React internal logic to validate using this object.
So this https://github.com/acdlite/recompose/blob/master/src/packages/recompose/onlyUpdateForPropTypes.js#L22 still be working as now.

**Comment by deoqc** [comment]
Thanks @istarkov, you seem correct.
