### ISSUE TITLE
[HOC suggestion] withNamespacedProps

### ISSUE THREAD

**Issue by jtadmor** [acdlite/recompose#245]
Hey (again),

I think it would be cool to have a HOC that helped separate out your props by distinct name space.

You would call it with a list of names, and it would place your props into separate objects based on those names (e.g. 'container' will "capture" 'containerStyle' or 'containerClassName' but not 'container' or 'className'.)

`const enhance = withNamespacedProps('container', 'header', 'body')`

This would turn something like:

```
{
  header: 'Namespacing Your Props is Great!',
  body: 'It creates a consistent and easily understood API for your component...:'
  headerClassName: 'text-large text-fancy',
  containerStyle: {{ color: 'red' }},
  bodyClassName: 'text-medium text-simple'
}
```

into:

```
{
  header: 'Namespacing Your Props is Great!',
  body: 'It creates a consistent and easily understood API for your component...:',
  headerProps: {
   className: 'text-large text-fancy'
  },
  containerProps: {
   style: { color: 'red' }
  },
  bodyProps: {
    className: 'text-medium text-simple'
  }
} 
```

Then you can do:

```
const Enhanced = enhance(MyBlog)

MyBlog = ({ headerProps, containerProps, bodyProps, header, text }) => (
  <div {...containerProps}>
    <span {...headerProps}>{header}</span>
    <span {...bodyProps}>{body}</span>
  </div>
)

// In some component
<Enhanced
  headerClassName="text-large text-fancy"
  containerStyle={{ color: 'red' }}
  bodyClassName="text-medium text-simple"
  header="Namespacing Your Props is Great!"
  body="It creates a consistent and easily understood API for your component...:"
  />
```

(I have a small library called `prop-map` (https://github.com/jtadmor/prop-map) that implements this, it would be fairly simple to similar logic into a HOC and I'd be happy to submit a PR)

(editing for hopeful clarity)

**Comment by istarkov** [comment]
I have reread this 3 times, and still can't understand what this HOC do. Could you explain this in a shorter clear form?

**Comment by jtadmor** [comment]
Tried to clarify.

**Comment by farism** [comment]
Seems like a lot of magic - and very domain specific - with all the prop name slicing/reconstructing, probably not something that belongs in the library.

-1

**Comment by wuct** [comment]
I am agree with @farism. Besides, matching string might introduce a performance issue in production.

**Comment by jcheroske** [comment]
I'm encountering some prop namespacing issues using recompose, and I'm wondering what other folks are doing to avoid prop collisions? The problem that I'm running into is how do I add props to the props pipeline when I have no control over what props might already be in that pipeline? When building a recompose-based HOC, there seem to be several categories of props:

1 Props that have nothing to do with the HOC and are just passing through.
2 Props that are passed into the HOC, utilized, and not passed onward.
3 Props that are created within the HOC and passed down to the wrapped component.
4 Props that are created within the HOC and consumed within the HOC. Not passed to the wrapped component.

The main danger involves 3 and 4. What I just started doing is using PropTypes to enforce unset props:
```
const propTypes = {
  exampleIncomingProp: PropType.string.isRequired, // or whatever
  internalProp: PropType.oneOf([undefined]) // warn if the prop comes in from outside.
}

const enhancer = compose(
  setPropTypes(propTypes),
  withState('internalProp', 'setInternalProp', 'foo'),
  // the rest of your HOC
)
```

**Comment by Jephuff** [comment]
I solved this by defining my own compose that is name spaced. This could also be done with mapProps, but I wanted to be able to have one call where it was needed.

```
function composeNS(ns, ...funcs) {
  if (funcs.length === 0) return arg => arg;

  return [
    Wrapped => (props) => Wrapped({ parentProps: props }),
    ...funcs,
    Wrapped => ({ parentProps, ...props }) => Wrapped({ ...parentProps, [ns]: props }),
  ] 
    .reduce((a, b) => (...args) => a(b(...args)));
};
```

working on creating a npm package, I'll be adding a readme and tests shortly https://www.npmjs.com/package/composens

usage on it's own
```
const App = composeNS(
  'foo',
  withProps({foo: 2})
);
```
usage combined with non namespaced HOC
```
const App = compose(
  withProps({ bar: 24601 }),
  composeNS(
    'foo',
    withProps({foo: 3})
  )
);
```
codepen: https://codepen.io/jephuff/pen/dWypwe
