### ISSUE TITLE
Make symbol-observable a peer dependency or update it to @latest

### ISSUE THREAD

**Issue by iskandersierra** [acdlite/recompose#246]
Right now recompose have a dependency on "symbol-observable": "^0.2.4" (not peer but direct) so I end up with this dependencies. 

recompose@0.20.2
--------symbol-observable@0.2.4
rxjs@5.0.0-beta.11
symbol-observable@1.0.2

I don't know much on how rxjs depends on symbol-observable, but certainly having two symbol-observable libraries is not a good thing.

**Comment by istarkov** [comment]
Please provide a PR. We will accept it.
