### ISSUE TITLE
withReducer should initialize state using default argument

### ISSUE THREAD

**Issue by just-boris** [acdlite/recompose#247]
Usually, in Redux reducers can provide initial state from themselves, using default argument value

```js
const counterReducer = (count = 0, action) => {
  switch (action.type) {
    case INCREMENT:
      return count + 1
    default:
      return count
  }
}
```

This reducer works within redux store but doesn't work with recompose as expected.

Is there any chance to fix this? For example, call reducer with arbitrary action to get the initial state only when the last argument (initial state) for `withReducer` is not provided. It will not be breaking for current users, but it will increase reusability of reducers, so you can change them from in-place with recompose to global with redux and the other way round.

**Comment by istarkov** [comment]
I see the problem, [here](https://github.com/acdlite/recompose/blob/master/src/packages/recompose/withReducer.js#L10-L12) initial state should be initialized like in redux with action of type https://github.com/reactjs/redux/blob/master/src/createStore.js#L11

So lines above becomes 

```javascript
      state = {
        stateValue: reducer(
          typeof initialState === 'function'
            ? initialState(this.props)
            : initialState,
         { type: ActionTypes.INIT }
        )
      };
```

**Comment by istarkov** [comment]
Do you want to provide a PR?

**Comment by just-boris** [comment]
If the basic idea is acceptable, I do.

**Comment by istarkov** [comment]
Yes, acceptable.

**Comment by billyjanitsch** [comment]
FYI, I believe this was done by design. @acdlite has stated several times that if he could co-design redux again, he would not allow reducers to specify an initial state.
