### ISSUE TITLE
withState best practices

### ISSUE THREAD

**Issue by maitriyogin** [acdlite/recompose#257]
Hi,
I'v been using withState for a while now and have gone backwards and forwards from having only one withState hoc with a state object with many state attributes to having multiple withState's for each individual prop :

```
withState('state', 'setState', {isLoading, name})
```

```
withState('isLoading', 'setLoading', false)
withState('name', 'setName', 'stephen');
```

I'm kind of vering more to the second approach as its specificity lends to a more fine grained approach in handlers, I can skip spreading the `state` object, and it matches the props approach that recompose gives us. i.e. the state values are just props ...

Would love to know what you guys think as the docs kind of leave this open, although the 'stateName' does kind of suggest it can be whatever you want ...
Look forward to your replies,

/Stephen.

**Comment by wuct** [comment]
Hi Stephen,

Thanks for asking!

Both approaches are good. For more complex situations, you can also consider to use withReducer, or introduce Observable. All approaches come with their own pros and cons, so it depends on how you want to architecture your components.

**Comment by wuct** [comment]
Related to #319.

I am going to close this issue. Please feel free to reopen it.

**Comment by andrewjmead** [comment]
Thanks for the info!

A potential downside for a single state handler is that you no longer have the ability to provide just the updates in the return value from `setState`. You need to include the unchanged values too.

Will work:

```javascript
setState((state) => ({
  ...state,
  counter: state.counter + 1
}))
```

Won't work:
```javascript
setState(({counter}) => ({
  counter: counter + 1
}))
```

**Comment by euvl** [comment]
I wrote this, hope anyone will find it useful:

```ks
export default initialState =>
  compose(
    withState('state', 'setState', initialState),
    withHandlers({
      updateState: ({ setState, state }) => patch => setState({ ...state, ...patch }),
      resetState: ({ setState }) => () => setState(initialState)
    })
  )
```

**Comment by zomars** [comment]
@euvl can you explain how do you use it? 🤔

**Comment by euvl** [comment]
```

const Component = compose(
  withEnhancedState({
    todos: [],
    updatedAt: null,
    createdAt: Date.now(),
  }),
  withHandlers({
    handleAddTodo: ({ state, updateState }) => value => {
      updateState({
        todos: [...state.todos, value],
        updatedAt: Date.now(),
      })
    },
  })
)(View)
```
