### ISSUE TITLE
Balancing enhancers with simplicity

### ISSUE THREAD

**Issue by grsmvg** [acdlite/recompose#258]
I like recompose a lot, but I'm struggling with where I should stop using enhancers en just put stuff inside normal classes / function components.

Let's say we have this fictional component, (using MomentJS). It displays a month name and day numbers, given the first day of the week:
```
// Imports...

const Week = props =>
  <div>
    <div className="monthName">
      {props.days[6].format('MMM').toUpperCase()}
    </div>
    <div className="days">
      {props.days.map(day =>
        <div className="day">
          day.format('D')
        </div>
      )}
    </div>
  </div>

const enhance = compose(
  setPropTypes({
    firstDay: momentPT.momentObj.isRequired,
  }),
  shouldUpdate((props, nextProps) =>
    !props.firstDay.isSame(nextProps.firstDay, 'day')
  ),
  mapProps(props => ({
    days: range(7).map(n => props.firstDay.clone().add(n, 'day')),
  }))
)

export enhance(Week)
```

Instead, I could also add an additional withProps. Or am I taking this to the extreme?
```
  setPropTypes(...),
  shouldUpdate(...),
  mapProps(...),
  withProps(props => ({ monthName: props.days[6].format('MMM').toUpperCase() }))

and then:

  <div className="monthName">
    {props.monthName}
  </div>
```

And what about setPropTypes: should you define them always after usage of map/withProps? Or use them only for those props of which the values are calculated/obtained from outside of the component file ( JSX props, Redux connect() ). I like the latter, because otherwise you often have to define several setPropTypes within the same compose().

**Comment by istarkov** [comment]
Hi, in a lot of cases your writing style should depends on your own code style.
What you like, what code your teammates like. 
We become a robots if we will start to write everything similar.

In my case I prefer to move all long computations (long not means time but number of code lines)
into `withProps`, `withPropsOnChange` and short computations into render itself.
But this is not a rule, sometimes I can move all into render, or all into enhancer. 

About setPropTypes - I prefer not to use them at all, as not a lot bugs could be found/created without that checks IMO. So can't say about usage of `setPropsTypes` a lot, I thought that just one at the top is enough.

**Comment by grsmvg** [comment]
> But this is not a rule, sometimes I can move all into render, or all into enhancer.
There are no performance issues when using multiple map/withProps in a row (with other enhancers in between)? Is this also where component squashing comes into play?

> About setPropTypes - I prefer not to use them at all, as not a lot bugs could be found/created without that checks IMO.
I guess we have different coding styles then 😃. I tend to mess around with my Redux state structure and forget about that small component somewhere that also depends on the structure. They saved me already a lot of times.

**Comment by istarkov** [comment]
Hi, 
a lot of recompose enhancers like `mapProps, withProps` will give you almost zero performance issues as combining them sequentially, will be just function calls, [see here](https://github.com/acdlite/recompose/blob/master/src/packages/recompose/utils/createEagerElementUtil.js#L11-L14) for more info.

```javascript
compose(
withProps(...), // function call
withProps(...), // function call
withProps(...), // depends on functional referential equality of BaseComp
)(BaseComp)
```

function calls are fast.

BTW even without optimization above, in my practice I never saw a real task where the performance was somehow affected with the number of recompose enhancers. 
Moving all recompose logic into one Component (without optimizations you could do having all code in one place) never helped me to improve performance.

**Comment by grsmvg** [comment]
Thanks @istarkov , will close the issue for now. Any other thoughts are always welcome.
