### ISSUE TITLE
[HOC suggestion] defer

### ISSUE THREAD

**Issue by oliviertassinari** [acdlite/recompose#261]
Waiting for the **fiber reconciliation** implementation to be shipped, batching the rendering of the React virtual DOM is quite useful in some cases.

E.g. Rendering your whole screen takes some time. You want to increase the perceived performance by rendering the layout first, then the data.

Here is an example of implementation:

``` jsx
// @flow weak

import { Component } from 'react';
import createHelper from 'recompose/createHelper';
import createEagerFactory from 'recompose/createEagerFactory';

const defer = (BaseComponent) => {
  const factory = createEagerFactory(BaseComponent);

  return class extends Component {
    state = {
      show: false,
    };

    componentDidMount() {
      /* eslint-disable react/no-did-mount-set-state */
      this.timer = setTimeout(() => {
        this.setState({
          show: true,
        });
      }, 0);
      /* eslint-enable react/no-did-mount-set-state */
    }

    componentWillUnMount() {
      clearTimeout(this.timer);
    }

    timer = null;

    render() {
      if (!this.state.show) {
        return null;
      }

      return factory(this.props);
    }
  };
};

export default createHelper(defer, 'defer', true, true);
```

**Comment by istarkov** [comment]
Hi, nice idea but it will have a problem with server rendering.
Having nice big server I want to render all the content and I can't just set check like 'typeof window === undefined ? <MyComponent> : null' above. 

As it will cause blinking on the client side, 
- content will be rendered on server
- disabled by client
- enabled by client
So it will add some kind of logic like - if content was already rendered don't return null.
Isn't it looks too hard for simple library?

**Comment by wuct** [comment]
@istarkov How do we know a component has been rendered on a server?

**Comment by istarkov** [comment]
@wuct  some boolean variable :-) setted on a server :-)

**Comment by oliviertassinari** [comment]
> Hi, nice idea but it will have a problem with server rendering.

Right, you gonna lose the SSR benefits when using this implementation of `defer`.
Who could we improve it?
I think that increasing the time to interaction over the visual blink is a good tradeoff.
We need a way to set `this.state.show` to `true` before the component is mounting.

>  How do we know a component has been rendered on a server?

As far as I know react don't provide any API for this.
A good heuristic could be to have a singleton on the client side and a check on `[data-reactid=X]` in the DOM.
I.e. The singleton goal would be to determine if we are performing a reconciliation. It needs to be shared across different instances of `defer`.

**Comment by istarkov** [comment]
Want to add:
implementation above can be done with current recompose

```javascript
mapPropsStream(props$ => Observable.empty().delay(0).concat(props$))
```

Here is other fine idea https://twitter.com/_developit/status/789627747836399616

Having `async` render we could just `await sleep(N)`

**Comment by wuct** [comment]
I am going to close this issue because it's no longer active. Please feel free to reopen it.
