### ISSUE TITLE
Add babel-plugin-lodash configuration into README

### ISSUE THREAD

**Issue by grsmvg** [acdlite/recompose#263]
I think it would be nice to have something like babel-plugin-lodash for recompose. That way, we don't have to define all separate recompose/x imports, while keeping are bundle size small.

If more people think this is a good idea, I'm happy to start a repo for it.

See:
https://github.com/lodash/babel-plugin-lodash

**Comment by ntkoso** [comment]
You can use this plugin with recompose and other modules.

Change babel-plugin-lodash config to:
```js
['lodash', { id: ['lodash', 'recompose'] }]
```

You can look at [test fixture with ramda](https://github.com/lodash/babel-plugin-lodash/tree/master/test/mixed-fixtures/async-bound-ramda)

**Comment by grsmvg** [comment]
Cool! Thanks for pointing that out for me.

**Comment by wuct** [comment]
We should add this instruction to README.md.

**Comment by kjcpaas** [comment]
HI @wuct. This instruction has been really helpful in our project. Can I add this to the README? (unless someone's already working on it)

**Comment by wuct** [comment]
@kjcpaas I think there is no one working on it. A PR is appreciated. Thanks in advance!

**Comment by kjcpaas** [comment]
Hi, I already submitted a PR for this. Thanks for letting me work on int!

**Comment by wuct** [comment]
@kjcpaas thanks for your contribution!

**Comment by wuct** [comment]
Closed because it's already in README now.
