### ISSUE TITLE
withState produces component with weird displayName

### ISSUE THREAD

**Issue by just-boris** [acdlite/recompose#266]
Currently, when use withState wrapper it produces component, that is displayed as `_class2` in React-Devtools. Also, I can't use 'enzyme' either, because it also looks gets displayName in the same way.

I have reproduced bug as a simple JSFiddle
https://jsfiddle.net/a7yLqrj0/1/

`TestComponent` is displayed correctly, therefore I expect something more readable for StatefulComponent as well, something like `withState(TestComponent)`

**Comment by istarkov** [comment]
Hi,
`jsfiddle` is not a good example in this case, 
as recompose generates it's own `displayName` for each component only in development mode, see [here](https://github.com/acdlite/recompose/blob/master/src/packages/recompose/createHelper.js#L7)

`jsfiddle` uses the package which builded with `NODE_ENV=production`

**Comment by istarkov** [comment]
Here is an examples in tests
and having that tests are passing the reason you don't see the normal names is in NODE_ENV variable

https://github.com/acdlite/recompose/blob/287674218265667661a048f2db83c96fd1c4be54/src/packages/recompose/__tests__/mapProps-test.js#L15

https://github.com/acdlite/recompose/blob/287674218265667661a048f2db83c96fd1c4be54/src/packages/recompose/__tests__/withState-test.js#L9

**Comment by just-boris** [comment]
I am sorry! You're right, everything works as expected.

I have some other `_class2` in my code that made me think that there is a problem in recompose.

**Comment by istarkov** [comment]
No need to sorry, we are all doing mistakes :-) it's just a learning process
