### ISSUE TITLE
allow props access from withReducer 

### ISSUE THREAD

**Issue by droganov** [acdlite/recompose#268]
Make initialState a thunk which accepts both:
```
withReducer('state', 'dispatch', reducer, initialState);
withReducer('state', 'dispatch', reducer, (props, context) => initialState);
```

**Comment by wuct** [comment]
@droganov [The current implementation](https://github.com/acdlite/recompose/blob/master/src/packages/recompose/withReducer.js#L16) has already accepted a function with `props` as the first argument. For `context`, you can use `withContext` to transfer `context` into `props`.

However, the doc is outdated and we should improve it.

**Comment by droganov** [comment]
@wuct cool, thank you, it will work for me.
But it's not a thunk actually, what if func return another func which return a state?

**Comment by wuct** [comment]
I am not sure what you mean. Could you elaborate it?

**Comment by droganov** [comment]
recursion/decoration
At the moment the `initialState` function is pure. There is a (minor) chance one may need to decorate something.

**Comment by wuct** [comment]
We can do a recursion in a pure function and decorate a pure function, can't we?

**Comment by droganov** [comment]
sure, this is minor thing

**Comment by wuct** [comment]
It seems like there is no enough benefit for making a breaking change.

I am going to close this issue now. Please feel free to reopen it if you have further question or suggestion :)

**Comment by droganov** [comment]
sure, thanks for helping
