### ISSUE TITLE
Accessing method of wrapped component after composing

### ISSUE THREAD

**Issue by reintroducing** [acdlite/recompose#269]
Hello,
I have a component called SearchMap that has a public method on it (I know, not ideal, but it is what it is). I want to be able to call that method from a parent component but I'm composing my component as such:
```javascript
const enhance = compose(
    Config,
    connect(makeMapStateToProps, mapDispatchToProps, null, {withRef: true})
);

export default enhance(SearchMap);
```
When I add a ref to SearchMap in my parent I'm getting back Config which doesn't have the method I want to call on it obviously. How can I get back the SearchMap component in my parent so I can call the public method I'd like to call from it?

Thanks for any help offered, much appreciated.

**Comment by alex-wilmer** [comment]
Not possible to extract the public method into its own HOC? That way you can wrap upstream and both parent and SearchMap have access.

**Comment by reintroducing** [comment]
@alex-wilmer The problem is that SearchMap's public method has some things that are specific to SearchMap and the parent needs to execute it with knowledge of those items in SearchMap otherwise it would be pointless to have that method on SearchMap. Hopefully that makes sense :)

**Comment by reintroducing** [comment]
I ended up adding a getWrappedInstance() type method to my HOC that will get the proper instance for me depending on whether its wrapped or not. Problem solved :)

Not sure why I didn't think of that sooner, granted I hadn't looked at this until you posted since I did. Thanks for helping me think about it again, though!

**Comment by alex-wilmer** [comment]
Glad you got it working. I still think it would be better to bring your method higher up in the tree. That's more "the react way" of doing things.

If your entire app consisted of just SearchMap then your app might look like

    App -> 
      connect(mapState, mapDispatch)
      withHandlers({ method: props => args => props.dispatch(args) })
      SearchMap

and if you need to call that method higher up, then its trivial now to wrap `withHandlers` higher up in the tree so both your map and your Config can access it

    App ->
      connect(mapState, mapDispatch)
      withHandlers({ method: props => args => props.dispatch(args) })
      Config ->
       SearchMap
