### ISSUE TITLE
Integrate with 'styled-components'

### ISSUE THREAD

**Issue by degroote22** [acdlite/recompose#270]
This lib is a perfect fit for 'styled-components' but I'm having some issues using both together.
I'm sorry if i've misunderstood the docs or something but I made some very simple reproduction of one issue: http://www.webpackbin.com/NyrRWNBlz
Maybe someone can check it out and see what's happening :)

**Comment by kastigar** [comment]
You've made it wrong. `branch` uses HOC's instead of components. `renderComponent` will help you:
```js
branch(
  (props) => true,
  renderComponent(Black),
  renderComponent(White)
);
```

**Comment by wuct** [comment]
I am going to close this issue because it's no longer active. Please feel free to reopen it if you have further question.
