### ISSUE TITLE
refs best practises

### ISSUE THREAD

**Issue by vaukalak** [acdlite/recompose#282]
I think there should be a way to work with refs somehow. For sure, refs are problematic in stateless components, but let give a try. For now I have a following ~antipattern~ workaround:

```
const Stateless = ({ refs }) => (
  <div>
    <Foo ref={r => refs.store('myFoo', r)} />
    <div onClick={() => refs.myFoo.doSomeStuff()}>
      doSomeStuff
    </div>
  </div>
)

class RefsStore {
  store(name, value) {
    this[name] = value;
  }
}

const enhancer = compose(
  withProps({ refs: new RefsStore() }),
)(Stateless);
```

With this we create a wrapper, to store refs. Something similar to `withState`, but it doesn't trigger component re-render. This code work, but I'm not sure, if it's really ok, from idiomatic point of view. If it ok, we could probably create a new enhancer `withRefs`. If it's not ok, how should we work with this?

**Comment by istarkov** [comment]
Hi, here I wrote `IMO` about refs https://github.com/acdlite/recompose/pull/272

**Comment by wuct** [comment]
Related to #319. We can add this part in the cookbook section.
