### ISSUE TITLE
bind callbacks to props

### ISSUE THREAD

**Issue by istarkov** [acdlite/recompose#29]
It's easy for any class component to get `props` in any event callback, 
having reference to callback not change across render calls.
```javascript
class Blabla ... {
  onClick = () => {
    const props = this.props;
    ... do Some work based on props;
  }
  render() {
     // this.onClick is same every render
     return <BlaBla onClick={this.onClick} />;  
  }
}
```

mapProps cause callback refs to change at every render call (if I need to have access to `props` inside 
callback)

Like
```javascript
mapProps(props => {
  ...props,
  // reference to onClick here changed at every render call
  onClick() { 
  // use props here, also i can't call other methods defined here 
  }
}
```

May It's good to create something like bindToProps HOC,

```javascript
onClick(props, args) {
}

bindToProps({onClick})
...
```

Because every time I start to write stateless component I need to write something like
```javascript
  <BlaBla onClick={(...args) => onClick(props, ...args) } />
```
And I dislike the Idea that every time BlaBla receives a new function reference and lost some of his shouldComponentUpdate optimization.

**Comment by acdlite** [comment]
I've been thinking more about this lately. `mapPropsOnChange()` is supposed to address this, but it's not clear from the documentation.

**Comment by acdlite** [comment]
I think we should rename `mapPropsOnChange()` so it's clearer what it actually does. Perhaps `mapDependentProps()`?

**Comment by istarkov** [comment]
Yes I use `mapPropsOnChange` for this, 
look's like current version of `mapPropsOnChange` is my favorite HOC now :-)
(I almost finished independent of svg libs chart component http://recordit.co/xXaSy4WM2W using just recompose and functional components, 
and mapPropsOnChange is super useful for such component)

About name, I like both :-)

**Comment by acdlite** [comment]
Another idea:

```js
import { Component } from 'react'
import createElement from './createElement'
import createHelper from './createHelper'

const withAttachedProps = (createProps, BaseComponent) =>
  class extends Component {
    attachedProps = createProps(() => this.props)
    render() {
      return createElement(BaseComponent, {
        ...this.props,
        ...this.attachedProps
      })
    }
  }

export default createHelper(withAttachedProps, 'withAttachedProps')
```

`createProps()` is called once, and the returned object (`this.attachedProps`) never changes.

**Comment by istarkov** [comment]
Yes it's better than `mapPropsOnChange(['dispatch'], ...`

**Comment by istarkov** [comment]
Thank You!!!!
https://github.com/acdlite/recompose/pull/81
