### ISSUE TITLE
idiomatic way to handle async requests

### ISSUE THREAD

**Issue by arolson101** [acdlite/recompose#304]
I think a very common use case is a component that displays data fetched asynchronously.  Without recompose, one would issue the request in componentDidMount, keep track of its value in state, and ensure that setState isn't called if the component gets unmounted.  Also, user actions could cause a new request to be issued, so we only want the latest.

I think the solution is to use mapPropsStream, but I'm new to rxjs and recompose, so I was wondering if anyone could give some guidance as to the best way to proceed.

**Comment by arolson101** [comment]
here's my first attempt; it seems to be working.  It will only resolve the latest promise and you don't need to worry about component lifecycle.

```js
const ResolvePromise = (key, loadingRender, errorRender) => compose(
  setDisplayName('ResolvePromise'),
  mapPropsStream((props$) => {
    const promise$ = props$
      .pluck(key)
      .map((promise) => promise.then(value => value, err => err))
      .switch()
      .map(value => ({[key]: value}))

    const rest$ = props$
      .map(props => ({ ...props, [key]: undefined}))

    return rest$
      .merge(promise$)
      .scan((x, y) => Object.assign({}, x, y))
  }),
  branch(
    ({[key]: err}) => err instanceof Error,
    errorRender
  ),
  branch(
    ({[key]: value}) => !value,
    loadingRender
  )
)
```

use it by composing it in with loading and error handlers:
```jsx
const RequestRenderComponent = ({ request }) =>
  <article>
    <div>request: {request}</div>
  </article>

const RequestRender = compose(
  setDisplayName('RequestRender'),
  ResolvePromise(
    'request',
    renderComponent(() => <div>spinner</div>),
    renderComponent(({request}) => <div>error: {request.message}</div>)
  )
)(RequestRenderComponent)
```

then you have a component that you can just pass in a request:
```jsx
const eventuallyReturnString = async(i: number) => {
  await wait(2000)
  if (i % 2 === 1) {
    throw new Error('error message')
  }
  return `finally returned (${i})!`
}

let i = 0

const TestComponent = ({ request, onClick }: any) =>
  <article>
    <PromiseRender request={request} foo='bar'/>
    <button onClick={onClick}>click</button>
  </article>
const Test = compose(
  setDisplayName('Test'),
  withState('request', 'setRequest', () => eventuallyReturnString(i++)),
  withProps(({setRequest}) => ({
    onClick: () => setRequest(eventuallyReturnString(i++))
  }))
)(TestComponent)
```

**Comment by istarkov** [comment]
No idiomatic ways why for any code must be some idiomatic way ;-), 
`mapPropsStream` is really helpful, 
Here I use something similar but with some caching logic etc
https://github.com/istarkov/revue/blob/cbc01375923d2993da41c3c9e808758c2ed8c314/src/CodePresenterContainer.js#L76

In real big projects I prefer to use redux + redux-observable processes for loading data like https://github.com/istarkov/redux-observable-process-fetch (it's very outdated but you can get the idea)

**Comment by khanghoang** [comment]
@arolson101 we were in the same situation and my colleague wrote a small package just for that purpose, it's [redux-api-call](https://github.com/tungv/redux-api-call/) under the hood it uses rxjs to handle request's result streams. Hope it helps (disclaim: I did contribute to package)

**Comment by wuct** [comment]
Might be related #319 in which we can make some recipe about handling async things.

**Comment by wuct** [comment]
As @istarkov said, there are many ways to achieve it. It depends on your project's architecture and your preference. I am closing this issue and please follow #319 if you want to share some code.
