### ISSUE TITLE
`lifecycle` causes swallowing of exceptions thrown in `mapStateToProps`

### ISSUE THREAD

**Issue by oluckyman** [acdlite/recompose#305]
I made a HOC to fetch api on component mount:
```
// helpers.js
// ...
function withDataSources(dsConfigs = [], BaseComponent) {
  return compose(
    setDisplayName('...'),
    lifecycle({
      componentWillMount() {
        dsConfigs.forEach(...fetchApiMethod...)
        // that code causes state update and calling of
        // `mapStateToProps` method (see below)       
      }
    })
  )(BaseComponent);
}

export {
  withDataSources
};
```
And this is how I use it:
```
const mapStateToProps = () => {
  throw 'Unhandled error'; // ← Notice that mapStateToProps throws an error
};

export default helpers.withDataSources(
  dataSourceConfigs, 
  connect(mapStateToProps)(MyComponent)
);
```
after long debugging session I reduced scope to `lifecycle` method. If I comment it out in `compose` function above, then Unhandled error gets its way to console
<img width="674" alt="ss 2017-01-13 at 15 12 51" src="https://cloud.githubusercontent.com/assets/642673/21932836/ddcf1d44-d9a2-11e6-8f10-0230965c88f4.png">
but if `lifecycle` is used then the error is swallowed by this piece of code in React:
<img width="660" alt="ss 2017-01-13 at 15 19 08" src="https://cloud.githubusercontent.com/assets/642673/21932998/b89bd912-d9a3-11e6-9fb7-ecf07c682db2.png">
In debugger I see that `fn()` is Redux' `Connect.prototype.render` function and it throws the error when calling `mapStateToProps`

**Comment by istarkov** [comment]
https://jsbin.com/teyenowohe/edit?js,console,output
What's wrong with this example, error occurred and visible

**Comment by oluckyman** [comment]
in example there is no Redux connect part

**Comment by istarkov** [comment]
How redux connect could affects lifeecycle?

**Comment by oluckyman** [comment]
I don’t know. Maybe it’s not lifecycle, but when I comment it, the error do throws as expected. Just hope for getting help here

**Comment by istarkov** [comment]
Provide a working example to get help, otherwise its impossible. There are enormous number of possibilities. For now it looks like - somewwhere in my code something does not work as expected - how I can help having such description?

**Comment by oluckyman** [comment]
Finally found the root of the problem. Surprise, it was one of the `Promise().catch()` blocks inside of one of our libs.
For folks struggling with similar issues, try to insert `console.log('here!')` in each `try {} catch {}` or `Promise().catch()` blocks in the code running before the crash. This is how I found a catch block where exception thrown by `mapStateToProps` was swallowed silently.
