### ISSUE TITLE
Who uses recompose?

### ISSUE THREAD

**Issue by Silviu-Marian** [acdlite/recompose#314]
Found about recompose through React-Europe :) absolutely loved Andrew's presentation

Considering you're at ~300,000 downloads a month, do you think it's time for a list of organizations and projects that use it?

I'd be happy to submit a PR with the first line for an `INTHEWILD.md`

**Comment by istarkov** [comment]
Until @acdlite will decide, let's place links in current thread. 

Mine:
- [Code presentation-review tool](https://github.com/istarkov/revue) 
- [How to draw thousands markers](https://github.com/istarkov/google-map-thousands-markers)
- [Clustering example for google-map-react](https://github.com/istarkov/google-map-thousands-markers)

**Comment by wuct** [comment]
@Silviu-Marian A PR will be a good start. Please feel free to submit it.

**Comment by Silviu-Marian** [comment]
Thank you for the go-ahead. 
I actually copied React's approach and went for a wiki page here: https://github.com/acdlite/recompose/wiki/Sites-Using-Recompose

I hope it's okay.

**Comment by wuct** [comment]
@Silviu-Marian Thanks! Would you mind to add link to this wiki page in the README as well?

**Comment by Silviu-Marian** [comment]
Great idea. :) Let me do that.

**Comment by wuct** [comment]
Closed by #324
