### ISSUE TITLE
Documentation Question: withProps vs withHandlers

### ISSUE THREAD

**Issue by jcheroske** [acdlite/recompose#315]
In the docs there is an example for `withState` like this:

```
const addCounting = compose(
  withState('counter', 'setCounter', 0),
  withProps(({ setCounter }) => ({
    increment: () => setCounter(n => n + 1),
    decrement: () => setCounter(n => n - 1),
    reset: () => setCounter(0)
  }))
)
```

I'm curious if there is any advantage to rewriting it like so:

```
const addCounting = compose(
  withState('counter', 'setCounter', 0),
  withHandlers({
    increment: ({ setCounter }) => () => setCounter(n => n + 1),
    decrement: ({ setCounter }) => () => setCounter(n => n - 1),
    reset: ({ setCounter }) => () => setCounter(0)
  })
)
```

**Comment by wuct** [comment]
`withProps` will create new functions every time when it get updated; on the other hand, `withHandlers` won't create new functions.

`withHandlers` is useful when you want to pass these functions to other components which `shouldComponent`s are implemented by comparing props shallowly (like how `recompose/pure` do).

**Comment by jcheroske** [comment]
Thanks for the explanation.
