### ISSUE TITLE
mapPropsStream is throwing an error 

### ISSUE THREAD

**Issue by orenklein** [acdlite/recompose#316]
When using mapPropsStream an error is thrown:
"Possible unhandled promise rejection: undefined is not a function (evaluating 'onbserver.complete()')

After a quick overview on the code, seems like the error caused by this change added on 0.22.0: https://github.com/acdlite/recompose/pull/303

**Comment by istarkov** [comment]
Could you provide an example? Or create a PR with failing test?

**Comment by orenklein** [comment]
(Using rx js 4.1.0)
Reproduce example:
const languagesNames = [
    'javascript',
    'C#',
    'Swift'
];
import {mapPropsStream, setObservableConfig} from 'recompose';
import rxjs4config from 'recompose/rxjs4ObservableConfig';
import { Observable } from 'rx';
setObservableConfig(rxjs4config);
const MyComponent = mapPropsStream(props$=>{
    const languagesNames$ = Observable.just(languagesNames).delay(500)
    return Observable.combineLatest(props$,languagesNames$, (props, languagesNames)=>{
        return {...props,languagesNames}
    })
})((props)=>{
    return <View><Text>MyComponent fromOwnProps: {props.text} fromPropsStream: {props.languagesNames.join(',')}</Text></View>
});

export default class App extends Component{

    state = {
        showComponent: true,
    }
    componentDidMount(){
        setTimeout(()=>{
            this.setState({showComponent:!this.state.showComponent})
        },1000)
    }
    render(){
        return (
            <View>
            {
                this.state.showComponent&&
                <MyComponent text="ownProps"/>
            }
            </View>
        );
    }
}

**Comment by istarkov** [comment]
Seems like the problem with `rx`, I've tested this with `rxjs 5` and see no issues
I don't use rxjs 4 in any of my projects, not sure can help without your own investigation.

```javascript
import React from 'react';
import { mapPropsStream, setObservableConfig } from 'recompose';
import { Observable } from 'rxjs';

setObservableConfig({
  fromESObservable: Observable.from,
});

const languagesNames = [
  'javascript',
  'C#',
  'Swift'
];

const MyComponent = mapPropsStream((props$) => {
  const languagesNames$ = Observable
    .of(languagesNames)
    .delay(500);

  return Observable
    .combineLatest(
      props$,
      languagesNames$,
      (props, languagesNamesS) => ({
        ...props,
        languagesNames: languagesNamesS,
      })
    );
})(
  props => <div>A: {props.text} B: {props.languagesNames.join(',')}</div>
  );


export default class App extends React.Component {

  state = {
    showComponent: true,
  }

  componentDidMount() {
    setTimeout(() => {
      this.setState({ showComponent: !this.state.showComponent });
    }, 100);
  }

  render() {
    return (
      <div>
        {
          this.state.showComponent &&
          <MyComponent text="ownProps" />
        }
      </div>
    );
  }
}
```

**Comment by orenklein** [comment]
I understand. Let's try one last thing - when the timeout is 100, error is not thrown in rx 4 either . I set it to 1000 ms for a reason, because it seems like it occurs only if the unmounting called after languagesNames$ completes.
Try to change the setTimeout to setInterval and 100 to 1000.

**Comment by istarkov** [comment]
Im pretty sure the problem is not in `recompose` code,
there is no issue at all to call `observer.complete` when stream ends
(In case of rx 4 `onCompleted` will be called https://github.com/acdlite/recompose/blob/master/src/packages/recompose/rxjs4ObservableConfig.js#L9)
You can try to downgrade your example to non react-recompose version, and be sure the error will stay in.

**Comment by orenklein** [comment]
Indeed, there is no issue using rx 5, only when using rx 4. 
I'll try that, thank you.
