### ISSUE TITLE
branch API Addition

### ISSUE THREAD

**Issue by timkindberg** [acdlite/recompose#318]
I'm not sure if this is true but I feel like `branch`'s 2nd and 3rd params are ALWAYS either a `renderComponent` or `renderNothing`. 

If that's true, why not remove the need to call 'renderX' methods and just allow passing in a Component reference, like so:

```
branch(isTrue, MyComponent, MyOtherComponent)
```

You could then also expose a `Nothing` component to replace the `renderNothing` method.

```
branch(isFalse, Nothing)
```

Am I correct in assuming that the 'renderX' methods exist solely for paired usage with `branch`?

**Comment by wuct** [comment]
Besides `renderNothing` or `renderComponent`, you can use any HoC/HoF with `branch`. For example, you can build something like:

```js
branch(
  ...,
  compose(
     withState(...),
     withHandlers(...),
     ...
  ),
  ...
)
```

This composition feature is really powerful. If we switch to passing components, we lose this ability.

**Comment by timkindberg** [comment]
Ah ok I see. I'd not used it that way yet, but it's good to know. Thanks.
