### ISSUE TITLE
Add Cookbook section on README

### ISSUE THREAD

**Issue by timkindberg** [acdlite/recompose#319]
I'm seeing a lot of requests for new HOCs that are for more specific needs. Since this library is really a tool to help with creating custom HOCs, perhaps there is a place we can share common recipes, like a cookbook. Perhaps gists or jsbins? It could be community driven mostly (though I'd love to see some recipes from the library authors out of curiosity).

**Comment by wuct** [comment]
It's a good idea. A PR will be welcome. Add a cookbook section to the current README and add some links under it would be a good start.

**Comment by rbong** [comment]
So has there been a PR?

**Comment by timkindberg** [comment]
I have a PR in for the recipes wiki I added. Recipes and Cookbook are the same thing so yeah it's in progress. Head over to the wiki to contribute.
