### ISSUE TITLE
Consider releasing v1.0

### ISSUE THREAD

**Issue by levithomason** [acdlite/recompose#320]
Recompose has been around a little while now, churn seems pretty low.  Is there anything in the way of calling it a 1.0 and instead keeping it as a development version?

**Comment by timkindberg** [comment]
And close some issues ;)

Like I mean there are issues that could be closed (dead, won't implement, duplicate, whatever). First rule of managing open source issues... when in doubt.... close it out. It can always be reopened.

**Comment by wuct** [comment]
I will have some time to close some issues on the following weekend.

@istarkov I think we are waiting for @acdlite to release 1.0. Am I right?

**Comment by istarkov** [comment]
Yes you are.

**Comment by wuct** [comment]
I am working on closing issues :)
