### ISSUE TITLE
Why does `wrapDisplayName` get stripped in production?

### ISSUE THREAD

**Issue by lifehackett** [acdlite/recompose#329]
Recompose Version: 0.21.2

In this case I am using `defaultProps` from the recompose lib.  

When `process.env.NODE === 'development'`, the `displayName` for the component is what I expect it to be- `defaultProps(MyComponentName)`

When `process.env.NODE === 'production'`, the `displayName` for the component is `DefaultProps` (note: both the "D" is capitalized and "MyComponentName" is no longer present).

I see that the wrapping of the display name is intentionally omitted here
https://github.com/acdlite/recompose/blob/master/src/packages/recompose/createHelper.js#L7

And believe that the `displayName` of "DefaultProps" is a result of React inferring it from here
https://github.com/acdlite/recompose/blob/master/src/packages/recompose/defaultProps.js#L6

I can "coerce" it to what I want by applying `setDisplayName` after `defaultProps` but that is not ideal.

Am I misusing the lib? Is this a bug? Is this the expected/desired behavior?

**Comment by istarkov** [comment]
Expected, displayName is only needed for dev mode, there is no need in it in production at all so in production JSX sets this value automatically

**Comment by lifehackett** [comment]
Ok. Do you happen to know the rules for how React sets that value in Production? I have found some information saying that it will still use the `displayName` if present and will otherwise fallback to the function/class name, but nothing authoritative.

My use case is that I want to use `displayName` for determining the type of the children in another components render function. So why not use true type checking? Well, we use HOCs in our app and the type checking breaks down under this scenario.  I know `displayName` is not the best solution, but I have a way to enforce unique display names and this was working while also giving us the flexibility of using HOCs.

**Comment by lifehackett** [comment]
It looks like this is handled by Babel. https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-react-display-name

**Comment by GreenGremlin** [comment]
> Expected, displayName is only needed for dev mode, there is no need in it in production at all so in production JSX sets this value automatically

The displayName can absolutely be useful in production. React uses `displayName` when logging errors caught in the render cycle, even in production builds. Also, display names are very useful when using the React developer tools, which is often used in production. It seems to me that stripping the `displayName` should be left to consumer and really should not be a decision that recompose makes for them.

**Comment by GreenGremlin** [comment]
> It looks like this is handled by Babel. https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-react-display-name

That plugin is only works if you're using `createReactClass`, which recompose is not using, as far as I know.
