### ISSUE TITLE
Thoughts about a genProp helper?

### ISSUE THREAD

**Issue by lopatin** [acdlite/recompose#336]
Some Lisps (CL, Clojure) provide a `gensym` function to generate a symbol that is guaranteed to not clash with others that may be in scope. It allows you to create a temporary variable without worrying about what it's called. It's an indispensable tool for writing macros. 

I usually work around the issue of potential prop name clashing by using naming conventions specific to my app. I think that having some kind of `genProp` helper function that generates a prop name that is guaranteed to not clash with other props that may be in the "prop scope" would be very helpful for writing generalized, shareable hocs.

I could be wrong but I'm under the impression that `gensym` keeps track of some global state (probably a counter) to guarantee uniqueness. Not sure if that would make sense here or not.

Just a thought. Feel free to close the issue if this has already been discussed or y'all think this may be (pub intended) out of scope.

**Comment by istarkov** [comment]
What the purpose and usage of this? How it differs from js `symbol`?
 https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Symbol

**Comment by lopatin** [comment]
Oh cool, I haven't used JS Symbols yet. It hasn't even occurred to me to use them as React props. The purpose I had in mind was to be able to write abstractions out of recompose methods that make use of temporary props. I think JS Symbols would address this though, thanks for the quick reply!
