### ISSUE TITLE
Attempting to wrap in dynamic HOC based on props

### ISSUE THREAD

**Issue by bmatto** [acdlite/recompose#339]
Branch originally looked promising for this ... the issue is that the HOC for left or right cannot be dynamic to props.

I think what i'm trying to accomplish is something like this ...

```
const enhance = compose(
  connect(mapStateToProps),
  branch(
    predicateFunction,
    props => dynamicHocFromProps
  )
)
```

Specifically in my case i'm trying to wrap a component in `graphql` HOC based on props.  Any input would be stellar.

Also, this library is stellar! 👍

**Comment by istarkov** [comment]
You can use all the recompose HOCs or your own as usual
```javascript
branch(
    predicateFunction,
    compose(
       hoc0,
       ....
       hocN
    )
  )
```

**Comment by bmatto** [comment]
This makes sense, however I think my issue is that I would like the hoc that follows the predicate function to be dynamic based on props ...

```
brach(
  predicateFunction,
  props => graphql(props.query)
)
```
My thinking here is that the returned HOC would then be applied to the base component.

@istarkov thank for the map lib as well 😄

**Comment by istarkov** [comment]
In your case (if I got it) you don't need branch, just use `withProps` like

```javascript
withProps(props => predicateFunc(props) && graphql(props.query))
```
