### ISSUE TITLE
Remove change-emitter

### ISSUE THREAD

**Issue by TrySound** [acdlite/recompose#342]
It's not neccessary depenency. componentFromStream has only one listener then we can just hold callback and call it any times.

**Comment by istarkov** [comment]
Its not the only place where its used,
 https://github.com/acdlite/recompose/blob/master/src/packages/recompose/createEventHandler.jsp

**Comment by wuct** [comment]
The link above is broken, use this one :) https://github.com/acdlite/recompose/blob/master/src/packages/recompose/createEventHandler.js
