### ISSUE TITLE
new React 15.5 broke build (fixed), lifecycle causes deprecation warnings (in review).

### ISSUE THREAD

**Issue by istarkov** [acdlite/recompose#344]
Fixing now, seems like we have a problem with lifecycle method.

**Comment by istarkov** [comment]
The problem with current lifecycle that it uses `React.createClass`, and this https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.createclass will break support of react 14 users (I'm still using it ;-()

**Comment by istarkov** [comment]
Lifecycle #346

**Comment by MichaelDeBoey** [comment]
Any update on this one? :-)

**Comment by istarkov** [comment]
Yes, 11 days ago, see [Releases](https://github.com/acdlite/recompose/releases/tag/v0.23.0)

**Comment by istarkov** [comment]
I forgot to close issue after enzyme update ;-)

**Comment by MichaelDeBoey** [comment]
@istarkov I still get the following warnings (from the `lifecycle` method): 
`Warning: A Component: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.`

Stacktrace: 
```
printWarning	@	warning.js:36
warning		@	warning.js:60
createClass	@	ReactClass.js:628
(anonymous)	@	lifecycle.js:28
(anonymous)	@	createHelper.js:31
```

**Comment by TrySound** [comment]
@MichaelDeBoey Remove `node_modules` and run `npm install`

**Comment by MichaelDeBoey** [comment]
@TrySound I did this, but still get the warning

**Comment by TrySound** [comment]
@MichaelDeBoey Which version specified in package.json?

**Comment by MichaelDeBoey** [comment]
`"recompose": "^0.21.0",`

**Comment by istarkov** [comment]
https://github.com/acdlite/recompose/releases/tag/v0.23.0

Must be ^0.23.0

**Comment by mistadikay** [comment]
@MichaelDeBoey try this amazing tool https://semver.npmjs.com/ it'll help you to understand how versioning in npm works 😬

**Comment by MichaelDeBoey** [comment]
Doh! --'
Looked over that --' :/

**Comment by sergekovbasyuk** [comment]
I still get this issue😒:
"react": "^15.5.4",
"recompose": "^0.23.4",

**Comment by istarkov** [comment]
What issue? Please be specific.

**Comment by sergekovbasyuk** [comment]
Warnings from the `lifecycle` method: 
`Warning: getInitialState was defined on lifecycle(Component), a plain JavaScript class. This is only supported for classes created using React.createClass. Did you mean to define a state property instead?`

**Comment by istarkov** [comment]
It's not "this issue" as you can see.

`getInitialState` now is not supported in lifecycle as `React.createClass` isn't used any more in recompose.

**Comment by sergekovbasyuk** [comment]
Oh, I see, thanks
