### ISSUE TITLE
How to access props from lifecycle?

### ISSUE THREAD

**Issue by ChenLi0830** [acdlite/recompose#356]
In my current component, the lifecycle methods call methods in `props`. For example, 
```
      componentWillMount() {
        this.props.onEnterScreen();
      }
  
      componentDidMount() {
        this.props.toggleModal();
      }
```

Now I want to rewrite it using recompose's lifecycle as shown below, how do I access the `props`? 
```
lifecycle({
      componentWillMount() {
        props.onEnterScreen(); // <-- props is not defined
      },
})
```

**Comment by TrySound** [comment]
@ChenLi0830 Same way. All methods just extend component class and use it context. It's not quite clean and will be deprecated some day.

**Comment by ChenLi0830** [comment]
Thank you @TrySound, do you mean I can access the props using `this.props`?

**Comment by TrySound** [comment]
Yep

**Comment by TrySound** [comment]
@istarkov We need to update docs

**Comment by timkindberg** [comment]
Please do not deprecate lifecycle! I use it quite often.

**Comment by ChenLi0830** [comment]
It worked, thanks a lot @TrySound! 
Closing this issue.

**Comment by nick121212** [comment]
it worked,thanks a lot @TrySound 
`lifecycle({
        componentDidMount: ()=> {
            this.props.getList(this.props);
        }
    }` not worked yet

**Comment by wuct** [comment]
@nick121212 because `this` in an arrow function doesn't refer to the class instance. This behavior is from ECMAScript.

**Comment by rasdaniil** [comment]
Thanks @wuct , I somehow missed this fact and was struggling for 15 minutes %)

**Comment by shawnmmatthews** [comment]
I'm getting undefined on 
```
export const fetchOptions= lifecycle({  
  componentDidMount() {
   this.props.dispatch(change('form', 'test', this.props.test)); 
  }
});
```

Any thoughts?

**Comment by TrySound** [comment]
@shawnmmatthews Just use class.

**Comment by shawnmmatthews** [comment]
@TrySound, Thanks for the response. Just confirming you are saying just use a class on the markup component vs trying to handle this in the HOC

**Comment by DmitryGG** [comment]
For use `this` in lifeCyrcle method you need to write like this:
```js
lifecycle({
  componentDidMount() { this.props.some /* OK */ }
})
```
Instead of:
```js
lifecycle({
  componentDidMount: () => { this.props.some /* this === undefined */ }
})
```

Arrow function using parent's context.

**Comment by mauroporrasc** [comment]
I agree with @TrySound, at that point is seems better just to use a class.

**Comment by TrySound** [comment]
@LaloHao And how lifecycle HOC solves any of it? It's just a wrapper around class with all class problems.
https://github.com/acdlite/recompose/blob/master/src/packages/recompose/lifecycle.js

**Comment by LaloHao** [comment]
In the same sense any computer language solves the abstraction of writing
direct processor operations

**Comment by mauroporrasc** [comment]
@webberwang 
https://medium.com/@PhilipAndrews/react-how-to-access-props-in-a-functional-component-6bd4200b9e0b
