### ISSUE TITLE
Make mapPropsToStream more modular.

### ISSUE THREAD

**Issue by mrapogee** [acdlite/recompose#369]
Currently, if recompose was used as a peer dependency or the lib was used by multiple packages the setObservableConfig could cause bugs if 2 packages used different stream libraries.

I would recommend a new backwards compatible API:

```typescript
interface ObservableConfig {} // Your current stream config with toESObservable and fromESObservable

interface Recompose {
   mapPropsStream<P>(mapFn: (o: Observable<P>) => Observable<any>): Enhancer // Current behaviour
   mapPropsStream<P, O extends Observable<P>>(
    config: ObservableConfig | () => O, // Can just accept a from function for observables that conform to the ES standard
    mapFn: (o: Observable<P>) => O
  ): Enhancer
}
```
Then at `recompose/most/mapPropsStream`, something like
```typescript
export default partial(mapPropsStream, most.from) // or xstream.from, Rx.from for their respective modules
```

This would also allow well typed `mapPropsStream` typings for each observable library.

This would preserve current behaviour but fix the issue going forward.

Let me know your thoughts, I'd love to create a PR.

**Comment by istarkov** [comment]
Its already done, https://github.com/acdlite/recompose/blob/master/src/packages/recompose/mapPropsStream.js#L13

**Comment by mrapogee** [comment]
That's awesome!

However, the recommended route in the docs could lead to confusing bugs, I don't think global state is a very good idea especially for utility libraries.

If one package author crease a package and uses mapPropsStream with most.js and then another uses the same instance of recompose with bacon, one of the packages would be broken.

**Comment by istarkov** [comment]
Agree, we need to expose config methods at index.js and provide the `documentation` + `tests`.

**Comment by mrapogee** [comment]
Okay, I'll work on a PR

**Comment by istarkov** [comment]
https://github.com/acdlite/recompose/blob/master/src/packages/recompose/index.js#L52
