### ISSUE TITLE
mapPropsStream enhanced input causes cursor to jump to end of input

### ISSUE THREAD

**Issue by jameslaneconkling** [acdlite/recompose#376]
This is an rxjs-react issue, not strictly a recompose issue, but asking here in case anyone has any ideas.

Consider the following useless input field component composed w/ `mapPropsStream()`:

```javascript
const Input = ({ value, onChange }) => (
  <input
    value={value}
    onChange={onChange}
  />
);

const EnhancedInput = compose(
  withState('value', 'setValue', ''),
  mapPropsStream(props$ => (
    props$
      .delay(0)
  )),
  withHandlers({
    onChange: ({ setValue }) => e => setValue(e.target.value)
  })
)(Input);
```

If the user inputs a string of text, then moves the cursor somewhere to the middle of the input text and types a new letter, the letter will be inserted into the middle of the input string (correctly), but the cursor will jump to the end of the input text (incorrectly).

This must have something to do with [this react issue thread](https://github.com/facebook/react/issues/955) on delayed updates to input components.  But the implication is that it's easy to degrade functionality of input forms wrapped in a `mapPropsStream` HOC.

For context, I'm using `mapPropsStream` to issue requests to populate an autocomplete form.  The actual code is something similar to:

```javascript
  mapPropsStream(props$ => {
    const query$ = props$
      .switchMap((props) => (
        fakeAPICall()
      ), (props, response) => ({ ...props, data: response.data }));

    return props$
      .merge(query$);
  }),
```

The input form value is updated _nearly_ immediately (in the above example, simulated by `.delay(0)`).  Operative word being _nearly_...

**Comment by istarkov** [comment]
This is well known react issue, u need to update input immediately without delays.

**Comment by jameslaneconkling** [comment]
I ended up writing a higher order component to cache the input value on update, re-rendering the input form immediately so the cursor does not jump:

```javascript
const cacheInputValue = (value, setValue, selector = v => v) => BaseComponent =>
  class CachedInputValue extends Component {
    constructor(props) {
      super(props);

      this.state = { cachedValue: props[value] };
    }

    componentWillReceiveUpdates(next) {
      this.setState({ cachedValue: next[value] });
    }

    setCachedValue(...args) {
      this.setState({ cachedValue: selector(...args) });
      this.props[setValue](...args);
    }

    render() {
      const wrappedProps = {
        ...this.props,
        [value]: this.state.cachedValue,
        [setValue]: (...args) => this.setCachedValue(...args)
      };

      return <BaseComponent {...wrappedProps} />;
    }
  };
```

to use:

```javascript
const Input = ({ inputValue, updateInputValue }) => (
  <input
    value={inputValue}
    onChange={updateInputValue}
  />
);

const EnhancedInput = compose(
  withState('inputValue', 'updateInputValue', ''),
  mapPropsStream(props$ => (
    // ...some potentially async stuff
  )),
  withHandlers({
    updateInputValue: ({ updateInputValue }) => e => updateInputValue(e.target.value)
  }),
  cacheInputValue('inputValue', 'updateInputValue', e => e.target.value)
)(Input);
```

**Comment by istarkov** [comment]
WTF is `componentWillReceiveUpdates` above ;-)

**Comment by jameslaneconkling** [comment]
ah... yeah, that.  (fixed)
