### ISSUE TITLE
Recompose latest breaking MUI build

### ISSUE THREAD

**Issue by jcheroske** [acdlite/recompose#377]
Just got this from MUI repo:

[10:52] 
Version 0.23.2 of recompose just got published.

Branch    Build failing :rotating_light:
Dependency    recompose
Current Version    0.23.1
Type    dependency
This version is covered by your current version range and after updating it in your project the build failed.

recompose is a direct dependency of this project this is very likely breaking your project right now. If other packages depend on you it’s very likely also breaking them.
I recommend you give this issue a very high priority
![image](https://cloud.githubusercontent.com/assets/3675338/25964029/5b5ad41e-3638-11e7-9df9-fb10f16c11ca.png)

**Comment by istarkov** [comment]
I see, seems like we accidentally removed old babel build, @TrySound ?

**Comment by TrySound** [comment]
@istarkov Yeah it's not published. But exists in relase.js

**Comment by istarkov** [comment]
Seems like `npm` problem, I don't see the babel cli in node_modules/.bin ;-(
will fix now.

**Comment by istarkov** [comment]
npm: 4.2.0

**Comment by istarkov** [comment]
0.23.3 should work

**Comment by istarkov** [comment]
Thank you @jcheroske

**Comment by jcheroske** [comment]
Anytime. Your work makes mine possible.
