### ISSUE TITLE
recompose/rxjsObservableConfig missang in 0.23.2 (0.23.3)

### ISSUE THREAD

**Issue by nonlux** [acdlite/recompose#379]
Given recompose@0.23.1
When I run `ls -l  node_modules/recompose/rxjsObservableConfig.js`
Then I should see :
`node_modules/recompose/rxjsObservableConfig.js`

Given recompose@0.23.2 or ecompose@0.23.2
When I run `ls -l  node_modules/recompose/rxjsObservableConfig.js`
Then I want see :
`node_modules/recompose/rxjsObservableConfig.js`
But I see nothing.

**Comment by istarkov** [comment]
0.23.2 is broken, please use latest version
