### ISSUE TITLE
helper for partially applying props

### ISSUE THREAD

**Issue by py-in-the-sky** [acdlite/recompose#38]
This idea comes from Pete Hunt's [jsxstyle](https://github.com/petehunt/jsxstyle/blob/master/curry.js): a helper to partially apply props to a component.

Here's a rough sketch of what it could look like for a stateless base component:

```js
import omit from 'lodash/object/omit';

const applyProps = (partialProps, baseComponent) => {
  const NewComponent = (moreProps, context) =>
    baseComponent({ ...partialProps, ...moreProps }, context);

  NewComponent.propTypes = omit(
    baseComponent.propTypes,
    key => key in partialProps
  );

  NewComponent.defaultProps = baseComponent.defaultProps;

  return NewComponent;
};
```

And that might not be significantly different from this:

```js
const applyProps = (partialProps, baseComponent) => {
  const NewComponent = (moreProps, context) =>
    baseComponent(moreProps, context);

  NewComponent.propTypes = baseComponent.propTypes;

  NewComponent.defaultProps = {
    ...(baseComponent.defaultProps || {}),
    ...partialProps
  };

  return NewComponent;
};
```

**Comment by py-in-the-sky** [comment]
Ah, never mind.  It looks as though [withProps](https://github.com/acdlite/recompose/blob/master/docs/API.md#withprops) already addresses the use case I had in mind.

**Comment by acdlite** [comment]
`applyProps()` is a good name for it... What do you think about supporting aliases, a la lodash?
