### ISSUE TITLE
Breaking changes in 0.23.2/0.23.3

### ISSUE THREAD

**Issue by reidblomquist** [acdlite/recompose#380]
Initial findings on our end are showing that 0.23.2/0.23.3 includes breaking changes - per https://github.com/callemall/material-ui/issues/6848

looks like this should've at least been a minor version and not a patch.

**Comment by istarkov** [comment]
0.23.2 was broken because of my mistake at release step.
0.23.3 must work and as I think does not contain breaking changes. Could you provide specific details what is broken?

**Comment by miksansegundo** [comment]
Hey, here is my breaking issue: **createHelper.js is missing in v0.23.3**

```
ERROR in ./~/material-ui/styles/withStyles.js
Module not found: Error: Can't resolve 'recompose/createHelper'

ERROR in ./~/material-ui/internal/withSwitchLabel.js
Module not found: Error: Can't resolve 'recompose/createHelper'
```

**Comment by TrySound** [comment]
@miksansegundo Heh. I removed it. It wasn't documented. And it's not so useful. It breaks tree shaking.

**Comment by miksansegundo** [comment]
Material-UI use it. I will open an issue there.

**Comment by xDae** [comment]
+1 i used to use recompose for my components, now my boss made me remove from everywhere 😥

**Comment by travi** [comment]
for those tracking this, the `material-ui` issue is here: https://github.com/callemall/material-ui/issues/6849

**Comment by aacotroneo** [comment]
Related: recompose/pure stopped working in the material-ui icons (that use that function) when you build react for production! It simply returns a bad wrapped object. 
Either compiling in dev mode or downgrading the version fixed my issue.

**Comment by aacotroneo** [comment]
https://github.com/acdlite/recompose/commit/a0a72bfcbc6988e70b0f3a60bb150a2a7fba8917#diff-a1e3850a92625b20984c44531204b27eR16  ?? I don't know the library.. but shouldn't wrap the component somehow?

**Comment by TrySound** [comment]
@aacotroneo which object?

**Comment by TrySound** [comment]
Damn, he is right, @istarkov. I skipped that. We need to call hoc with basecomponent, also we need to test production code.))

**Comment by reidblomquist** [comment]
Sorry I didn't provide more info in the initial report - was in react mode and had to slap version overrides into one of our packages that a few projects depend on, then respin a bunch of servers. Thanks for filling in the gaps everyone!

**Comment by istarkov** [comment]
0.23.4 pure fixed, please check

**Comment by miksansegundo** [comment]
@istarkov thanks. I will check asap.

**Comment by aacotroneo** [comment]
yay! my use case is working fine now!! (basically material ui icons with NODE_ENV='production'). Thanks!

**Comment by jeremyadavis** [comment]
Fixes my issue with material-ui icons as well.

**Comment by pbassut** [comment]
What about recompose-relay? Looks like it broke that too.

**Comment by istarkov** [comment]
Looks like broke or broke?

**Comment by pbassut** [comment]
Well, at least the latest published npm package is breaking because it's still using the createHelper function. And it's version requirements isn't strictly using 0.23.1

**Comment by istarkov** [comment]
You are right, thank you!

**Comment by jkettmann** [comment]
Is there any time to expect an update of the recompose-relay npm package? The newest one is 0.3.1 and still uses createHelper
