### ISSUE TITLE
Create a Recipes docs

### ISSUE THREAD

**Issue by andresmijares** [acdlite/recompose#385]
Hi,

I would love to submit a `recipes` md with a few solutions that I've found after refactoring a whole application with this library, there were a few escenarios that were had for me to understand at first, like updating one state property after another one updated. This also helped me to understand pure components and all the stuff that I was doing really bad.

I think a lot of people could update this doc with their own recipes as well.

I wonder if this is something that would be accepted as a `PR`?

**Comment by istarkov** [comment]
Here we have wiki you are free to add recepies there, no need in PR I think

**Comment by istarkov** [comment]
https://github.com/acdlite/recompose/wiki

**Comment by andresmijares** [comment]
nice thanks!
