### ISSUE TITLE
Propose `lookup` like HoC

### ISSUE THREAD

**Issue by MrRacoon** [acdlite/recompose#386]
A common pattern we use involves using a switch statement to conditionally render data based on some object property.

For Instance:

```
const Thing = (props) => {
    switch(props.type) {
        case 'image': return <ImageThing {...props} />;
        case 'video': return <VideoThing {...props} />;
        default: return null;
    }
}
```

I'd love to add the ability to simply do something along the lines of:

```
const Thing = lookup( // I don't have a great name for it yet
    prop('type'),   // some function to inspect an argument and return a key for the next map
    {
        'image': renderComponent(ImageThing)    // map of string to HOC
        'video': renderComponent(VideoThing)
    },
    renderComponent(DefaultThing) // some default case
)
```

My case was specific to inspecting an objects property, but the first argument to this new function can allow for more flexible lookups.

```
lookup(
  lookup: (props: Object) => string,
  hocMap: { string: HOC },
  default: ?HigherOrderComponent
): HigherOrderComponent
```

My goal was to keep the api as similar to `branch` as possible. so the optional arg, if not applied would likely just render the wrapped component.

If this sounds reasonable, I'd be happy to take a stab at it.

**Comment by istarkov** [comment]
In your example your switch is some kind of terminator - ie ends with `renderComponent` there will be more readable to use ordinary `branch` or use nothing and use language js `switch` inside `Component`.

If it's not terminator ie like `branch` usage 

```javascript
branch(
  testFn,
  compose(...enhacersList),
  compose(...enhacersList2)
)
```

Do you really have such pattern? If yes please describe it, IMO even branch without terminator is really rare, and in most cases it used like

```javascript
// v1 both branches are not terminators but second branch is just identity
branch(
  testFn,
  compose(...enhacersList),
)
// or
// v2 one of branches or both are terminators
branch(
  testFn,
  renderNothing, // or render Component // both terminators
 // render Component // terminator
)
```

So even branch not used with such pattern often, so do you really have a lot of code like

```javascript
lookup(
  lookupFn,
  {
    key1: compose(...enhancers1),
    key2: compose(...enhancers2),
    key3: compose(...enhancers3)
  }
)
```

 if not IMO it will be better to write switch statement directly in components.

**Comment by MrRacoon** [comment]
This is my team's first week with `recompose` so we don't have many of these patterns yet. We're kinda just going through and trying to replace as much code as possible.

This pattern I'm trying to pull out is one where we iterate through a "bag" of objects of different types, and expect to render them with different components, based on their properties.

The branch analogous would end up being along the lines of:

``` 
const Thing = branch(
    isImageType,
    renderComponent(ImageThing),
    branch(
        isVideoType,
        renderComponent(VideoThing),
        branch(
            isOtherType,
            renderComponent(OtherThing),
            renderNothing
        )
    )
)
```

In this example, I use `renderComponent` to directly translate our use case, but we're beginning to explore ways to wrap these components using your HOCs. 

I think I see what you mean about the terminators, though. Because, I'm not sure what I would pass to the resulting HOC....

It sounds like I have made an incorrect assumption about being able to use this library to minimize the current problem.

**Comment by istarkov** [comment]
IMO no need to create an abstraction if you don't need it ;-)

IMO js switch is good enough for such case, or if you don't want switch something like
```
const myComponent = (props) => ({
  image: <img src />
  blabla: <div>
}[prop(props)])
```

where is no need in recompose as nothing to compose here

**Comment by MrRacoon** [comment]
Fair enough! Thanks for the chat! We're loving the repo. Take care.

**Comment by janusch** [comment]
@istarkov I like your example! Just wondering what is `prop()` doing?
