### ISSUE TITLE
Are you up for new HoCs?

### ISSUE THREAD

**Issue by lucasconstantino** [acdlite/recompose#388]
Simply put: on every project I always end up creating new HoC which are mostly variations of the one's recompose provides, but with simpler usage to specific needs.

Are you guys open for pull requests on these HoCs? How have you decided you needed both `renameProp` and `renameProps`, but needed `withProps` and not `withProp`, for instance?

**Comment by istarkov** [comment]
We are open, but in most cases new HOCs are simple combination of existing or just small simplification of language constructs. We are also can think differently about whats needed and whats not. 
About withProp - having that you need to return a key and a value, the simplest case is to return object, so withProps :-)
IMO no decision were made, just for historical reasons, someone provided an accepted PR with new name.
I think that a lot of existing hocs not needed at all, like renameProp, flattenProp etc.

**Comment by lucasconstantino** [comment]
I see your point... I agree with you that recompose provides enough HOCs to build new ones on top. `omitProp`, for instance, is mentioned as a possibility but not available in the lib. It's just that a see recompose as I see ramda: I know most things can be build as combinations of others, but it is so much easier to rely on the lib having tools available for mostly every possible scenario. I would never use ramda if I had to recreate auxiliar methods, just for them been combinations of orther.

I close it here for your answer is very satisfactory, though I'm not very happy with it haha

P.s.: my implementation of `withProp`, just to mention, works like this: `withProp('myProp', props => myPropValue)`, meaning no object returning, making it very clean on the syntax. So does `mapProp`, which receives the prop name to be mapped against, and the mapping function.
