### ISSUE TITLE
withState and withHandlers must go in a specific order

### ISSUE THREAD

**Issue by jethrolarson** [acdlite/recompose#390]
I don't really know why this is true but I found if you do
```js
compose(withHandlers(...), withState(...))
```
instead of 
```js
compose(withState(...), withHandlers(...))
```

The state props inside of the handlers will be undefined. This was confusing me for quite a while.

This is especially confusing because I expect the composed functions to run right-to-left and I wouldn't expect that the handlers would need to get added prior to the state mixin for the props to be available.

**Comment by istarkov** [comment]
https://medium.com/@icelabaratory/why-recompose-uses-compose-19e6cb1430ac

**Comment by TrySound** [comment]
@jethrolarson Think of them like from top to bottom
```js
compose(
  withState(...),
  withHandlers(...)
)
```

**Comment by jethrolarson** [comment]
okay, so is this the same reason that lenses compose left-to-right?

**Comment by istarkov** [comment]
Just ordinary `compose` definition, having that we compose enhancers. Have no idea what lenses means. I'll close this as nothing to discuss here.
