### ISSUE TITLE
call handler from another?

### ISSUE THREAD

**Issue by code-by** [acdlite/recompose#392]
How to call handler from another?
something like this
```
  withHandlers({
    handlerOne: props => value =>
      console.log(value)
    handlerTwo: props => () => {
      handlerOne('Hello, World')
    },
```

**Comment by TrySound** [comment]
@code-by You can use two withHandlers. Props from prev with new handler will be passed to the next one.

**Comment by code-by** [comment]
if one run my example there will be error
Uncaught ReferenceError: handlerOne is not defined

**Comment by TrySound** [comment]
Call it from props. Of course there's nothing in the scope. It's just properties of the object. Not magic.

**Comment by istarkov** [comment]
I also created a PR https://github.com/acdlite/recompose/pull/401 not sure it will be merged

**Comment by istarkov** [comment]
I'll close this, if anyone want to proceed please write at #401
