### ISSUE TITLE
Using "compose" makes reduxForm not able to reinitialize

### ISSUE THREAD

**Issue by vuphuctho** [acdlite/recompose#394]
When `compose` is used, `enableReinitialize` will not be fired even when `initialValues` is updated
```
import { compose } from 'recompose'
import { connect } from 'react-redux'
import { reduxForm } from 'redux-form'

import { initialValues, getInitialValuesFromState } from './src'

mapStateToProps = state => ({
  initialValues: getInitialValuesFromState(state)
})

export default compose(
  reduxForm({
    form: 'sampleForm',
    initialValues,
    enableReinitialize: true
  }),
  connect(mapStateToProps)
)(Form)
```

Meanwhile, reinitialization works well with normal React component composition

```
export default connect(mapStateToProps)
  (reduxForm({
    form: 'sampleForm',
    initialValues,
    enableReinitialize: true
  })(Form))
```

**Comment by istarkov** [comment]
`connect...(reduxForm..)` is not the same as `compose(reduxForm.., connect...)`
you are using incorrect order in compose

**Comment by vuphuctho** [comment]
Thanks. Sorry for missing to check the order of components

**Comment by wuct** [comment]
I'm going to close this issue. Please feel free to re-open it if you have further questions.
