### ISSUE TITLE
Support for async loadable HOCs

### ISSUE THREAD

**Issue by jeescu** [acdlite/recompose#395]
It is also very helpful if you also provide loadable components as of Webpack 2 code splitting.
There are already packages out there but I think it's perfect if you also have this as one of your utilities.

**Comment by TrySound** [comment]
@jeescu Doing again what already works is not efficient. Reusing existing package can force as to publish to much major versions which will confuse users.
Better use something like this https://www.npmjs.com/package/react-loadable

**Comment by jeescu** [comment]
Thanks @TrySound for the link. That's a better package btw.

**Comment by wuct** [comment]
I'm going to close this issue. Please feel free to reopen it if you have further suggestions or questions.
