### ISSUE TITLE
[Question] "Mimic" Some Aspects of Relay

### ISSUE THREAD

**Issue by hnordt** [acdlite/recompose#4]
First of all thank you for open source this amazing library!

I've been using Flux for many projects (Alt, Redux, NuclearJS, Baobab).

I like Flux, but, at least for me, I don't think it's fun to write when project grows. The main reason is the boilerplate (it's just personal taste, I know that some people like boilerplate, also I know I can reduce boilerplate, anyway...).

I want to know if I can use Recompose to  "mimic" some aspects of Relay.

My idea is to add data fetching inside containers and pass it to the component with "withState".

For state that need to be shared across all components I'll create an AppContainer (` withState('usersOnline', 'getUsersOnline', [])`, ` withState('loggedUser', 'getLoggedUser', { isLoading: false, data: {}, error: null })`), then I'll create subcontainers, for example NotificationContainer (` withState('notifications', 'getNotifications', [])`).

Do you think I can proceed this way?

**Comment by hnordt** [comment]
Here is data fetching example I imagine:

```js
import React from 'react';
import ReactDOM from 'react-dom';
import { compose, withState, mapProps } from 'recompose';

const Counter = ({ counter, getCount }) => (
  <p>
    {counter.isLoading ? 'Loading...' : (counter.data ? `Count: ${counter.data}` : null)}
    <button onClick={getCount}>Get Count</button>
  </p>
);

// Simulate backend
let count = 0;
const getCount = callback => {
  count++;
  setTimeout(() => callback(count), 1000);
};

const CounterContainer = compose(
  withState('counter', 'updateCounter', {}),
  mapProps(({ updateCounter, ...rest }) => ({
    getCount: () => {
      updateCounter({ isLoading: true });

      getCount(count => updateCounter({ data: count }));
    },
    ...rest
  }))
)(Counter);

ReactDOM.render(<CounterContainer />, document.getElementById('root'));
```

**Comment by acdlite** [comment]
Usually when you connect a component to an external data source, you need to subscription that is disposed when the component unmounts. Check out the `lifecycle()` helper https://github.com/acdlite/recompose/blob/master/src/lifecycle.js

**Comment by hnordt** [comment]
@acdlite awesome.

So data fetching inside container components with Recompose is acceptable? I mean, it's scalable?

**Comment by acdlite** [comment]
I can't say for certain since I haven't tried it yet, but using `lifecycle` it shouldn't be any different than using `constructor()` and `componentWillUnmount()` directly, which is how data fetching in normal React classes usually works.
