### ISSUE TITLE
OnlyUpdateForKeys handle nested objects keys

### ISSUE THREAD

**Issue by jaredramirez** [acdlite/recompose#402]
This is less of a bug, and more of a feature request. Giving the following code:

```
// AuthContainer.js - generic, reusable redux container
const mapStateToProps = state => ({
  auth: state.auth, //isAuthenticated, isAuthenticating, authenticateError, username, email, profilePic
});
export default connect(mapStateToProps);

// Example.js
import {compose, onlyUpdateForKeys} from 'recompose';
import AuthContainer from './AuthContainer';

const enhance = compose(
  onlyUpdateForKeys(['auth.isAuthenticated']),
  AuthContainer,
);

const Example = enhance(({auth}) => (
  {auth.isAuthenticated && ? <Something /> : <Nothing />
));

export default Example;
```

This component will never update, because the key provided don't directly match the prop name.

If you are using reusable redux containers(like this example), the `mapOnlyForKeys` function is a savior, because you want the reusable containers to provide enough props for many different components but reduce unnecessary re-renders.

I think something along the lines of lodash's get function would be great in this instance, so you can pass in more complex objects, and specific which of those children that you want to watch for.

Thoughts on this?

**Comment by istarkov** [comment]
Based on my experience of team work, any HOC other than `pure` which used `shouldComponentUpdate` is a future bug. 
It's sometimes hard to get that somewhere in the chain something prevents rendering.
So my thoughts is to remove `onlyUpdateForKeys` at all from the recompose.
Yes I understand that it can be useful for some rare cases, 
but IMO it promotes bad optimization pattern.
