### ISSUE TITLE
[branch]: async test function?

### ISSUE THREAD

**Issue by joncursi** [acdlite/recompose#406]
This works as expected:

```js
  branch(
    () => {
      return false;
    },
    withQuery,
    undefined,
  ),
```

This does not:

```js
  branch(
    async () => {
      const id = await userId();
      if (id) {
        return true;
      }
      return false;
    },
    withQuery,
    undefined,
  ),
```

I noticed that when using an `async` test function, branch always uses the left HOC (defaults to true) even if the condition comes back asynchronously as `false`. Is there a way we can re-write this to make branch accept an async test function?

**Comment by istarkov** [comment]
> Is there a way we can re-write this to make branch accept an async test function?

I don't think so. Just think about what is test function in branch - it's a function of props, and test is called every time parent props were updated.

So now let's assume that now `test` is a function returning Promise,
so on every render we need to resolve Promise, get value, and render something based on that value. 
But what we should render until Promise resolved? Do you really need a blinking Component, with unknown behaviour, which visual state depends not on data but on parent rendering behaviour, on Promise side-effects and all that fun async issues having that at the moment you can have multiple unresolved Promises. There are other issues exists this is just what is immediately visible.

**Comment by istarkov** [comment]
Also if you need some kind of data fetching enhancers,
there are a lot of available, just use them composing with branch etc.

https://github.com/brillout/awesome-react-components#props-from-server
