### ISSUE TITLE
withPropertyHandlers proposal

### ISSUE THREAD

**Issue by garretttaco** [acdlite/recompose#409]
[Here is the proposal for the withPropertyHandlers HoC.](https://gist.github.com/garretttaco/7cb6fedb6008512be2a1a5af52dc721e) 

Given the following scenario, I would like to see if anyone else has come across this pattern and if this, `withPropertyHandlers` HoC, would be a good addition to the library.
Le's say we have an object that is a representation of a record in the database. The database has 5 columns that a user can edit in a form. First, we clone the object into the local state of the component on mount. We render the items into a form with controlled inputs and allow the user to update the values. There are a few ways handle updates from the inputs to the state/store/server? Since we are updating the one object and the syntax is pretty much the same, we can use one method to update the state. However, the property is different. So how do we let the method know what the property name is to match the value?
We can:
A) **Use currying and inline call the name, in the render method, to the curry method.**
```
reusableHoC = name => value => {
  this.setState({ [name]: value })
}
...
render() {
...
<input name="uniqProperyName" onChange={reusableHoC('uniqProperyName')}
```
B) **Use currying and declare all the propertyMethodUpdaters in the class body to be then called onChange of the input.**
```reusableHoC = name => value => {
  this.setState({ [name]: value })
}
updateUniqPropertyName = reusableHoC('uniqProperyName')
...
render() {
...
<input name="uniqProperyName" onChange={updateUniqPropertyName} />
```
C) **Create a different method for each input because screw functional programming.**
```
// Not reusable
updateUniqPropertyName = value => {
  this.setState({ uniqProperyName: value })
}
...
render() {
...
<input name="uniqProperyName" onChange={updateUniqPropertyName} />
```

From my experience, option B is the best solution. The methods are only ever declared once per class instantiation and this allows for DRY code.

However, in recompose, this is really tedious to implement. We have to define the curry function in a `withHandlers` HoC and then all the other methods in another `withHandlers` HoC. Then we have to destructure all the methods into the presentational component to pass them to the inputs.
Let's take a look at what I mean.

```
const enhance = compose(
  withHandlers({
    updater: ({ databaseObj, updateDatabaseObjState }) => name => value => {
      updateDatabaseObjState({
        ...databaseObj,
        [name]: value,
      })
    },
  }),
  withHandlers({
    updateValue1: ({ updater }) => updater('value1'),
    updateValue2: ({ updater }) => updater('value2'),
    updateValue3: ({ updater }) => updater('value3'),
    updateValue4: ({ updater }) => updater('value4'),
    updateValue5: ({ updater }) => updater('value5'),
  }),
)

const Component = enhance(({
  updateValue1,
  updateValue2,
  updateValue3,
  updateValue4,
  updateValue5,
}) => null)
```
Now how would this save us with the proposed HoC, `withPropertyHandlers`? Well, we would not have to declare all the handlers in the second withHandlers HoC. We would just let our new HoC do that for us. Let's see what it would look like the new way.

```
const enhance = withPropertyHandlers(
  [value1, value2, value3, value4, value5],
  'updater',
   ({ databaseObj, updateDatabaseObjState }) => name => value => {
      updateDatabaseObjState({
        ...databaseObj,
	[name]: value,
      })
   },
)
const Component = enhance(({
  updateValue1,
  updateValue2,
  updateValue3,
  updateValue4,
  updateValue5,
}) => null)

```
We have quite a bit of flexibility with this function since we declare the main updater function and pass it in as one of the arguments. We also pass in properties in an array and the name for the updater prop. There is also a possible last parameter to allow the developer to change the name of the prefix, which defaults to `update`
I have been using this recently and has been noticeably improving development for me personally.

I would love to hear peoples thoughts on this idea and if it seems useful.

**Comment by istarkov** [comment]
I read 2 times but havent got the idea and how its different from withState + withHandlers Hocs combination?

**Comment by istarkov** [comment]
Simple reduce inside withHandlers will do the same

**Comment by garretttaco** [comment]
I realize that a simple `reduce` in a `withHandlers` will do the same. That's how it's implemented under the hood. You can see that in the gist that I provided. The idea is that I don't want to have to write that logic every time I want to do this. For me, I do this often enough that It would be useful to have a utility HoC. I really wanted to get a feeler if anyone else would too. I mean, we have HoC for get/set/wrap displayName. You can easily implement those too, but for the sack of making it even easier, it's a part of Recompose.

**Comment by istarkov** [comment]
I'll close this.
Additional reason to not implement this HOC as now as we support flow type system this kind of HOCs can't get a good type definition and I dont want to extend [this section](https://github.com/acdlite/recompose/tree/master/types#part-2---other-hocs)
