### ISSUE TITLE
Multiple calls to defaultProps merges them into a single object?

### ISSUE THREAD

**Issue by smber1** [acdlite/recompose#413]
Hi,
Looking at the source for defaultProps, it looks to overwrite defaultProps for every invocation. For my app I've been separating concerns for a single HoC out into separate files. Each file, e.g. withFeatureX, has the appropriate withState, withPropsOnChange, withHandlers etc.  Was hoping to also put the specific defaultProps per file as well and have them all merge together.  It's easy enough to achieve outside of Recompose, just wondered if it's something you've considered?

**Comment by istarkov** [comment]
I havent got the question. Recompose does not overwrite defaultProps of existing component. It creates a new one as a HOC and adds default props to it. Its expected.
