### ISSUE TITLE
How to change a prop on child element?

### ISSUE THREAD

**Issue by RomainGoncalves** [acdlite/recompose#425]
Hi,

I discovered this library yesterday and I already love it. Now, I've got a little problem, I'm sure it's just me not understanding the flow but...

I have an element, on which I use branch in order to do a check. If I have `true`, I need to display a modal, otherwise I display my component as intended. That part works.

Now when I have the modal opened, I have 2 choices, first to be redirected to another page (that works), second is to continue back to my element that was not shown in the first place.

Here's what I have so far on the parent component:

```
// Using compose to check if the user has enough credit limit remaining
const enhance = compose(
  connect(state => ({
    user: getUser(state), // First getting the user from state
    proceed: true,
  })),
  branch(
    props => props.user.remainingCreditLimit < props.invoice.amount || !props.proceed,
    // If above condition is true, then display the modal
    renderComponent(
      compose(
        withProps(() => ({
          pathToIncreaseCL: router.userIncreaseCreditLimitPath(),
        }))
      )(Modal)
    )
  )
);

// connectedForm is above, a simple connect() call
export default enhance(connectedForm);
```

Now in my Modal component, I do see `pathToIncreaseCL` but what I want to do is to modify `proceed` so that I can go on with my workflow. And I can't find how to get that value change to reflect on the parent component.

Thanks for any help

**Comment by timkindberg** [comment]
maybe use `withStateHandlers` above `branch`?

```js
const enhance = compose(
  connect(state => ({
    user: getUser(state)
  })),
  withStateHandlers(
    { proceed = true },
    { 
      doProceed: () => () => ({ proceed: true }),
      doNotProceed: () => () => ({ proceed: false })
    }
  ),
  branch(
    props => props.user.remainingCreditLimit < props.invoice.amount || !props.proceed,
    // If above condition is true, then display the modal
    renderComponent(
      compose(
        withProps(() => ({
          pathToIncreaseCL: router.userIncreaseCreditLimitPath(),
        }))
      )(Modal)
    )
  )
);
```

Now Modal should receive the `doProceed` handler that you can call.

**Comment by RomainGoncalves** [comment]
Awesome @timkindberg ! That worked perfectly. Had a little scare, as I was on release `0.23.5` and somehow it didn't have `withStateHandlers`, but then I switched to `0.24.0` and got it working.

Thanks again.

**Comment by istarkov** [comment]
My fault I've merged `withStateHandlers` but decided not to publish it, so it was in docs but not at lib itself.
