### ISSUE TITLE
Help converting to recompose withState?

### ISSUE THREAD

**Issue by GollyJer** [acdlite/recompose#427]
I've moved pretty much everything in my codebase over to recompose and it's helped immensely with code organization.

I'm not sure how to approach this one though. 
```
class TrackYPosition extends React.Component {
  constructor() {
    super();
    this.state = {
      scrollPositionY: new Animated.Value(0),
    };
    this.scrollEventY = Animated.event(
      [{ nativeEvent: { contentOffset: { y: this.state.scrollPositionY } } }],
      { useNativeDriver: true },
    );
  }

  render() {
    return (
      <Animated.ScrollView
        onScroll={this.scrollEventY}
        scrollEventThrottle={1}
      >
        <View>
          {console.log(this.state.scrollPositionY)}
        </View>
      </Animated.ScrollView>
    );
  }
}
```
Thanks for any help you can provide!

**Comment by timkindberg** [comment]
Maybe something like this?

```js
const enhance = withStateHandlers(
  { scrollPositionY: new Animated.Value(0) },
  {
    scrollEventY: ({ scrollPositionY }) => Animated.event(
      [{ nativeEvent: { contentOffset: { y: scrollPositionY } } }],
      { useNativeDriver: true },
    )
  }
);

const TrackYPosition = enhance(({ scrollEventY, scrollPositionY }) =>
      <Animated.ScrollView
        onScroll={scrollEventY}
        scrollEventThrottle={1}
      >
        <View>
          {console.log(scrollPositionY)}
        </View>
      </Animated.ScrollView>
);

```

**Comment by GollyJer** [comment]
Thanks @timkindberg.
I didn't even know that function existed.  :-)

P.S. - I paid for a month of egghead.io just to get your recompose class.  It was super helpful.  Thanks!!

**Comment by timkindberg** [comment]
@GollyJer You're welcome, and wow thanks for the views!

**Comment by timkindberg** [comment]
@GollyJer if that solves the issue can you pls close?

**Comment by GollyJer** [comment]
Hi @timkindberg, 
I got around to trying this out today but am running into an error I don't know how to troubleshoot.  Thought I'd see if you have an idea. Thanks!
![84e2bb81-67a1-4f69-ac00-5e95631a932b](https://user-images.githubusercontent.com/689204/28277439-f956d800-6ae7-11e7-9fc1-c494099744d4.PNG)

**Comment by PemL** [comment]
@GollyJer 
The function is pretty new. I suspect you have an older version of the recompose library. Update to the latest one and try again

**Comment by GollyJer** [comment]
@PemL 
I upgraded to .24 before posting. 🙁 
I feel like I might have the syntax wrong. Is Tim's sample code correct?

**Comment by PemL** [comment]
@GollyJer 

Try

`const enhance = withStateHandlers(
  { scrollPositionY: new Animated.Value(0) },
  {
    scrollEventY: ({ scrollPositionY }) => () => Animated.event(
      [{ nativeEvent: { contentOffset: { y: scrollPositionY } } }],
      { useNativeDriver: true },
    )
  }
);
`

**Comment by GollyJer** [comment]
@PemL 
Thanks for the help.  That doesn't thrown an error but scrollPositionY never updates.
Looks like I'll have to keep this one a `class component` for now.

**Comment by GollyJer** [comment]
@istarkov 
Sorry to bother you. I was looking at the `withStateHandlers` code you checked in hopes of understanding this issue but with no luck.

Do you have any thoughts on why this isn't working?

Thanks!

**Comment by istarkov** [comment]
@GollyJer I have no idea what you want to achieve, I see no description of `Animated.event` at animated library, at how it works.
If you clear the code from than I could help.

**Comment by joedski** [comment]
Shot in the dark, but looking at Animated's docs, maybe this 'll work?

```js
compose(
  withState(
    'interaction',
    'setInteraction',
    // Props get passed in here, but we're ignoring them.
    () => {
      const interaction = {
        scrollPositionY: new Animated.Value(0),
      };
      
      interaction.scrollEventY = Animated.event(
        [{ nativeEvent: { contentOffset: { y: interaction.scrollPositionY } } }],
        { useNativeDriver: true },
      );

      return interaction;
    },
  )
)((props) => (
  <Animated.ScrollView
    onScroll={props.interaction.scrollEventY}
    scrollEventThrottle={1}
  >
    <View>
      {console.log(props.interaction.scrollPositionY)}
    </View>
  </Animated.ScrollView>
));
```

**Comment by GollyJer** [comment]
@joedski 
This works perfectly! THANK YOU!!
