### ISSUE TITLE
withState - bulking state updates

### ISSUE THREAD

**Issue by orenklein** [acdlite/recompose#433]
How would you bulk state updates into one update? 
Using 'showData' of the following example will cause 2 renders (as far as I see it - without recompose I'd use this.setState)
```
compose(
    withState('enabled', 'setEnabled',false),
    withState('data','setData',null),
    withHandlers({
        showData:({setEnabled, setData})=>()=>{
            setEnabled(true);
            setData([1,2,3]);
        }
    })
)
```

**Comment by istarkov** [comment]
use withStateHandlers instead of 3 hocs.

**Comment by wuct** [comment]
So the code above can be written as:

```js
withStateHandlers({
  enable: false,
  data: null,
}, {
  showData: () => () => ({
    enabled: true,
    setData: [1, 2, 3]
  })
})
```

The doc is [here](https://github.com/acdlite/recompose/blob/master/docs/API.md#withstatehandlers). I'm going to close this issue and please feel free to reopen it if you have further questions.
