### ISSUE TITLE
withStateHandlers will not result the expected behavior

### ISSUE THREAD

**Issue by incoqnito** [acdlite/recompose#435]
Hello,

i have a Loader Component and i am exporting an hoc for loading state as well. In my first version it looks so:

```
export const withLoadingState = withState('isLoading', 'showLoadingIndicator', false)
```

that worked as expected. But i want explicit define the function for updating the state, so i turned the withState into withStateHelpers

```
export const withLoadingState = withStateHandlers({
  isLoading: false
}, {
  showLoadingIndicator: (state) => (value) => ({ isLoading: value })
})
```
The result is not the same, my state is not updating. Someone has an idea?

My recompose version is: 0.24.0

**Comment by istarkov** [comment]
You need to provide an example, as like in your case
https://jsfiddle.net/41yz1hng/3/
All is fine

**Comment by incoqnito** [comment]
Okay now i figured out, what is missing, i execute code in a successCallback, but the callback will not be invoked 

https://jsfiddle.net/1sh3o04q/

how can i use the success callback with withStateHandlers?

**Comment by istarkov** [comment]
what the usecase for that callback? I wrote enormous amount of code on React and never feel that I need it.
There is no way to use it with withStateHandlers

**Comment by incoqnito** [comment]
```
const computeComponentWillMount = componentWillMount((props) => {
  props.showLoadingIndicator(true, () => {
    props.fetchECRs().then(() => props.showLoadingIndicator(false))
  })
})
```
fetching dats in component

**Comment by istarkov** [comment]
Having that functional `setState` in react is atomic and ordered (non functional is also ordered) i.e

```
setState(() => ({ loading: true }));
blaBlaAsync(..., function callback() {
  setState(() => ({ loading: false }));
}); 
```
in all cases second `setState` will be after the first so no need to place it into callback.

Also no reason to call data fetch after the state has change in this case.

**Comment by istarkov** [comment]
Also as I know it's some kind of undefined behaviour to call parent state change inside cwu method,
see https://github.com/facebook/react/issues/7671
> Callbacks from componentWillMount that update parent components with a setState is completely unsupported and lead to strange and order dependent race conditions. We already know that we want to deprecate that pattern.
So it's better not to use recompose for this HOC

**Comment by cdomigan** [comment]
Calling a callback after setState() is a common and helpful React pattern, I'm confused why withStateHandlers doesn't support it?

Eg. I want to update a searchString state item, and then trigger a async load using that new state.

```
withStateHandlers({
    searchString: ''
}, {
    setSearchString: (state) => (newString) => ({searchString: newString})
}),
withHandlers({
    onSearchChange: ({setSearchString, load}) => (newString) => setSearchString(newString, load)
})
```
