### ISSUE TITLE
How to type custom HOCs that are used alongside recompose HOCs?

### ISSUE THREAD

**Issue by tanem** [acdlite/recompose#439]
If this question should be posted somewhere else let me know, last thing I want to do is pile up your issue tracker unnecessarily 😉 ...

We're using recompose + flow in a fairly large React app, and I've been utilising the flow examples in this repo, but I just wanted to double check how to set up custom HOCs so they played nicely with the recompose HOCs in terms of type checking?

Example:

```js
type Props = {
  str: string,
  mult: number
};

const Thing = ({str, num}) => <div>{str}{' '}{num}</div>;

const addProp = (BaseComponent) => ({mult, ...rest}) =>
  <BaseComponent {...rest} num={props.mult * 2} />;

const enhancedThing: HOC<*, Props> = compose(
  setDisplayName('Thing'),
  addProp
);

const Enhanced = enhancedThing(Thing);

ReactDOM.render(<Enhanced str="w" mult={3} />, document.getElementById('app'));
```

Questions:

1. How should `addProp` be typed?
2. Is it possible to type it in such a way that the `mult` prop is checked without having to lift it up into the `Props` type definition, like it is in the example?

**Comment by istarkov** [comment]
1) There is no need in types in your example:
type inference will work.
See gif below:
![addp](https://user-images.githubusercontent.com/5077042/28504124-19da1970-701a-11e7-810b-361eb29a1f56.gif)

2) You need to provide or base or enhanced component types to make all work, 
having that mult is a property of Enhanced component you need to define it in Props.
Here Props is some kind of your component public interface.

**Comment by istarkov** [comment]
BTW I'm not experienced flow dev, may be wrong etc.

**Comment by tanem** [comment]
Thanks heaps @istarkov 👍 That should be enough for me to move ahead with things anyway, if you were wanting to close the issue.

**Comment by tanem** [comment]
I'll close it now actually 😉
