### ISSUE TITLE
Type checking an enhancer that uses branch

### ISSUE THREAD

**Issue by tanem** [acdlite/recompose#441]
I'm trying to figure out how to sanely type an enhancer that uses `branch`. Example:

```js
// @flow

import React from 'react';
import ReactDOM from 'react-dom';
import {branch, compose, renderComponent, setDisplayName} from 'recompose';

import type {HOC} from 'recompose';

// --- button

type ButtonProps = {
  children?: React$Element<any>,
  onClick: () => mixed
};

const Button = ({children, onClick}: ButtonProps) =>
  <button onClick={onClick}>{children}</button>;

// --- anchor

type AnchorProps = {
  children?: React$Element<any>,
  url: string
};

const Anchor = ({children, url}: AnchorProps) =>
  <a href={url} target="_blank">{children}</a>;

// --- enhance

type EnhanceProps = {
  children?: React$Element<any>,
  // ?
  // url
  // onClick?
};

const enhance: HOC<*, EnhanceProps> = compose(
  setDisplayName('Button'),
  branch(
    ({url}) => Boolean(url),
    renderComponent(Anchor)
  )
);

const Enhanced = enhance(Button);

ReactDOM.render(
  // <Enhanced url="a url"}>anchor</Enhanced>,
  <Enhanced onClick={() => {}}>button</Enhanced>,
  document.getElementById('root')
);
```

So `Enhanced` renders as an `Anchor` if `url` is passed, otherwise it renders as a `Button`.

Setting up `EnhancedProps` with optional `url` and `onClick` won't work, one example where it doesn't is that you could then create a `Button` without an `onClick` and get no flow errors.

I'm getting the feeling that I should refactor this somehow, but I thought I'd ask here as I'm not sure if this is going to mean getting bitten again in future (we've used `branch` a fair bit, and are in the process of moving from `PropTypes` -> flow)?

**Comment by istarkov** [comment]
https://github.com/acdlite/recompose/blob/master/types/flow-typed/recompose_v0.24.x-/flow_v0.49.x-/recompose_v0.24.x-.js#L213

**Comment by istarkov** [comment]
btw in your case try to type EnhancedProps as like as
`type EP = type1 | type2`

**Comment by istarkov** [comment]
where type1 and type2 are exact types like ` {|url: string|}`

**Comment by tanem** [comment]
Thanks again @istarkov.

> btw in your case try to type EnhancedProps as like as
type EP = type1 | type2

> where type1 and type2 are exact types like {|url: string|}

Oh yea of course, awesome, cheers :clinking_glasses: 

> https://github.com/acdlite/recompose/blob/master/types/flow-typed/recompose_v0.24.x-/flow_v0.49.x-/recompose_v0.24.x-.js#L213

Ah right, so given your advice above, I could still use branch for this, but I'd need to do a refinement in the `test` function, and then also in the `left` function?

At this point I'm thinking that it's probably easier to do the refinement in my own `branch`-like function. Something like the following?

```js
// @flow

import React from 'react';
import ReactDOM from 'react-dom';
import {compose, setDisplayName, createEagerFactory} from 'recompose';

import type {Component, HOC} from 'recompose';

// button

type ButtonProps = {|
  children?: React$Element<any>,
  onClick: () => mixed
|};

const Button = ({ children, onClick }: ButtonProps) =>
  <button onClick={onClick}>{children}</button>;

// anchor

type AnchorProps = {|
  children?: React$Element<any>,
  url: string
|};

const Anchor = ({ children, url }: AnchorProps) =>
  <a href={url} target="_blank">{children}</a>;

// branch-like

const renderAnchor = <B, E: *>(BaseComponent: Component<B>): Component<E> =>
  (props) =>
    props.url
      ? createEagerFactory(Anchor)(props)
      : createEagerFactory(BaseComponent)(props);

// enhancer

type EP =
  | ButtonProps
  | AnchorProps;

const enhance: HOC<*, EP> = compose(
  setDisplayName('Button'),
  renderAnchor
);

const Enhanced = enhance(Button);

ReactDOM.render(
  // <Enhanced url="some url">anchor</Enhanced>,
  <Enhanced onClick={() => {}}>button</Enhanced>,
  document.getElementById('root')
);
```

PS does that `renderAnchor` type def look right/necessary to you? I just wanted to let flow infer the enhanced props coming through. I had to hack the type defs to export the `Component` type 🤔 

```js
const renderAnchor = <B, E: *>(BaseComponent: Component<B>): Component<E> ...
```

**Comment by istarkov** [comment]
Seems like it's my fault to not export `Component` type, 
I haven't used this `typedefs` widely in my projects as I'm on vacation now ;-) so you are some kind of pioneer in this theme.
IMO the problem of `renderAnchor` is that it will call create factory on every render, where is no need in this just use `jsx`.

Also I think that recompose here isn't needed ;-), putting all the logic inside BaseComponent render you will automatically get type refinement as you will need to explicitly write something like 
`const myButtonOrUrl = (props: EP) => props.url ? renderLink(props.url) : renderButton(props.onClick)` 
And this will be easier to read.

**Comment by tanem** [comment]
Agree with those points you made, cheers for the heads up about the factory :+1:

To provide some context, this example is a very simplified piece of a part of our component library. We have a number of different buttons, and only some of them can render as anchors, plus some of them can render with icons, and they're all styled differently.

We actually started in a similar fashion to your suggestion, with a single component rendering button or anchor, rendering with or without icon... but that component got quite complex, hence we started using recompose to split things up and reuse logic across the various buttons.

So recompose seems like a good fit but yep, sometimes can be a tendency to try and jam all the things into the API 😆 

Will see how I go with all the info from this issue when I'm back working on the app tomorrow. If it works out ok I'll close the issue, thanks again.

**Comment by tanem** [comment]
I reckon we can close this for now, things are progressing pretty well in the app I'm working on 👍

**Comment by istarkov** [comment]
It would be cool if you share your opinion about tips and tricks later.

**Comment by ardok** [comment]
Anyone face this kind of error with flowtype?
```
Cannot call compose with compose intermediate value bound to a because property children is missing in Props [1] but
exists in object type [2] in the first argument.
```

I'm doing something similar like @tanem :
```
branch(
({ isLoading }) => isLoading[rpcIds.phase4GetTabularData],
renderComponent(CenteredPreloader)
),

const CenteredPreloader = ({ children, ...preloaderProps }: { children?: React$Node }) => (
```

But I got that error.
His `Anchor` component is basically the same like my `CenteredPreloader`
