### ISSUE TITLE
should `isReferentiallyTransparentFunctionComponent` be completely off for non-production env?

### ISSUE THREAD

**Issue by deepsweet** [acdlite/recompose#442]
Hi.

Right now

```js
(process.env.NODE_ENV === 'production' || !Component.propTypes)
```

from [here](https://github.com/acdlite/recompose/blob/master/src/packages/recompose/isReferentiallyTransparentFunctionComponent.js) leads to lack of actual element while testing with Enzyme (`NODE_ENV=test`) so very dummy stateless components can't be found in a tree. Same problem with react-dev-tools (`NODE_ENV=development`), I can't see the component because function was directly invoked with props.

I understand the purpose of `createEagerFactory`, and the idea is really nice, but in my opinion it should be production only optimization. Should we consider removing `|| !Component.propTypes` part from the condition or something like this? It's really confusing and took a lot of time to find the reason.

**Comment by istarkov** [comment]
The same confusion as [here](https://github.com/acdlite/recompose/issues/407) let us think a little, 
seems like you are right

**Comment by deepsweet** [comment]
Also it sounds like a breaking change because it might break many tests based on children count or (which is more likely) Jest snapshots.

>The only problem I see is small perf degrade at dev mode.

One can't expect much performance from React in dev mode, all of these warning, PropTypes, setter guards, [and so on](https://github.com/thejameskyle/babel-react-optimize) :) As for me it's totally fine.

**Comment by deepsweet** [comment]
Guys, sorry for pushing, but is there any conclusion? Plans for the next major version?

**Comment by istarkov** [comment]
I remember about this, just took a few weeks break with any computer work. Now Im in deep Russia with mobile phone only ;-)

**Comment by istarkov** [comment]
You can provide a PR with 90% probability we will accept it

**Comment by wuct** [comment]
Sorry for late reply and yes, a PR is welcome. This change probably can land at 0.25.
