### ISSUE TITLE
withStateHandlers and Promise

### ISSUE THREAD

**Issue by RomainGoncalves** [acdlite/recompose#443]
Hi,

what would be the reason for `fetchCustomers` to return undefined?

```javascript
const enhanced = compose(
   withStateHandlers(
     { page: 1, newCustomers: [] },
     {
       changePage: ({ page }) => () => ({ page: page + 1 }),
       fetchCustomers: ({ page }) => () => backendApi.getCustomers(1, page, 10)
           .then(response => response.customers),
     }
   ))(CustomerSelectInput);
```

I also tried this, but `newCustomers remains empty`:
```javascript
const enhanced = compose(
   withStateHandlers(
     { page: 1, newCustomers: [] },
     {
       changePage: ({ page }) => () => ({ page: page + 1 }),
       fetchCustomers: ({ page }) => () => backendApi.getCustomers(1, page, 10)
           .then(response => ({ newCustomers: response.customers })),
     }
   ))(CustomerSelectInput);
```
The actual call works properly, I see in the Network tab that the data is returned as expected.

Thanks for any help

**Comment by istarkov** [comment]
[here](https://github.com/acdlite/recompose/blob/master/docs/API.md#withstatehandlers)
> Every state updater function accepts state, props and payload and must return a new state or undefined.

You are returning a promise, not a state object. 
To make more clear - it is just a wrapper over the functional form of `setState` React method, which does not accept promises as a return.

**Comment by RomainGoncalves** [comment]
Hi,

thanks for your reply.

So, I can't do my fetch there?... hmm Which other method could I use in order to achieve this?
withPropsOnChange?

**Comment by istarkov** [comment]
No. 
The only good enhancer in `recompose` which you can use for calls with side-effects is
a [mapPropsStream|mapPropsStreamWithConfig](https://github.com/acdlite/recompose/blob/master/docs/API.md#mappropsstream)
[Some examples](https://github.com/acdlite/recompose/issues/304)

Or implement a simple enhancer by yourself - google something like `react fetch componentDidMount`.

Or the best solution is to use available open source enhancers which like [link](https://github.com/brillout/awesome-react-components#props-from-server)

**Comment by RomainGoncalves** [comment]
Thanks for your help. I went the simple road and use a `Component`... Better luck next time :D
