### ISSUE TITLE
Override lifecycle display name?

### ISSUE THREAD

**Issue by mnpenner** [acdlite/recompose#448]
It would be nice to be able to override the display name [set by `lifecycle`](https://github.com/acdlite/recompose/blob/7f6169bba911e32086745333f89221b3842cc69f/src/packages/recompose/lifecycle.js#L29).

I'm using lifecycle to build an ajax loader HOC (akin to react-apollo's `graphql` HOC), and it would be nice if React devtools showed `ajaxLoader(...)` instead of `lifecycle(...)` everywhere.

Maybe add `spec.displayName` as an option?

**Comment by istarkov** [comment]
The problem here is what to do with other enhancers? Why we prefer lifecycle over the others?
Also providing additional arguments just to support some helper utility does not looking good for me. 
IMO if its really needed just write your own enhancer and give it a name.

**Comment by mnpenner** [comment]
Not sure. The other enhancers seem simpler -- haven't wanted to name them yet. But I see your point. I guess we can close this.
