### ISSUE TITLE
Branch, Router and updating

### ISSUE THREAD

**Issue by RomainGoncalves** [acdlite/recompose#453]
Hey there,

quick question. I have this component:

```javascript
import { connect } from 'react-redux';
import { compose, branch, renderComponent } from 'recompose';

const Sorting = (sellerRouter, investorRouter) =>
compose(
  connect(
    () => ({
      user: { isSeller: () => true },
    }),
  ),
  branch(
    props => props.user.isSeller(),
    renderComponent(sellerRouter),
    renderComponent(investorRouter),
  ),
)();

export default Sorting;
```

It works fine in doing the sorting. Now my routers have a little problem. On first load, they display the proper route. But when I try to click a move to another route, nothing happens. I've tested the router without using the Sorting and they work properly.

Am I missing something? Or is it because the `lifecycles` are not available?

Thanks in advance

**Comment by istarkov** [comment]
I reread 3 times. What I understand? Nothing.
What lifecycles what routes where you click?

**Comment by RomainGoncalves** [comment]
OK sorry.

So I'm using React-Router to setup my routing. The router to use is decided by the component I showed above.
And for example the `sellerRouter` looks like this:

```javascript
import React from 'react';

import SubRoutes from './sub_routes';

import Dashboard from '../../views/dashboard';
import Customers from '../../views/customers';

const sellerRoutes = [
  {
    path: '/',
    exact: true,
    component: Dashboard,
  },
  {
    path: '/customers',
    component: Customers,
  },
];

const SellerRoutes = () => (
  <SubRoutes routes={sellerRoutes} />
);

export default SellerRoutes;
```

And `SubRoutes`, taken directly from React Router's docs:

```javascript
import React from 'react';
import PropTypes from 'prop-types';
import { Route } from 'react-router-dom';

// wrap <Route> and use this everywhere instead, then when
// sub routes are added to any route it'll work
const RouteWithSubRoutes = (route) => (
  <Route
    path={route.path}
    exact={route.exact}
    render={props => (
    // pass the sub-routes down to keep nesting
      <route.component {...props} routes={route.routes} />
  )}
  />
);

const SubRoutes = ({ routes }) => (
  <div>
    {
      routes.map(route => (
        <RouteWithSubRoutes key={route.path} {...route} />
      ))
    }
  </div>
);

SubRoutes.propTypes = {
  routes: PropTypes.array.isRequired,
};

export default SubRoutes;
```

Now I also have a navigation, using `<Link... >` components, that contain the proper links to my routes.

With my current setup, when I click on a `<Link>` the Router doesn't respond. However if I refresh, the proper component displays.

Hope that's enough explaination :)

**Comment by istarkov** [comment]
It become more fun :-) sorting from first comment is lost in the second. I think you need to provide a full example using jsbin or similar, so someone can help.

**Comment by Panoplos** [comment]
`<route.component {...props} routes={route.routes} />` does this even work? I thought React required a capitalised component name...

**Comment by wuct** [comment]
@Panoplos It's actually work. [Here is how it's compiled to js code](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact&targets=&browsers=&builtIns=false&debug=false&code_lz=DwJw9grgLgpgdAYzAWwA5gHYw1ABAegD4g).
