### ISSUE TITLE
feat: add pure variant of `toClass`

### ISSUE THREAD

**Issue by AndersDJohnson** [acdlite/recompose#455]
Feature request to add a pure variant of `toClass` that extends [`React.PureComponent`](https://facebook.github.io/react/docs/react-api.html#react.purecomponent) instead of just [`React.Component`](https://facebook.github.io/react/docs/react-api.html#react.component) - either as an optional argument to `toClass` or a separate method, e.g., `toPureClass`.

**Comment by GollyJer** [comment]
@AndersDJohnson I think you can compose in the [pure HOC](https://github.com/acdlite/recompose/blob/master/docs/API.md#pure
) to get the desired affect.

**Comment by AndersDJohnson** [comment]
@GollyJer True, though it wouldn't use the native `React.PureComponent` which might be slightly preferable to `pure` if only to reduce bundle size, assuming the behavior is identical.

**Comment by istarkov** [comment]
What is the usecase for toClass? Just to allow refs and tests.
It some kind of hack enhancer, and very rarely used.

**Comment by AndersDJohnson** [comment]
See https://github.com/acdlite/recompose/issues/251 for discussion of using native `PureComponent`.
