### ISSUE TITLE
Suggestion: HOC factory

### ISSUE THREAD

**Issue by sbking** [acdlite/recompose#468]
It would be nice if there were a function that would allow the creation of HOCs based on props within a `compose` pipeline. For example, I have something like this in one piece of code:

    branch(
      ({ theme }) => theme.globalStyles,
      compose(
        BaseComponent => props => {
          const WrappedComponent = withStyles(props.theme.globalStyles)(BaseComponent)
          return <WrappedComponent {...props} />
        },
        omitProps('classes')
      )
    )

The idea is that the `withStyles` HOC from Material UI requires a stylesheet object, but in this case, I want to get the stylesheet out of the props being passed down throughout a pipeline of recompose HOCs. It would be great if recompose included a function that would allow something like:

    branch(
      ({ theme }) => theme.global,
      compose(
        createHOC(({ theme }) => withStyles(theme.global)),
        omitProps('classes')
      )
    )

**Comment by istarkov** [comment]
1. In your code you recreate WrappedComponent on every render, not good
2. Im pretty sure that author of WithStyles hoc will accept a PR allowing to initialize theme from props
I dont think that its a good idea because it will be always better to change the root of the problem and not to create workarounds.

**Comment by sbking** [comment]
@istarkov You're right, the code should look something like:

    const withThemeGlobalStyles = BaseComponent => {
      let globalStyles
      let WrappedComponent
      const WithThemeGlobalStyles = props => {
        if (globalStyles !== props.theme.globalStyles) {
          globalStyles = props.theme.globalStyles
          WrappedComponent = WrappedComponent || withStyles(props.theme.globalStyles)(BaseComponent)
        }
        return <WrappedComponent {...props} />
      }
      /* set display name */
      return WithThemeGlobalStyles
    }

As Material UI's 1.0 release nears, I strongly doubt they will accept a change to the `withStyles` API. I find that the majority of HOCs in other libraries do not have a way to get HOC settings from props, so I'm not sure that I agree about what is the root of the problem. It seems unlikely that the makers of say, Apollo, would introduce a new API for their `graphql` HOC so that the gql query could be passed in as a prop from another higher order component, and frankly I'm not sure if they should as it's a pattern that is not necessarily specific to Apollo.

What I'm proposing is a generic pattern that would allow any HOC to be enhanced so that rather than having to pre-configure the HOC with known arguments, its configuration would be taken from the props passed to it. Maybe this pattern doesn't make sense, as the logic of whether to recreate the wrapped component on subsequent renders will depend on which props the HOC uses for its configuration. It just seems like a natural extension from the composition/branching style encouraged by recompose.

**Comment by istarkov** [comment]
spinner can be done without any extension also
`renderComponent((props) => <div>{ props.spinner`

Apollo gql as I know need a static string to work otherwise query cant be precompiled so apollo creators has a reason to prevent passing it via props.

So I still not see any good example for this.

**Comment by sbking** [comment]
Okay, I will find another approach.
