### ISSUE TITLE
small type error on mapProps doc

### ISSUE THREAD

**Issue by zeakd** [acdlite/recompose#469]
please change `omit(keys, props)` to `omit(props, keys)` thanks!

correct doc
``` js
const omitProps = keys => mapProps(props => omit(props, keys))
```

**Comment by Isaddo** [comment]
The arguments order of lodash-fp's `omit()` is different from lodash's `omit()`
[FP-Guide#rearranged-arguments](https://github.com/lodash/lodash/wiki/FP-Guide#rearranged-arguments)

**Comment by zeakd** [comment]
oh, you are right. thanks
