### ISSUE TITLE
How to focus wrapped input elements?

### ISSUE THREAD

**Issue by krzysztofpniak** [acdlite/recompose#470]
I have following code:
```js
const enhanceInputOnChange = withHandlers({
    onChange: props => value => {
        props.onChange(value, props.id)
    }
});

const Input = enhanceInputOnChange('input');
```

then I'm storing few input refs using:
```jsx
<Input id="1" ref={e => this.controls["1"] = e} />
```
in `componentDidMount` I'm trying to set focus on the first field, but the `focus` method is not defined.

```js
const firstControl = this.controls[firstField.id];
if (firstControl) {
    firstControl.focus(); //Uncaught TypeError: firstControl.focus is not a function
}
```

Following approach works, but I'm not sure if it is recommended:
```js
firstControl._reactInternalInstance.getHostNode().focus()
```

Is this the only way to set the focus and access dom element after wrapping with recompose?

**Comment by istarkov** [comment]
You need to set ref on input DOM element, or use findDomNode
