### ISSUE TITLE
StackOverflow: How do you add refs to functional components using withHandlers?

### ISSUE THREAD

**Issue by GollyJer** [acdlite/recompose#472]
Hey everyone... I find GitHub Issues difficult to search so I thought I'd start asking more questions on StackOverflow and referencing them here.  More people will be able to find the answers.  If you do answer here I'll copy it over to SO.  Thanks!

**[How do you add refs to functional components using withHandlers in Recompose and call ScrollTo on a ScrollView?](https://stackoverflow.com/q/45678526/25197)**

**Comment by istarkov** [comment]
https://github.com/acdlite/recompose/pull/295#issue-197407889

**Comment by GollyJer** [comment]
Hi @istarkov. Thanks for the response.

I referenced your #295 in the SO question. I'm just not smart enough to understand how to use something with a very basic example.  Sorry 😛 

If I want to add the ref to my ScrollView, where do I put `registerChild`?  How do I give the ref a name so I can call ScrollTo?

Thanks again for the help.  At some point this stuff will click and I'll be able to pick things up quicker.

**Comment by istarkov** [comment]
https://github.com/acdlite/recompose/blob/67eaef8aae52613671f62b7887089951cfb198d4/types/flow-example/src/MouseDetector.js
see here registerChild

**Comment by GollyJer** [comment]
Got an [answer on SO](https://stackoverflow.com/a/45748180/25197) from @deepsweet.
Thanks you both @istarkov and @deepsweet.
