### ISSUE TITLE
componentFromStream swallows errors

### ISSUE THREAD

**Issue by TrySound** [acdlite/recompose#477]
via mostjs
```
componentFromStream(props$ =>
  props$.tap(() => {
    throw Error('custom error');
  })
);
```
It isn't obvious that error happend. Component just stops to work.

**Comment by istarkov** [comment]
Use recoverWith or how most handles the errors?

**Comment by TrySound** [comment]
It's not about error handling. I just don't see that error happend and can't find source of problem without debugging.

**Comment by istarkov** [comment]
This? https://github.com/cujojs/most/issues/198#issue-136164131

**Comment by TrySound** [comment]
https://github.com/cujojs/most/pull/477
