### ISSUE TITLE
Wrong version of peerDependency for rx-recompose

### ISSUE THREAD

**Issue by ahlee2326** [acdlite/recompose#48]
`ERROR in ./~/rx-recompose/observeProps.js
Module not found: Error: Cannot resolve module 'recompose/createHelper' `

`npm ERR! peerinvalid Peer rx-recompose@0.1.2 wants recompose@^0.8.0`

`createHelper` is only exists in 0.9.0 onwards.

**Comment by acdlite** [comment]
Oops! Good catch

**Comment by acdlite** [comment]
Fix released in v0.1.3
