### ISSUE TITLE
semver v1

### ISSUE THREAD

**Issue by graingert** [acdlite/recompose#481]
recompose has been around ~2 years now. And 0.25.0 released with no breaking changes.

I'd like to configure `"recompose": "^1.0.0"` as a dep so that I can automatically upgrade it by recreating my package lock.

**Comment by deepsweet** [comment]
Technically there is a breaking change in `0.25` so minor version bump while it's in zero major state was right.

**Comment by graingert** [comment]
@deepsweet according to the release notes it's "Production only optimisations" so I take that to mean non-breaking

**Comment by graingert** [comment]
@istarkov if there was a breaking change I'd like to see:


* **BREAKING**: broke the thing because it was bad and you shouldn't use it anyway

**Comment by istarkov** [comment]
1 It breaks tests
this is enough

**Comment by graingert** [comment]
@istarkov I'd like to be able to see what the breaking changes are in the shortest amount of time possible.

Could you please add breaking changes to the release notes

**Comment by istarkov** [comment]
All information about was added to release notes yesterday, I wrote about breaking change and gave aPR rref. This is enough.

**Comment by graingert** [comment]
@istarkov after reading through the release notes carefully I found the breaking change.

I'm future can you highlight breaking changes with **BREAKING**, please?

**Comment by istarkov** [comment]
Rules kills fun :-) Ill try :-) Thank you

**Comment by graingert** [comment]
@istarkov rules kill bugs

**Comment by istarkov** [comment]
I love bugs. Every new bug shows me that Im not Ideal and there is a reason to live further.

**Comment by graingert** [comment]
@istarkov functional programming is just rule composition

**Comment by istarkov** [comment]
Its not
