### ISSUE TITLE
A HOC to iterate children deeply and add a prop if type matches

### ISSUE THREAD

**Issue by Noitidart** [acdlite/recompose#482]
I was trying to write a HOC that adds a `prop` if it's a certain type. I am iterating through it depth first. But when I try to set prop it says it's not extensible, I am trying to add prop of `value` to `HEEHAW`. I don't see a helper in `recompose` for this, is there one?

    function fieldLayoutHOC(WrappedComponent: ComponentType) {
        return (
            class FieldLayoutWrap extends WrappedComponent {
                static displayName = wrapDisplayName(WrappedComponent, 'FieldLayoutWrap')
    
                render() {
                    const view = super.render()
                    // depth first - stack - last in first out
                    // iterate depth first until a Field is found
                    const elements = [view]; // stack
    
                    console.log('view:', view);
    
                    while (elements.length) {
                        const element = elements.pop();
                        const primative = typeof element;
                        if (primative === 'object') {
                            if (element.type === Field) {
                                // fields.push(element);
                                element.props.value = 'HEEHAW'; /////// not extensible error here
                                console.log('added value HEEHAWW');
                            } else {
                                if (element.props) {
                                    const children = element.props.children;
                                    if (children) {
                                        if (Array.isArray(children)) {
                                            elements.push(...children);
                                        } else {
                                            elements.push(children);
                                        }
                                    }
                                }
                            }
                        }
                    }
    
                    return view;
                }
            }
        )
    }

Am I doing it wrong?

**Comment by Noitidart** [comment]
Ok so I created a HOC to do this - https://stackoverflow.com/a/45767116/1828637

My first inheritance inversion HOC, yay.

**Comment by istarkov** [comment]
I'll close this feel free to reopen.
