### ISSUE TITLE
Use prop-types package instead of React.PropTypes

### ISSUE THREAD

**Issue by morajabi** [acdlite/recompose#483]
It seems in this code snippet https://github.com/acdlite/recompose/blob/master/docs/API.md#onlyupdateforproptypes
and maybe in the source code, you're using `React.PropTypes`. Now that we have `prop-types` package, we should use that. 

I can make a PR if you wish.

**Comment by istarkov** [comment]
Yes we wish, thank you

**Comment by morajabi** [comment]
It's here: #484
