### ISSUE TITLE
[withReducers] Handling updated props

### ISSUE THREAD

**Issue by p10ns11y** [acdlite/recompose#485]
I was wondering if re-initialisation is appropriate if new props arrives.
One use case is initialising data into form, and then handle the changes, and after the form is 
submitted, new props will arrive. But as of now `withReducers` will not re-initialise it.

https://github.com/acdlite/recompose/blob/master/src/packages/recompose/withReducer.js#L10

**Comment by istarkov** [comment]
There can be a lot of issues with reinitializing state based on external properties change or even rerender.
I wrote about https://github.com/acdlite/recompose/issues/368#issuecomment-297917744  https://github.com/acdlite/recompose/pull/397#issuecomment-306001357
and I'm pretty sure in other places too.
If you need this please use your own enhancer with logic you need, or try to avoid this if it possible.
