### ISSUE TITLE
Replace older jsfiddle link with updated example

### ISSUE THREAD

**Issue by samsch** [acdlite/recompose#486]
The jsfiddle linked from the README.md is based on the older React jsfiddle base. Since that base was created jsfiddle properly supports babel+jsx in the editor directly, which includes syntax highlighting.

The pull request to update to a new fiddle would be trivial, but I'm not certain of some possible opinions. The current fiddle uses `compose`, `withState`, and `withHandlers`, which has been surplanted by `withStateHandlers`. I created a [demo using `withStateHandlers`](https://jsfiddle.net/samsch/p3vsmrvo/). To support `withStateHandlers`, I used latest through unpkg ([https://unpkg.com/recompose/build/Recompose.js](https://unpkg.com/recompose/build/Recompose.js)) rather than pointing at a specific version.

However, if a different demo, or the older demo is preferred, its easy to (re)build off of my [updated base React jsfiddle](https://jsfiddle.net/samsch/nxjd9ens/), and gain syntax highlighting support.

**Comment by istarkov** [comment]
May be it will be better to use https://codesandbox.io/ as I was highly inspired when I saw it in this [comment](https://github.com/acdlite/recompose/issues/436#issuecomment-316964676) by @Andarist 
cc @wuct ?

**Comment by istarkov** [comment]
In all cases we will accept your PR @samsch 
Thank you!

**Comment by Andarist** [comment]
For the reference - https://github.com/CompuIves/codesandbox-client/issues/43

**Comment by samsch** [comment]
I think CodeSandbox is great resource, especially when where it makes sense to split your JS into multiple files.

`<opinion>`

For small examples, I personally prefer jsfiddle because it does not default to automatically running your code while you make changes to it. For example, while you are typing `const j = <Foo />;`, if you happen to hesitate at `const j = <`, then many of the other online environment will attempt to compile that code and print an error. I find this behavior disruptive.

`</opinion>`

I'll create a pull request with my example. No hard feeling if it's replaced with a CodeSandbox or different link later. In any case, just having the syntax highlighting will be an improvement, whichever solution is decided on.

**Comment by samsch** [comment]
Closed by #487
