### ISSUE TITLE
withPropsOnChange error

### ISSUE THREAD

**Issue by avkos** [acdlite/recompose#491]
Error in class withPropsOnChange

computedProps  should set in empty object every time when we receive new props
because if we not do this when props will receive next HOC receive previous computed props and never receive next props while shouldMap not return true
componentWillReceiveProps (nextProps) {
      this.computedProps = {}
      if (shouldMap(this.props, nextProps)) {
        this.computedProps = propsMapper(nextProps)
      }
}

**Comment by istarkov** [comment]
Could you provide a failing example, as I use withPropsOnChange since it first date (and even before) and never had any issues with.

**Comment by istarkov** [comment]
Feel free to reopen with example, you can use [jsbin](https://jsfiddle.net/samsch/p3vsmrvo/2/) as a base
