### ISSUE TITLE
Computed lifecycle hook keys not bound to Lifecycle.

### ISSUE THREAD

**Issue by Panoplos** [acdlite/recompose#492]
I have attempted to create a kind of debouncer or delayed action HOC as follows:

```es6
/* @flow */
import { compose, withState, lifecycle } from 'recompose'
import ms from 'ms'

type DelayableLifecycleHooks = 
  | 'componentWillMount'
  | 'componentDidMount'
  | 'componentWillReceiveProps'
  | 'componentWillUpdate'
  | 'componentDidUpdate'

type DelayedAction = (props: Object) => any

const withDelayedAction = (name: string, action: DelayedAction, lifecycleHook: DelayableLifecycleHooks, delay: string) => compose(
  withState(
    `${name}Timeout`,
    `set${name}Timeout`,
    null
  ),
  lifecycle({
    [lifecycleHook]: () => {
      const { [`${name}Timeout`]: timeout, [`set${name}Timeout`]: setTimer } = this.props
      timeout && clearTimeout(timeout)
      const later = () => {
        action(this.props)
      }
      setTimer(setTimeout(later, ms(delay)))
    }
  })
)

export default withDelayedAction
```

But when the hook is called by React, the function is not bound to `this`, so `this` is undefined (even though it is called as `imp.componentWillMount()`, for example.

![lifecycle hook issue](https://user-images.githubusercontent.com/2549985/29664435-8320ece8-890a-11e7-9a54-6cc416196fe1.png)

If I specify the lifecycle hook directly, it works as advertised.

**Comment by Panoplos** [comment]
Hmmm... also works if I use `[lifecycleHook]()`. Must be a quirk in how functions and methods are handled differently?

**Comment by istarkov** [comment]
Try this
```javascript
lifecycle({
    [lifecycleHook] () {
```

**Comment by istarkov** [comment]
In a case of `() => {}` it's `binded` but to parent context not the object

**Comment by istarkov** [comment]
A quick example https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&targets=&browsers=&builtIns=false&debug=false&code_lz=GYVwdgxgLglg9mABADVQCgJSIN4CgIIDOUixATogLyIDkAJgzQNz5EkCGVOuiiA2uQC6ALkSYqAPm69eBMITgAbAKYA6RXADmaGlAAWMQjQA0ifYYwteAX1y3c7VQzqYWtsMoDuKdJdy4gA

See right side.

**Comment by Panoplos** [comment]
Interesting... Thanks for that insight!

**Comment by istarkov** [comment]
Javascript is tricky language. Ill close this, feel free to reopen if ...
