### ISSUE TITLE
NODE_ENV=production breaks withHandlers

### ISSUE THREAD

**Issue by dictions** [acdlite/recompose#495]
I'm compiling via webpack, and the following works and correctly caches the ref in development.

```js
const DraftToolbar = ({
	onOpenFileBrowser
}) => (
	<Button onClick={onOpenFileBrowser}>
		Browse...
	</Button>
);

export default compose(
	withHandlers(() => {
		let fileInput;
		
		return {
			setFileInputRef: () => (ref) => {
				if (ref) {
					fileInput = ref;
				} else {
					fileInput = undefined;
				}
			},
			onOpenFileBrowser: () => () => {
				fileInput && fileInput.chooseFiles();
			},
		};
	}),
)(DraftToolbar);
```

Compiling throws this error when `NODE_ENV=production`:

```
ERROR in ./src/components/DraftToolbar.jsx
Module parse failed: /Users/ianwilliams/dev/tapwater/frontend/node_modules/babel-loader/lib/index.js!/Users/ianwilliams/dev/tapwater/frontend/node_modules/eslint-loader/index.js!/Users/ianwilliams/dev/tapwater/frontend/src/components/DraftToolbar.jsx Unexpected token (167:41)
You may need an appropriate loader to handle this file type.
```

This issue is fixed if I wrap the function within another function call inside the render method:

```js
const DraftToolbar = ({
	onOpenFileBrowser
}) => (
	<Button onClick={() => onOpenFileBrowser()}>
		Browse...
	</Button>
);

export default compose(
	withHandlers(() => {
		let fileInput; // eslint-disable-line
		
		return {
			setFileInputRef: () => (ref) => {
				if (ref) {
					fileInput = ref;
				} else {
					fileInput = undefined;
				}
			},
			onOpenFileBrowser: () => () => {
				fileInput && fileInput.chooseFiles();
			},
		};
	}),
)(DraftToolbar);
```

Is this expected behavior?

**Comment by istarkov** [comment]
Seems like the problem with your babel config check it carefully. Compiler errors in your code have nothing with this library so I'll close this issue.

**Comment by dictions** [comment]
@istarkov thanks, I found it. `transform-react-constant-elements` was hoisting when it shouldn't have.

**Comment by udisun** [comment]
@istarkov i have the exact same problem, did you remove `transform-react-constant-elements` completely or did you find another solution?

**Comment by istarkov** [comment]
@udisun this problem have zero intersections with recompose, why are you asking me?

**Comment by dictions** [comment]
@udisun i think you mentioned the wrong person. i removed `transform-react-constant-elements` completely.
