### ISSUE TITLE
v0.25.0 has a breaking change

### ISSUE THREAD

**Issue by dotintegral** [acdlite/recompose#496]
Hi,

I have had simple test setup (jest+enzyme) that was working correctly under v0.24.0, where I used `defaultProps` to bind `MyComponent` with mock data.

```
const mockData = {
  myProp1: 'one',
  myProp2: 'two'
 // ...
}

const EnhancedComponent = defaultProps(mockData)(MyComponent)
```

The test itself was pretty simple:
```
  test('have proper className', () => {
    const wrapper = shallow(<EnhancedComponent />)

    expect(wrapper.hasClass('my-class')).toBeTruthy()
  })
```

After upgrading to `v0.25.0` The following test and other similar stopped working. For now, only workaround that I see is to use enzyme's `mount` instead of `shallow`.

Is this a bug or a feature? If feature, it might be a good idea to mark this as a breaking change or in the other way. Simply to avoid developers going `WTF`.

**Comment by istarkov** [comment]
Its marked at releases page, also having that version is below 1.0 every Minor release is Major ;-) 
plz read here https://docs.npmjs.com/misc/semver about many authors treat 0.x :-)
