### ISSUE TITLE
Is there a way to call forceUpdate() with recompose?

### ISSUE THREAD

**Issue by GollyJer** [acdlite/recompose#497]
I need to force the update of a component with forceUpdate and wonder if the only way is to convert a functional component to a class (which I don't want to do).

- [React docs on forceUpdate()](https://facebook.github.io/react/docs/react-component.html#forceupdate
)
- A codepen example of [forceUpdate](https://codepen.io/SyedAfrozPasha/pen/YWJwpy?editors=0010
).

Yes this is unorthodox but I'm hoping there's a way to do.  I can go into more detail if anyone needs, but the **tldr** version is I'm mapping props from one component to another via react-navigation params.  In this way I'm able to access screen _component_ props in the screen _header_ props.  However, changing prop/state values in one does not fire a render in the other.  

forceUpdate solves this issue. Can I somehow call it with recompose?

Thanks!

**Comment by istarkov** [comment]
we have toClass enhancer :-)

**Comment by GollyJer** [comment]
@istarkov Thank you, as always, for the help.  I tried to figure it out on my own but am stuck. 😞 
How would you [recreate this example](https://codepen.io/SyedAfrozPasha/pen/YWJwpy?editors=0010
) using toClass?

**Comment by istarkov** [comment]
```javascript
const someFuntionalComponent = () => ...
const EnhancedFunctional = toClass(someFuntionalComponent)

....

<EnhancedFunctional ref={registerRef} />
ref now has forceUpdate ;-)

```

**Comment by GollyJer** [comment]
Thanks!
