### ISSUE TITLE
withStateHandlers - Having a way to reset the state on new props

### ISSUE THREAD

**Issue by tleunen** [acdlite/recompose#498]
Hey,

I have a use case where I'd like to reset the state when one of my props get updated, but currently it seems there's no way to do so with `withStateHandlers`.

Would you be open to a PR with this new functionality? The way I'm seeing it is to have a third argument which would be a function taking `props` and `nextProps` and returning a boolean. And then having the HOC implementing `componentWillReceiveProps`.

Thanks.

**Comment by istarkov** [comment]
I wrote here a lot of words why we will not accept such PR
One of comments https://github.com/acdlite/recompose/issues/368#issuecomment-297917744
But a lot of more can be found using search ;-)
Feel free to reopen if u have questions.

**Comment by istarkov** [comment]
I even did such enhancer https://github.com/acdlite/recompose/issues/199
Really hard to use in real practice :-)

**Comment by tleunen** [comment]
Yeah I read, but you know... I could still try to have it implemented here instead of my own app ;)
My use case is because my state depends on a prop, and then the state can be modified in the UI without modifying my prop. And I use that specific state for another HoC, so I used `withStateHandlers` so it prevent me from creating another upper component with only that state.

**Comment by city41** [comment]
This doesn't make sense to me. withStateHandlers accepts a function to derive the initial state from props. This function is essentially playing the role that `getDerivedStateFromProps` is now playing for React in general. Why wouldn't the state initializer function get called again upon new props, just like getDerivedStateFromProps does? It doesn't make sense to me to derive state from props, but only for the first set of props that come in. What am I missing?

**Comment by eloff** [comment]
> I suppose one thing that is missing is the initialState function only takes in props, not state. So that is one piece of the puzzle. I still find it puzzling withStateHandlers allows state to be derived from the initial set of props but not subsequent ones.

That's the part the gets me too. I think the initialization function should take (props, state) and be called on initial setup and when props change. I don't see how that would be backward compatible though, it would probably need to be a new function if it were added.

I'm having trouble with this very thing because my component is getting re-created somehow and that causes a new state to be derived and the old state to be discarded (which is giving me grief.)
