### ISSUE TITLE
Flow not catching errors when using a recompose HOC in a separate file

### ISSUE THREAD

**Issue by ericbiewener** [acdlite/recompose#501]
When using either mapProps or withProps, Flow is not catching an error when I import and use the HOC in a separate file, but does catch it when using the HOC in the same file as where it's declared. Perhaps this happens with other recompose functions as well -- I haven't confirmed.

A simple test case:

**MyComponent.js**
```js
type Props = { name: string, age: number };

export const MyComponent = ({ name, age }: Props) => <div>{name} - {age}</div>;
```
**Hoc.js**
```js
import { MyComponent } from "./MyComponent";

export const Hoc = withProps({ age: 30 })(MyComponent);

const Test = () => <Hoc />; // Correctly throws flow error about missing `name` prop
```

**otherFile.js**
```js
import { Hoc } from "./Hoc";

const Test = () => <Hoc />; // No error!
```

**Comment by istarkov** [comment]
Please read docs and declare HOC right https://github.com/acdlite/recompose/tree/master/types
