### ISSUE TITLE
lifecycle does not get defaultProps from pure component

### ISSUE THREAD

**Issue by pr1ntr** [acdlite/recompose#502]
This is my example: https://gist.github.com/pr1ntr/15531b21736fbf66eb67aa5f01c7d238

`id` from `defaultProps` does not show up in` this.props`

**Comment by pr1ntr** [comment]
can you elaborate, also is lifecycle being deprecated?

**Comment by istarkov** [comment]
Why are you thinking that defining static property in one place it must propagate there you want?
What to elaborate here ;-)

Just use `defaultProps` enhancer and all will be fine 
```
compose(
defaultProps({ blabla }),
...
)
```

yep I think it will be deprecated

**Comment by pr1ntr** [comment]
thanks
