### ISSUE TITLE
switch() ?

### ISSUE THREAD

**Issue by dakom** [acdlite/recompose#503]
There's times where I need something more complicated than a `branch()` and so I end up with some sort of `switch()`

What is the idiomatic way to do this - and should it be something in the api along with branch? Consider:

```
const View = ({someProp, ...props}) => {
    
    switch(someProp) {
        case "foo": return Foo;
        case "bar": return Bar;
        case "baz": return Baz;
    }
};

export const MyComponent = enhance(props => View(props)(props));
```

This could be made cleaner by returning the child components like `Foo(props)`, but then that's a lot of repetition - or setting an internal mutable variable.

Not sure what the best solution here would look like, curious to hear thoughts from others :)

**Comment by istarkov** [comment]
plz read https://github.com/acdlite/recompose/search?q=switch+branch&type=Issues&utf8=%E2%9C%93

**Comment by dakom** [comment]
lol, thanks ;)
