### ISSUE TITLE
install from git?

### ISSUE THREAD

**Issue by dakom** [acdlite/recompose#504]
Installing as a package from git (setting "recompose": "git+https://github.com/acdlite/recompose.git") doesn't work

How can I install the latest recompose with the latest commit? (I'm getting some weird errors that I can't duplicate on jsbin, and want to see if it's magically resolved by upgrading)

**Comment by istarkov** [comment]
there is latest version in npm now.

**Comment by Silviu-Marian** [comment]
Can you try installing another package, which isn't recompose?
If it works, can you try installing other package from acdlite?

Also can you please post some output?

**Comment by dakom** [comment]
If it's not intended to be installed from Github feel free to close this issue :)

@Silviu-Marian - I've done this with some other projects, but I'm not so clear on exactly how npm works and what the rules are. Of course not every repo is setup to work that way ;)
