### ISSUE TITLE
Calling component function or constructing React element is not rendering deeply automatically any more in version 0.25.

### ISSUE THREAD

**Issue by Stupidism** [acdlite/recompose#505]
**Do you want to request a *feature* or report a *bug*?**
report a bug

**What is the current behavior?**
component is not deeply rendered after upgraded to v0.25.0

**If the current behavior is a bug, please provide the steps to reproduce and either a repl.it demo through https://repl.it/languages/jest or a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

The greenkeeper [PR](https://github.com/Stupidism/stupid-rc-starter/pull/40).
The travis CI [result](https://travis-ci.org/Stupidism/stupid-rc-starter/jobs/272743601)

Take omitProps as an example: 
I have a test file like this running well in v0.24.0, but failed in v0.25.0: 
```
/* eslint-env jest */
import React from 'react';
import omitProps from '../omitProps';
import withPropsPeeker from '../withPropsPeeker';

test('omitProps removes the some props of the new component', () => {
  const props = {};
  const BaseComponent = withPropsPeeker(props)(() => <div />);
  const NewComponent = omitProps(['foo'])(BaseComponent);

  NewComponent({ foo: 1, bar: 1 }); // Or <NewComponent foo={1} bar={1}/>;
  expect(props).toEqual({ bar: 1 });
});

```

```
FAIL  src/hocs/__tests__/omitProps.test.js
  ● omitProps removes the some props of the new component
    expect(received).toEqual(expected)
    
    Expected value to equal:
      {"bar": 1}
    Received:
      {}
    
```

Turns out the component is not deeply rendered.
I have to change the code to this:
```
/* eslint-env jest */
import React from 'react';
import { render } from 'enzyme'
import omitProps from '../omitProps';
import withPropsPeeker from '../withPropsPeeker';

test('omitProps removes the some props of the new component', () => {
  const props = {};
  const BaseComponent = withPropsPeeker(props)(() => <div />);
  const NewComponent = omitProps(['foo'])(BaseComponent);

  render(<NewComponent foo={1} bar={1}/>);
  expect(props).toEqual({ bar: 1 });
});
```

**What is the expected behavior?**
If this is a indented behaviour update, then we need a migration guide for this update.
Otherwise, it should deeply render the component like before.

**Please provide your exact Jest configuration and mention your Jest, node, yarn/npm version and operating system.**
You can run the [project](https://github.com/Stupidism/stupid-rc-starter/tree/greenkeeper/recompose-0.25.0)'s test.

**Comment by Stupidism** [comment]
It's quite wired that `recompose`, as a hoc component library, affects my test environment.

**Comment by istarkov** [comment]
Or may be tests were initially written in a wrong manner, creating a component you expected that it is a function. By definition hoc is a function that takes a component and returns a new component. Not a function!!!

**Comment by Stupidism** [comment]
@istarkov `<NewComponent foo={1} bar={1}/>` is not working, either.

**Comment by istarkov** [comment]
I see no recompose in examples above.
Your tests fail on your hocs

**Comment by istarkov** [comment]
Check out our tests https://github.com/acdlite/recompose/tree/master/src/packages/recompose/__tests__  as an examples

**Comment by Stupidism** [comment]
My hoc used `mapProps` and I imitated your examples at the very beginning actually. The only difference is I use `<Component />` instead of `mount(<Component />)`. I know `mount` will fix my current problem.
However, I'm wondering what has changed between v0.24 and v0.25.

**Comment by istarkov** [comment]
Why we provide releases ;-) https://github.com/acdlite/recompose/releases
In your case this is this https://github.com/acdlite/recompose/pull/473
and that change was made to make tests experience better ;-)

**Comment by Stupidism** [comment]
Sorry, I didn't realized this is related the hocs I used when I tried to find clues from release description. Thanks for your patience any way.
