### ISSUE TITLE
Provide HOC for accessing instance members

### ISSUE THREAD

**Issue by jfschwarz** [acdlite/recompose#507]
I love recompose and I find myself using it to an extent that I practically never ever write class based component anymore. There is just one situation, where I still have to use class components (or clunky `lifecycle` HOCs): When I need to make use of instance members. 

**use cases for instance members:**
- storing refs
- synchronous/instantaneous state updates (when I need to keep track of some state that is read by non-rendering code such as event handlers)

I'm wondering why recompose does not offer a HOC for this purpose? Maybe I'm overlooking some solution that's more simple?

After I found myself having to store stuff in instance members quite a couple of times, I implemented my own HOC factory function `accessInstanceMember` based on recompose. Look at its code below to get a better understanding of what it does. Of course, I'd be happy to submit this as a PR in case you would consider it useful.

```javascript
import { Component } from 'react'
import { setDisplayName, wrapDisplayName, createEagerFactory } from 'recompose'

// Injects props for getting and setting a value stored as an instance member. Useful when
// setting a value does not need to trigger a re-render and when that value update should be
// instantaneous instead of batched.
const accessInstanceMember = (
  getterName,
  setterName,
  initialValue
) => BaseComponent => {
  const factory = createEagerFactory(BaseComponent)
  class AccessInstanceMember extends Component {
    value = typeof initialValue === 'function' ? initialValue(this.props) : initialValue

    getValue = () => this.value

    setValue = (newValue) => {
      this.value = newValue
    }

    render() {
      return factory({
        ...this.props,
        [getterName]: this.getValue,
        [setterName]: this.setValue,
      })
    }
  }

  if (process.env.NODE_ENV !== 'production') {
    return setDisplayName(wrapDisplayName(BaseComponent, 'accessInstanceMember'))(
      AccessInstanceMember
    )
  }
  return AccessInstanceMember
}

export default accessInstanceMember
```

**Comment by istarkov** [comment]
`withHandlers` can be used for this purposes as an example https://github.com/acdlite/recompose/blob/master/types/flow-example/src/ItemsAnimator.js#L85

BTW it's not recommended and not a good practice ;-) as in the future this can fail.
(seems like in a not far future holding state in instances will be considered as a bad practice, as it prevents some future react optimisations)

**Comment by jfschwarz** [comment]
Ah indeed, using `withHandlers` is a better approach. Funny, how sometimes I just don't see the simple way... Now it seems so obvious.

Thank you!

**Comment by ospfranco** [comment]
I'm sorry I don't see how this can be used to call an instance method from a parent component, maybe could you post some snippet?
