### ISSUE TITLE
Shouldn't state and nextState be passed to shouldUpdate?

### ISSUE THREAD

**Issue by griezma** [acdlite/recompose#509]
The shouldUpdate function has only 2 parameters, props and nextProps. 
You cannot decide about the result without also comparing state and nextState.
Am I missing something?

**Comment by istarkov** [comment]
yep, there is no state in most of enhancers, so we don't need to compare state

**Comment by griezma** [comment]
but you can also enhance components with state. that's why I asked.

**Comment by wuct** [comment]
You can enhance components with `withState`, but the state created in `withState` is actually `props` to its base components.
