### ISSUE TITLE
Will recompose support componentDidCatch() for React 16?

### ISSUE THREAD

**Issue by SeanGroff** [acdlite/recompose#510]
Will the [lifecycle()](https://github.com/acdlite/recompose/blob/master/docs/API.md#lifecycle) method be updated to support `componentDidCatch()` when React 16 is released?

**Comment by istarkov** [comment]
see lifecycle deprecate in search

**Comment by kachkaev** [comment]
https://github.com/acdlite/recompose/issues/452 might be a useful read for those you are here from the search.

**Comment by xgqfrms-GitHub** [comment]
# bug ???

> maybe it still in development?


https://github.com/gildata/RAIO/issues/179#issuecomment-334910224

**Comment by wuct** [comment]
@xgqfrms-GitHub The link you provided is not related to recompose. What's your question?
