### ISSUE TITLE
Prop flow typing when base component can accept additional props beyond what HOC requires

### ISSUE THREAD

**Issue by ericbiewener** [acdlite/recompose#511]
All the examples and README in the [types](https://github.com/acdlite/recompose/tree/master/types) folder enhance base components that have the same prop types as the HOC enhancer itself. For example, [`item`](https://github.com/acdlite/recompose/blob/master/types/flow-example/src/Item.js#L27) does not require any props that are not already being typed by [`enhanceItem`](https://github.com/acdlite/recompose/blob/master/types/flow-example/src/Item.js#L39). 

But what if we had a more generic enhancer that could be used on a variety of base components, each of which may have different prop requirements? For example, adding a click handler with a defined callback argument:

```js
type OnClickProps = {
  onClick: * => void,
  onClickArg?: *
};

const withOnClick: HOC<*, OnClickProps> = withHandlers({
  onClick: props => () => props.onClick(props.onClickArg),
});

type ThingProps = {
  onClick: () => void,
  label: string
};

const Thing = ({ onClick, label }: ThingProps) => <button onClick={onClick}>{label}</button>;

const EnhancedThing = withOnClick(Thing);

const RenderTheThing = () => (
  <EnhancedThing
    onClick={(arg: string) => console.log(arg)}
    onClickArg={"onClick arg"}
    label="Click Me!"
  />
);

```
In the above example, Flow complains that:
> property 'label' not found in object type

Is this solvable? `withOnClick` doesn't care/know that the `label` prop is being passed to the enhanced component, so it doesn't get typed with that prop. Removing `ThingProps` from the typing of `Thing` still produces the same Flow error (although Flow previously pointed to that type annotation as the problem, whereas now it will point directly to the destructured `label` prop).

**Comment by istarkov** [comment]
See flow annotations of `withProps` as here is not a big difference in `withOnClick`
Also read https://medium.com/flow-type/flow-support-in-recompose-1b76f58f4cfc
there is a section at the end about how to annotate your own HOCs.

**Comment by ericbiewener** [comment]
Are you suggesting that I don't use `withHandlers` at all, and instead just write my own non-recompose HOC?

**Comment by istarkov** [comment]
I suggesting to make mind difference between component with enhancer annotation and just enhancer annotation. If you want just enhancer annotation - it will have different type definitions.
Type definitions are open see libdef, try your example - it's not hard, just practice.

**Comment by ericbiewener** [comment]
I'm sorry, I'm still unclear on the direction you're trying to point me in. Are you saying there a way to annotate my `withOnClick` enhancer using recompose's `withHandlers` function so that this flow issue gets resolved? Or are you saying that I need to entirely write my own HOC so that I can type it as needed?

I guess the deeper question here is whether a single recompose enhancer can be used multiple times with components that expect different props, or if a single enhancer can only be used with components that expect the same props (from the perspective of keeping Flow happy).

Thanks for your patience as I try understanding this HOC typing!

**Comment by istarkov** [comment]
There are a lot of here:
You can't use * to annotate reusable HOCs, as flow internally replaces * with some exact type from current module if it can find it. So * is not any compatible type but first type which is suitable
You can't use * to annotate `type OnClickProps` for the same reason
Having that almost all in current typedef uses idea that we know Enhanced component type (all hocs transforms base props not enhanced) this enhancer has a strong requirement that enhanced component must have onClick this will cause issues with type inference if you'll be not very accurate. I wanna say that such enhancer will always be a pain as you need always remember about this requirement on enhanced type. 
What I can recommend - try to annotate it using your own function, then if this succeed try to go further ;-)

**Comment by ericbiewener** [comment]
Ok, thanks for the discussion!
