### ISSUE TITLE
withStateHandlers callback

### ISSUE THREAD

**Issue by cdomigan** [acdlite/recompose#512]
Calling a callback after setState() is a common and helpful React pattern, I'm confused why withStateHandlers doesn't support it?

Eg. I want to update a searchString state item, and then trigger an async load that uses that state.

```
withStateHandlers({
    searchString: ''
}, {
    setSearchString: (state) => (newString) => ({searchString: newString})
}),
withHandlers({
    load: ({searchString}) => () => load(searchString)
}),
withHandlers({
    onSearchChange: ({setSearchString, load}) => (newString) => setSearchString(newString, load)
})
```

**Comment by istarkov** [comment]
Because the only thing you can do in that callback with current api is to call some side-effect. 
We don't want to provide such api.
Also you can search issues I wrote about in other places.

**Comment by dolezel** [comment]
In `withState` and `withReducer` you support callback. I do not understand why in this function you do not want to provide callback.

**Comment by elliotaplant** [comment]
@istarkov - could you provide a link to the issues you wrote in other places? I'm having trouble understanding why we would want to support a post `setState` callback on `withState` and `withReducer`, but not on `withStateHandlers`.

It seems like a reasonable generic use case might look like this:

```jsx
function onStateUpdated(newState) {
  // Do something with the newState
}

function MyComponent({ myState, myStateHandler }) {
  return (
    <button onClick={() => myStateHandler(Math.random(), onStateUpdated)}>
      Click me to randomize part of state
    </button>
  )
}

const MyComponentWithStateHandlers = withStateHandlers({
  myState: 0,
}, {
  myStateHandler: () => (newValue) => ({ myState: newValue }),
})(MyComponent)
```

**Comment by olsonpm** [comment]
As a workaround I'm just making a withHandler which wraps the withState setter and exposes a callback in its signature.  It's not the best solution but I don't like the alternatives.
