### ISSUE TITLE
withPropsOnChange renders props regarding of shouldMapOrKeys function

### ISSUE THREAD

**Issue by Rhjulskov** [acdlite/recompose#513]
I don't know, if i'm missing the intention of this HOC, but when given shouldMapOrKeys a function returning false, the props is set and updated each time?

**Comment by istarkov** [comment]
No, it has a very simple code, just look inside. It does not prevent rendering, it just recalculate something on change

**Comment by istarkov** [comment]
https://github.com/acdlite/recompose/blob/master/src/packages/recompose/withPropsOnChange.js#L24

**Comment by Rhjulskov** [comment]
Oh, I thought I could store an initial props (singleton-ish) like here, where I only recieve the apiKey on the first request and want to store it for the duration of the runtime:
```js
withPropsOnChange(
  ({ apiKey }, nextProps) => Boolean(apiKey  && !nextProps.apiKey)
  ({ apiKey }) => ({
    apiKey,
  })
),
```

Thank you for the quick answer

**Comment by istarkov** [comment]
For one time store I use syntax ;-)
```
withPropsOnChange(
  [],
  ({ blabla }) => ({
    blublu: calc(blabla),
  })
),
```
