### ISSUE TITLE
request: mapProp HOC

### ISSUE THREAD

**Issue by mcky** [acdlite/recompose#514]
I find myself writing this same pattern a lot (so much that I'm now moving it to a util) to apply a function to a single prop:
```js
mapProps(_.update('articles', _.chunk(2)))
```
```js
mapProps(_.update('content', _.splitLines))
```

So I propose `mapProp`/`updateProp`:
```js
mapProp('items', items => items.slice(0, 3))
```
This doesn't handle the case of needing to pass other props to the function, in which case I guess you'd still need to step back to mapProps, eg:
```js
mapProps(p => _.update('items', items => items.slice(0, p.itemCount), p))
mapProps(p => _.update('items', _.slice(p.itemCount), p))
```

I saw from some other issues that composition with `mapProps` is preferred, and you're looking to slim down the API, so I'll understand if this is a no :)

**Comment by istarkov** [comment]
How this
```
mapProp('items', items => items.slice(0, 3))
```
differs from this
```
withProp(({items}) => ({items: items.slice(0, 3)}))
```
 
In all cases I would prefer the last variant, it supports flowtype, it uses +- native language construct instead of some string key manipulation

**Comment by mcky** [comment]
I guess it's down to preference, but I heavily use ramda/lodash, so my actual use case would be
```js
mapProp('items', slice(0, 3))
```
which I feel is much more expressive, it cuts through the noise and expresses just the operation. I am concious that as a lib you don't want to overfit to cases like that however.

I'm also personally I'm not a fan of constantly destructuring and re-boxing up objects, but that's also just preference. Good point re typing etc.
