### ISSUE TITLE
withStateHandlers documentation does not agree with behavior

### ISSUE THREAD

**Issue by idris** [acdlite/recompose#515]
The `withStateHandler` docs say:
> Every state updater function ... must return a new state or undefined

[But the code uses React's `setState`](https://github.com/acdlite/recompose/blob/1465683bcfc58b2939d246e7a30b760ac192c977/src/packages/recompose/withStateHandlers.js#L25)

[React's `setState` docs](https://facebook.github.io/react/docs/react-component.html#setstate) say:
> The output of the updater is shallowly merged with `prevState`.

**Comment by wuct** [comment]
Thanks for reporting. I think the doc need some modification, like

> Every state updater function ... must return a new state or undefined which is shallowly merged with `prevState`.

Would you mind to open a PR for it?

**Comment by idris** [comment]
@wuct #518 submitted! Thanks.

**Comment by wuct** [comment]
@idris Thanks!
