### ISSUE TITLE
Export createEventHandlerWithConfig()?

### ISSUE THREAD

**Issue by acchou** [acdlite/recompose#520]
The documentation suggests using functions like `componentFromStreamWithConfig()` instead of `componentFromStream()` to avoid having to set global state with `setObservableConfig()`.

It seems there's also a similar situation with `createEventHandlerWithConfig()` vs `createEventHandler()`. There are two issues though:

(1) There's no mention of `createEventHandlerWithConfig()` in the docs.
(2) The Typescript typings for recompose don't export `createEventHandlerWithConfig()`, so it appears to be unavailable as an import.

I'd be happy to submit a pull request if I get some direction on where this should go.

**Comment by wuct** [comment]
Thanks for reporting. Tasks we can do including:

1. mention `createEventHandlerWithConfig()` in the doc.
2. re-export `createEventHandlerWithConfig()` in [index.js](https://github.com/acdlite/recompose/blob/master/src/packages/recompose/index.js)

A PR is welcome :)

We don't have TypeScript def in this repo, so you probably need to open a PR where it is.
