### ISSUE TITLE
Input loses focus on change

### ISSUE THREAD

**Issue by ilya-pyatin** [acdlite/recompose#524]
Hello:

I have an issue that an input loses focus when it's value is changed. The input is contained inside a component wrapped in withProps().

Here is an example that shows the issue - https://codepen.io/ilya-pyatin/pen/qPZwVG?editors=0010.

Is it possible to fix this issue somehow?

Thank you

**Comment by istarkov** [comment]
Yep, stop use recompose in this way, look at examples, tests, docs.
Your problem is that you create a new component every new render.
