### ISSUE TITLE
mobx observer + withState doesn't update component since 0.25 

### ISSUE THREAD

**Issue by ioRekz** [acdlite/recompose#527]
After updating from 0.24 to 0.25

A component using 
```
const enhance = withState("addon", "setAddon", false);
export default observer(
  enhance(({ showModal, addon, setAddon }) => {
```
won't rerender when data from mobx store is updated

I'm using 
```
"mobx": "^3.3.0",
"mobx-react": "^4.3.2",
"recompose": "^0.25.0"
```

when going back to 0.24.0 again, the component works fine and is updated.

I'm also fine getting a "you should not use withState like this" answer, if explained, as it's my first project using recompose.

**Comment by istarkov** [comment]
Please investigate, as I know nothing has changed at least in dev mode to explain this. 
If you need help dont forget to provide examples (codesandbox etc). Otherwise Im pretty sure your issue will not be resolved.
