### ISSUE TITLE
Feature request: debouncedprop

### ISSUE THREAD

**Issue by tkvw** [acdlite/recompose#528]
It would be nice to have a debouncedprop hoc. 
```
debouncedProps({ debounce: 100, propNames: [ 'value' ] })
```

I found an implementation here: 
https://github.com/apollographql/react-apollo/issues/450

**Comment by istarkov** [comment]
Also here https://github.com/deepsweet/hocs etc,
use them, there is no need to duplicate code, also debouncedProp is not that HOC we want to see in this library.
