### ISSUE TITLE
Q: How to access props in lifecycle hooks in `lifecycle` HOC

### ISSUE THREAD

**Issue by vanniewelt** [acdlite/recompose#532]
```js
lifecycle({
  componentDidMount: () => {
    // How do i get prop here?
  }
})(Component)
```

**Comment by timkindberg** [comment]
`this.props`

**Comment by dkrieger** [comment]
it seems this doesn't work when using arrow functions?

**Comment by KamuelaFranco** [comment]
Is it working with alternative syntax for object methods? E.g.
```
lifecycle({
  componentDidMount() {
    this.props;
  }
})(Component)
```

**Comment by dkrieger** [comment]
The alternative syntax worked for me, not the arrow fn. I'll test again but I'm pretty sure syntax was all I changed for it to work. Using es2015 and stage 2 in my babel config

**Comment by deepsweet** [comment]
you could try [@hocs/with-lifecycle](https://github.com/deepsweet/hocs/tree/master/packages/with-lifecycle), works with arrow functions as well and doesn't depend on `this`:

```js
withLifecycle(
  onDidMount: (props) => // ...
)
```

**Comment by KamuelaFranco** [comment]
@deepsweet Any way to integrate that implementation into this project?

**Comment by istarkov** [comment]
No way. Use search here for why.

**Comment by istarkov** [comment]
No way. Use search here for why.

**Comment by wuct** [comment]
The behavior in a arrow function is expected, because [arrow functions have no binding of `this`.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions)
