### ISSUE TITLE
withState | access state value

### ISSUE THREAD

**Issue by sqndr** [acdlite/recompose#535]
I am using `withState('value, 'setValue', '')` to keep the state of an input field. When the input field is changed, I want to  update the state, and debounce a `search` action (after 300ms).

The issue I am running into, is that when I want to acces my state in the onChange handler on my input field, my state is not up to date (from calling `setValue()`).

I figured out that I should not be using the `value` right after `setValue` (with basically calls `setState`), since this is synchronously and you should not use `this.state.value` after setting state. So … I figure I should use a callback function: https://www.webpackbin.com/bins/-KvC7Ui2TNnxCqRJ6I6w

However, I always get the previous state returned, instead of the "new state". Is this a bug? Or how can I fix this? Thanks!

**Comment by istarkov** [comment]
1 example - value is updated but you use previous definition of logResult with old value inside it's not because something async or sync it's just how javascript works.

2nd example is the same as first.


I can't get what the question?

**Comment by sqndr** [comment]
> 1 example - value is updated but you use previous definition of logResult with old value inside it's not because something async or sync it's just how javascript works.

@istarkov How can I, in this example, log the current state instead of the previous state? How can I acces the new value?

**Comment by istarkov** [comment]
log current
https://www.webpackbin.com/bins/-KvCDTdtiU_rKwbpgcUO

for your case, you don't need to access current state value, you can debounce in handler 
see here https://github.com/deepsweet/hocs debounce hoc

**Comment by istarkov** [comment]
BTW I would recommend you to read something about javascript, about variables closures, scopes etc

**Comment by sqndr** [comment]
@istarkov Could you point me in any direction where I can read more about this? Do you have an example of this using a debounce handler? What I am trying to do is keep a state for input field, and only once per eg. 500ms trigger a `search()` action. For this example I instead used a logger, just so I can see the result. 

Thanks for your help.

**Comment by sqndr** [comment]
Using a class: https://www.webpackbin.com/bins/-KvCZF-K1MWOiFb3MobY
Using recompose: https://www.webpackbin.com/bins/-KvCZsOSaIXs9v29cQL1

Still trying to figure out the difference 🤓
