### ISSUE TITLE
Proposal: bindPropsToHandlers

### ISSUE THREAD

**Issue by iddan** [acdlite/recompose#536]
Binding handlers to events in React was always awkward. It is very common to see developers do this like:

```javascript
class Form extends Component {
     render() {
          return <Control onChange={(value) => this.setState({ 'key': value })} />
     }
}
```

This is problematic as the `Control` element will always get a new onChange prop in each render.
To solve this required a decent amount of boilerplate code that either: avoids Control from listening to onChange changes or binding a prop that Control receives to it's event handlers invocation. This proposal aims to solve this using a higher order component that will pass the props in the event handler invocation and by that passing the required context for handling the event properly in the parent component.

The code I came up with and tested by now is:
```javascript
const bindPropsToEvents = (WrappedComponent, eventProps) =>
    class extends PureComponent {
        static displayName = `WithProps(${getDisplayName(WrappedComponent)})`

        eventHandlers = eventProps.reduce(
            (acc, eventProp) => ({
                ...acc,
                [eventProp]: (...args) => {
                    this.props[eventProp](...args, this.props)
                },
            }),
            {},
        )

        render() {
            return (<WrappedComponent
                {...this.props}
                {...this.eventHandlers}
            />)
        }
    }
```
usage would be:
```javascript
const ControlWithProps = bindPropsToHandlers(Control, ['onChange'])
```

Is this HOC would be welcome as a PR?

**Comment by istarkov** [comment]
Have you read the docs? withHandlers and withStateHandlers are already there long time ago

**Comment by iddan** [comment]
I guess `withHandlers` would do even though here there is less boilerplate code. Maybe it will be worthwhile to consider a shortcut that only passes props and doesn't require boilerplate code to describe this behaviour.

**Comment by istarkov** [comment]
There are also issues with typings in your proposal (string keys is hard to type) 
And you could always make a simple wrapper over withHandlers to make it similar to what you wrote. We try to not extend recompose API providing all the ideas we all have ;-) as I see withHandlers is more abstract and allows to do more things vs proposal above, also it supports flow type (inference etc) so I would like to not accept proposal above.
Small api surface is not the bad thing for library.
Ill close this, feel free to reopen if ...

**Comment by iddan** [comment]
NP, that's why I initially I created issue before sending a full fledged PR.
