### ISSUE TITLE
state set inside lifecycle method not propagated to wrapped component as prop

### ISSUE THREAD

**Issue by dkrieger** [acdlite/recompose#539]
my code is something like this:

```
lifecycle({
  componentDidMount(){
    this.helperFunction = (value) => {this.setState({foobar: value});}
    this.helperFunction(this.props.baz);
  }
  componentDidUpdate(){
    this.helperFunction(this.props.baz);
  }
})(WrappedComponent)
```

the result is that state is updated as expected, but it is not passed as `foobar` prop to `WrappedComponent`

**Comment by istarkov** [comment]
https://github.com/acdlite/recompose/blob/master/src/packages/recompose/lifecycle.js#L18-L22

please provide jsbin or codesandbox example, as what you wrote is in opposite to real code, and If you see it in reality just make another step, do an example with your behaviour.

Until then I'll close this.
