### ISSUE TITLE
RFC: withStateOrUpdatedProps

### ISSUE THREAD

**Issue by tkvw** [acdlite/recompose#545]
I think it would be interesting to have a withStateOrUpdatedProps hoc. Basically it does the same as withState, but allows state to be overridden by new props. So a component can have internal state, but this can be reset. 
Currently I use it to connect redux to a component with local state.:

    import { createFactory, Component } from 'react'
    import {setDisplayName,wrapDisplayName,shallowEqual} from 'recompose';
    const withStateOrUpdatedProps = (
        stateName,
        stateUpdaterName,
        stateFromProps
    ) => BaseComponent => {
        const factory = createFactory(BaseComponent);    
        const stateFromPropsIsFunc = typeof stateFromProps === 'function';
        
        class WithStateOrUpdatedProps extends Component {
            state = {
                stateValue:
                    stateFromPropsIsFunc
                        ? stateFromProps(this.props)
                        : stateFromProps,
            };

            componentWillReceiveProps = nextProps => {
                if(stateFromPropsIsFunc){
                    const nextState= stateFromProps(nextState);
                    if(!shallowEqual(nextState,this.state.stateValue)){
                        this.setState({
                            stateValue:nextState
                        })
                    }
                }
            };

            updateStateValue = (updateFn, callback) =>
                this.setState(
                    ({ stateValue }) => ({
                        stateValue:
                            typeof updateFn === 'function' ? updateFn(stateValue) : updateFn,
                    }),
                    callback
                );

            render() {
                return factory({
                    ...this.props,
                    [stateName]: this.state.stateValue,
                    [stateUpdaterName]: this.updateStateValue,
                })
            }
        }

        if (process.env.NODE_ENV !== 'production') {
            return setDisplayName(wrapDisplayName(BaseComponent, 'withStateOrUpdatedProps'))(
                WithStateOrUpdatedProps
            )
        }
        return WithStateOrUpdatedProps
    };

**Comment by Pajn** [comment]
This is something I use quite often as well. My use case local storage of quickly changed values, for example the value to a slider where the "outside" might only be updated on release or at least debounced.

**Comment by istarkov** [comment]
There were a lot of similar proposals in the past, we decided to not add them. As it somehow break the idea that `view = fn(state) where fn is pure function`, 
with proposal above it will be possible to get different views on every new render, it's not that this library about. 
Also imagine you have a windowed components (in a simple form we don't update/render components which are out of current view (like lazy image loading but for rendering))
The problem of pattern above that it will be really easy to skip such update because somewhere upper some component skips update to current. 
Having that api like https://developers.google.com/web/updates/2016/04/intersectionobserver is now supported in all major browsers this is easy to get optimisation, which will break all the code above.

BTW all of above is possible with our `stream` HOCs like [mappropsstream](https://github.com/acdlite/recompose/blob/master/docs/API.md#mappropsstream)

Wanna add I have such pattern in my code but not that much, may be in one of 100s components.

The recommendation is to use naked React or write your own.

**Comment by istarkov** [comment]
Also wanna add that if pattern above is used to cache so computationally intensive data you can use `withPropsOnChange` HOC

**Comment by istarkov** [comment]
I reread the code above and found that updated state depends only on `nextProps`, so we just reset state on render, it's also very bad idea than your view depends on render count. 
Anything above can cause rerender of tree below, and all that components above need to know that some component below can reset it's state and break some logic, not good.

**Comment by Pajn** [comment]
I agree it might be a special case and bad if you don't have a very specific use case. Maybe not useful in a generic library. For completeness my implementation is:
```ts
export function withInnerState<P, S = any>(
  stateName: string,
  setStateName: string,
) {
  return (WrappedComponent: React.ComponentType<P>) =>
    class extends React.Component<P, S> {
      constructor(props: P) {
        super(props)
        this.state = props[stateName]
        this.setState = this.setState.bind(this)
      }

      componentWillUpdate(nextProps) {
        if (this.props[stateName] !== nextProps[stateName]) {
          this.setState(nextProps[stateName])
        }
      }

      render() {
        return (
          <WrappedComponent
            {...{
              ...(this.props as any),
              [stateName]: this.state,
              [setStateName]: this.setState,
            }}
          />
        )
      }
    }
}
```
Might help someone with this specific use case even if it's not added.

**Comment by istarkov** [comment]
Yes even I wrote what's good and bad I also use such patterns in my code, as it's faster and sometimes not easy to find a proper solution, 
also I earn money for working code and not for good patterns inside (for them too but speed is one of the main thing business needs).

**Comment by tkvw** [comment]
Thanks for the feedback. @istarkov & @Pajn . I agree with your arguments, closing the issue.
