### ISSUE TITLE
Plunkrs on the Recipes page are invalid

### ISSUE THREAD

**Issue by danyim** [acdlite/recompose#546]
Hey there, I've just been exposed to this library, and I feel as if my React world turned upside-down--in a good way. So many things are possible with recompose that it's almost overwhelming!

In order to understand its uses, I looked through the [Recipes section](https://github.com/acdlite/recompose/wiki/Recipes) but was dismayed to find out that the Plunkrs in all the examples by @timkindberg do not work. 

Part of the issue is that the minified React they reference in a `<script>` tag is pointing to an invalid resource: https://npmcdn.com/react-dom@16.0.0/dist/react-dom.js
They should instead point to https://npmcdn.com/react-dom@16.0.0/umd/react-dom.production.min.js

**Comment by wuct** [comment]
@danyim Because the wiki page is maintained by the community, so I am going to close this issue. However, it would be nice if you can fix it :)

**Comment by timkindberg** [comment]
@danyim I tried the url you linked and it didn't work in the plunkr... if you can get the plunkr working and link to it then I can go fix all of the plunkrs I made.
