### ISSUE TITLE
Production build is broken

### ISSUE THREAD

**Issue by billyjanitsch** [acdlite/recompose#55]
In production, `createHelper` is set to lodash's `curry` [here](https://github.com/acdlite/recompose/blob/master/src/packages/recompose/createHelper.js#L6), which has signature:
`curry(func, arity)`.

In development, it uses a custom implementation [here](https://github.com/acdlite/recompose/blob/master/src/packages/recompose/createHelper.js#L16) with signature:
`curry(func, helperName, arity, setDisplayName)`

Note the different arity argument position.

`createHelper` is used to create `setStatic` [here](https://github.com/acdlite/recompose/blob/master/src/packages/recompose/setStatic.js#L8) with the arity as the 3rd argument. This works fine in development, but in production, Lodash returns the function without actually implement currying.

`setStatic`, expecting to be curried, is called with a single argument [here](https://github.com/acdlite/recompose/blob/master/src/packages/recompose/setPropTypes.js#L4). This works fine in development but throws in production because it tries to access a key on an undefined variable.

This all happens during library setup, so even just *including* `recompose` in production throws the cryptic error: `Uncaught TypeError: Cannot set property 'propTypes' of undefined`.

**Comment by mrblueblue** [comment]
I received this error in a production environment as well. 

I was using my own curried setProptypes and setDisplayname functions (not knowing they were part of the library), and when I switched to thr library functions I saw the same errors. 

Again, as billyjanitsch points out--all is well in dev.

**Comment by acdlite** [comment]
Sorry about that! Should be fixed in 0.9.2. The tests aren't set up to run in both development and production (yet), which is why I didn't catch this.

**Comment by billyjanitsch** [comment]
Thanks for the quick fix! :+1:
