### ISSUE TITLE
More examples in documentation

### ISSUE THREAD

**Issue by pokorson** [acdlite/recompose#554]
@acdlite What do you think about adding more usage examples to methods documentation? I know signature types are self-explanatory but additional example may be good for newcomers.

**Comment by wuct** [comment]
@pokorson We are welcome for a PR for more examples. By the way, there is [a wiki page](https://github.com/acdlite/recompose/wiki/Recipes)  maintained by the community for some recompose recipes.

**Comment by wuct** [comment]
Please feel free to reopen it if you have further thought.
