### ISSUE TITLE
Nesting HOC

### ISSUE THREAD

**Issue by hgylfason** [acdlite/recompose#556]
This is best explained with an example:

```
const enhance = compose(
  connect(mapStateToProps, mapDispatchToProps),
  branch(
    props => props.data.loading,
    renderComponent(Loader),
    compose(
      withState("activeRevision", "setActiveRevision", null),
      withState("currentPage", "setPage", 0),
      // ...more HOC
    )
  )
);

export default enhance(Revisions);
```

This doesn't work.
But what I'm trying to achieve is to skip the HOC's inside the nested compose function when the data is still loading.

**Comment by hgylfason** [comment]
I was referring to my example.
I can’t get it to run and assumed I was composing it incorrectly.
Should this work?

**Comment by istarkov** [comment]
yes it should

**Comment by hgylfason** [comment]
Sorry, the error was not because of recompose.
I’lol close this. Thanks for the feedback.
