### ISSUE TITLE
withStateHandlers does not allow for partially applied functions

### ISSUE THREAD

**Issue by dburles** [acdlite/recompose#558]
A common pattern I'll use with `withHandlers` is to write partially applied functions. e.g:

```js
withHandlers({
  onSetActivePopup: props => name => () => ...
})
```
```
<Avatar onClick={onSetActivePopup('user')} />
```
However, it appears you cannot make use of this pattern when using a method returned via `withStateHandlers`.

**Comment by istarkov** [comment]
It uses the same pattern as `withHandlers`.

**Comment by istarkov** [comment]
And it can't return partial functions as it's return is a state. This is written in docs.

**Comment by dburles** [comment]
@istarkov I'm a bit confused by the presence of [this issue](https://github.com/acdlite/recompose/issues/480) as the usage of `withStateHandlers` is actually quite different to that of the `withState` `withHandlers` combination. Curious why `withStateHandlers` would be recommended over them?

**Comment by istarkov** [comment]
`withState` have a lot of pain with flow. 
`withStateHandlers` can be used with flow easily.
`withState` in non functional form have all the issues of non functional form of react setState.
`withStateHandlers` always use a functional form of React `setState`

In all my cases I prefer `withStateHandlers` over `withState`, mostly because of flow and that it allows (not in all cases) to simplify combination of `withStateHandlers` and `withState`.

**Comment by istarkov** [comment]
The main case where `withHandlers` is still needed is the updating of some internal state and calling the upper handler like
```
withHandlers({
  onChange: ({onChange, updateState}) => e => {
    onChange(e);
    updateState(blabla);
  }
})
```
As forwarding event via `withStateHandlers`  is not a good idea, as it will be called async.

**Comment by dburles** [comment]
Thanks @istarkov. Just thinking out loud, what are the disadvantages of having the method return a function that returns state, e.g:

```js
withStateHandlers({
  incrementOn: ({ counter }) => value => event => ({
    counter: counter + value,
  }),
```

Currently the event is handled alongside `value` (introduced here): https://github.com/acdlite/recompose/pull/476/files
