### ISSUE TITLE
withHandlers: documentation for "handlerCreatorsFactory" is wrong

### ISSUE THREAD

**Issue by akomm** [acdlite/recompose#562]
Documentation for [withHandlers](https://github.com/acdlite/recompose/blob/8c4ac2e4a4cd8d60c8db9bc4cd73f0ce044fd9ca/docs/API.md#withhandlers):
```js
withHandlers(
  handlerCreators: {
    [handlerName: string]: (props: Object) => Function
  } |
  handlerCreatorsFactory: (initialProps) => {
    [handlerName: string]: (props: Object) => Function
  }
): HigherOrderComponent
```
But it turned out, it is actually this (compare handlerCreatorsFactory):
```js
withHandlers(
  handlerCreators: {
    [handlerName: string]: (props: Object) => Function
  } |
  handlerCreatorsFactory: {
    [handlerName: string]: (initialProps) => (props: Object) => Function
  }
): HigherOrderComponent
```

**Comment by wuct** [comment]
No, it's not. The doc is right. You can play with [this fiddle](https://jsfiddle.net/wuct/j7jvrvbL/3/) or read the source code to see why.
