### ISSUE TITLE
[flow-typed] Update flow-typed libdef

### ISSUE THREAD

**Issue by 102** [acdlite/recompose#563]
The current version of `flow-typed` in this repo is `recompose_v0.24.x.js` which is incompatible with `0.26.0`-- the current version of `recompose` itself.

Could this version be simply bumped or some changes required?

**Comment by XaveScor** [comment]
fixed in https://github.com/flowtype/flow-typed/pull/1566

**Comment by wuct** [comment]
@XaveScor Thank for your help! Do you mind to create another PR to update the flow-typed in this repo?

**Comment by XaveScor** [comment]
@wuct Sure. I will create PR tomorrow

**Comment by k** [comment]
From the flow-types repo it looks like there were no type changes, just version bumps.

**Comment by TrySound** [comment]
This is not relevant. Types are published with the library.
