### ISSUE TITLE
Add Composite to the Recompose

### ISSUE THREAD

**Issue by MrBr** [acdlite/recompose#567]
Just created React Composite package. It is a utility component, a pattern, that enables you to return multiple components from a component without an Array or additional HTML Element wrapper.

You can see the "documentation" here [React Composite](https://github.com/MrBr/react-composite).

I didn't know for Recompose until today, so created a standalone package, but it makes more sense to me to make it a part of a bigger utility library such as this one.

Just wanted to check with you guys if you think Composite would fit your library? If so, I will open PR.

Thanks

**Comment by istarkov** [comment]
Why just not to return an array? Future version of jsx will support key omitting in this case.

**Comment by istarkov** [comment]
In any case recompose is a collection of HOCs and not the helper elements, so its better for Composite to be a standalone library.

**Comment by MrBr** [comment]
That is something I didn't know, in that case, an array would be just as simple.

All right, thanks.

**Comment by istarkov** [comment]
And here it is https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html
```<>```

**Comment by MrBr** [comment]
Yup, just saw it :D
