### ISSUE TITLE
Persist static properties

### ISSUE THREAD

**Issue by iddan** [acdlite/recompose#570]
Hey there! We use recompose in a React Native app that also uses react-navigation. We enhanced one of our page components with composed `withProps()` and `connect()` and the returned component of `withProps()` lacked the navigationOptions that we expected to have (because it's a static property and this is a new component) what's confused us though is that `connect()` supported that use case and persisted the static properties. I wonder what is the approach for this use case and why does the behaviour differ from `react-redux`

**Comment by k** [comment]
Have you tried `hoistStatics`?
