### ISSUE TITLE
Flat component tree 

### ISSUE THREAD

**Issue by pokorson** [acdlite/recompose#571]
Hello, recently I've found this lib https://github.com/neoziro/recompact and I started to wonder what are benefits for keeping nested component tree while using multiple HOC's?
You can checkout https://github.com/neoziro/recompact#recompact-vs-recompose specific example. Basically all HOC's used on component are merged into single outer component.

 Some HOC's require for component to be nested inside cause they operate on lifecycle but I think that's not the case for many recompose HOC's and lifecycle itself is considered for deprecation. So why not use HOC's as pipe for props that will be passed to last component? I found it especially annoying for testing components build up with recompose HOC's.

**Comment by wuct** [comment]
This topic has been brought up several times. You might get our point about it from https://github.com/acdlite/recompose/pull/182#issuecomment-315214044.

**Comment by wuct** [comment]
I'm going to close this issue now, because there isn't too much we can do here. Please feel free to reopen it if you have further thought.
