### ISSUE TITLE
defaultProps in production

### ISSUE THREAD

**Issue by jackmellis** [acdlite/recompose#577]
I'm not entirely sure what's going wrong but I'm doing something roughly like this:
```js
compose(
  setDisplayName('foo'),
  defaultProps({
    /* some props */
  }),
  hover,
  withProps(() => ({ /* some props */ })),
);
```
where hover is a HOC provided by `reactcss` (which produces a stateful component)

when I build this in development everything works fine, but if I do the same in production I get `Cannot call a class as a function`

If I remove `defaultProps` or `hover` it works. And if I move `defaultProps` below `hover` it also works.

Any ideas?

**Comment by istarkov** [comment]
Please provide a failing example, jsbin, codesandbox, your repo
