### ISSUE TITLE
New HoC for optionally-controlled state in your components

### ISSUE THREAD

**Issue by mturley** [acdlite/recompose#589]
I wrote a HoC for my own project that I think might belong in a library like recompose. I'll put together a PR if there is agreement, but here is a gist of the version I have in my project: https://gist.github.com/mturley/b75732a1b740009928ca31ab38005c35 . The gist contains the source for the HoC `controlled()`, and an example `MyComponent` that uses it.

Basically, I want to be able to easily drop in some state types and defaults, and have my HoC provide a setControlledState helper, and essentially operate just like this.state and this.setState for the component, except that you can also pass in the state values as props instead if you want to override them.  Essentially, my HoC solves the same problem as this blog post: https://www.viget.com/articles/controlling-components-react.

Does something like this have a place in recompose? I was surprised to find that it wasn't here already.

**Comment by istarkov** [comment]
Look at withStateHandlers you can simply implement the same hoc as yours based on it.

**Comment by mturley** [comment]
Oh hmm. I see.

**Comment by wuct** [comment]
Because this HoC can be implemented by `withStateHandlers`, so, instead of merging this PR, I prefer to add a block introducing how this can be implemented in our [Recipe](https://github.com/acdlite/recompose/wiki/Recipes) page.

**Comment by wuct** [comment]
I'm going to close this PR for now, please feel free to reopen it if you have any further thought.

**Comment by mturley** [comment]
I do think this HoC offers a little more than the simple
`withStateHandlers` implementation, with a simpler syntax… but I see that
the existing solution is better than I thought. I still plan to make a PR
for this, but it’ll be a cleaner one that mostly uses withStateHandlers,
and either way I’ll definitely add stuff to Recipes.

Closing this is fine, when I’m ready with my new work I’ll open a PR.
