### ISSUE TITLE
Debug / log props HOC

### ISSUE THREAD

**Issue by pokorson** [acdlite/recompose#593]
Hello,

I think it's really convenient for debugging to have a HOC that prints out the props it gets and just render component. I saw previous closed issue on this one:
https://github.com/acdlite/recompose/issues/426

you mentioned before there could be an HOC for side-effect purposes however this will happen in render so I'm not sure if it's good to encourage any side-effects except of logging there? So maybe a logger/debbuger with `console` as default and some customization option?

**Comment by istarkov** [comment]
```
withProps(p => console.log(p));
```

**Comment by istarkov** [comment]
```
withProps(console.log);
```

**Comment by pokorson** [comment]
@istarkov I understand you want to protect library for becoming bloated with all of utils, but don't you think a lot of developers will end up pasting their own toolbelt along with recompose, from project to project?

**Comment by istarkov** [comment]
Main reason
https://github.com/acdlite/recompose/issues/588#issuecomment-356138552

Now about `lot of developers will bla bla bla`
Our Russian propaganda use sentences like this everyday ;-) 
How that `a lot` can be measured?
Based on my observations a lot of developers write not more than one project per year.

;-)

**Comment by pokorson** [comment]
Of course I can't measure it. Form handling is common use case but there are a lot of other libraries that focuses on this so I agree it might be not worth to build something specifically for this in recompse. But I still think recompose could be extended with some additional hoc like `debug` `omitProps`. 
And taking your perspective existing HOC's are also simple and could be written by developer.

**Comment by istarkov** [comment]
Yes :-) I often answer "you dont need recompose for this and that" :-) 

Now in most cases I use `console.log(bla) || blablabla` and just put it anywhere I need. Because its universal and can be used with any js code. Also I dont need to keep in mind additional method name :-)

IMO it can be done as 3rd party lib, see redux log middleware its not simple but cool.

**Comment by wuct** [comment]
@pokorson I've added this tip into README in #613, do you think it might be good enough?

**Comment by wuct** [comment]
Closed by #613
