### ISSUE TITLE
undefined is not a function(evaluating (0,_recompose.createEagerFactory)(Target))

### ISSUE THREAD

**Issue by rollymaduk** [acdlite/recompose#594]
Hello please I seem to be getting a rather unpleasant error titled  `undefined is not a function(evaluating (0,_recompose.createEagerFactory)(Target))` after my upgrade from 0.25.1 to 0.26.0, and I don't have the foggiest idea what is causing it, I have several components written with recompose and the logs dont show which one is causing the problem. please kindly help. Thanks

**Comment by istarkov** [comment]
`createEagerFactory` were removed from last version of recompose, looks like your code or your dependency uses it. 

For more details see https://github.com/acdlite/recompose/releases

**Comment by rollymaduk** [comment]
Thanks for the help, ill dig to find which component or dependency uses it.

**Comment by wuct** [comment]
I am going to close this issue. Please feel free to reopen it.
