### ISSUE TITLE
Is it possible to watch a single prop and fire a handler when it changes?

### ISSUE THREAD

**Issue by GollyJer** [acdlite/recompose#597]
I know `componentWillReceiveProps` is the "normal" place way to react to prop changes but am hoping for something more recomposey. 😃

In searching around I found this [Add withAttachedProps](componentWillReceiveProps) issue which seems like it's barking up a similar tree, but I'm not sure.  And [it was never merged](https://github.com/acdlite/recompose/pull/81).

Basically, I'm looking to call a function when a specific prop changes to a specific value.

Here's a real life example of how I'm handling this with an app level alert.  If `message.alert` is updated anywhere in the app the desired alert will be shown to the user.

As a point of clarification `PropsFromAppState` returns a slice of redux state (mapStateToProps behind the scenes) and puts it into an `appState` namespace.

**What I don't like is the `myLifeCycle` function.**  Is there a better way with recompose?

```javascript
import React from 'react';
import { compose, lifecycle, withHandlers } from 'recompose';
import DropdownAlert from 'react-native-dropdownalert';
import { PropsFromAppState } from '~/lib';

const MessageBar = ({ mySelfRef, mySelfCloseDirectly}) => (
  <DropdownAlert
    ref={mySelfRef}
    onClose={mySelfCloseDirectly}
    closeInterval={1100}
    showCancel={false}
    updateStatusBar={false}
    translucent
  />
);

const mySelfHandlers = withHandlers(() => {
  let mySelf;
  return {
    mySelfRef: () => (ref) => {
      mySelf = ref;
    },

    mySelfCloseDirectly: () => () => mySelf.closeDirectly(),

    mySelfAlertWithType: () => (type, title, message) => {
      mySelf.alertWithType(type, title, message);
    },
  };
});

const myLifecycle = lifecycle({
  componentWillReceiveProps(nextProps) {
    const currentAlert = this.props.appState.message.alert;
    const nextAlert = nextProps.appState.message.alert;

    if (nextAlert !== currentAlert) {
      this.props.mySelfAlertWithType(nextAlert.type, nextAlert.title, nextAlert.message);
    }
  },
});

export default compose(
  PropsFromAppState({
    state: 'message',
    props: 'alert',
  }),
  mySelfHandlers,
  myLifecycle,
)(MessageBar);
```

**Comment by istarkov** [comment]
So every render, even just rerender it will call alert. I wrote a lot here in issues that React logic, app logic must not be dependent on render. Component can be rerendered just because some parent rerendered etc

**Comment by istarkov** [comment]
https://github.com/acdlite/recompose/search?q=depend+render&type=Issues&utf8=✓

**Comment by istarkov** [comment]
https://github.com/acdlite/recompose/issues/545

**Comment by istarkov** [comment]
I think this is the best answer https://github.com/acdlite/recompose/issues/545#issuecomment-340469880

**Comment by dehypnosis** [comment]
dd

**Comment by GollyJer** [comment]
Thanks for the response @istarkov. Always appreciated.
Oops!  Good catch on the updating on every render. I fixed `myLifecycle` in the posted example.

Ignoring that issue, based on your linked comments it seems you suggest using "naked React" which I assume means the lifecycle methods. So the recompose way of doing it would still be the lifecyle methods (until you deprecate them) 😃 

Yeah?

**Comment by istarkov** [comment]
IMO the best will be to refactor alert component providing interface same as Dialogs have at material-ui. (open={true|false}) onRequestClose)
So alert will be fully controlled with state.

And if its not possible - lifecycle ;-( or better class Blabla extends React.Comp

**Comment by istarkov** [comment]
IMO the best will be to refactor alert component providing interface same as Dialogs have at material-ui. (open={true|false}) onRequestClose)
So alert will be fully controlled with state.

And if its not possible - lifecycle ;-( or better class Blabla extends React.Comp

**Comment by GollyJer** [comment]
Yeah... refactoring `<DropdownAlert>`would be ideal but it's a 3rd party component.

Thanks again for the help.  Looks like it's as good as it can get for now. 👍
