### ISSUE TITLE
Flatten higher order components?

### ISSUE THREAD

**Issue by FezVrasta** [acdlite/recompose#598]
I'd like to flatten a number of HOCs to look like a single one in the developer tools.

So, if I have:

```
compose(
  a,
  b,
  c
)(Foobar)
```

I'd like in the dev tools to see
```
flattened(Foobar)
```

Instead of:

```
<a(Component)>
  <b(Component)>
    <c(Foobar)>
```

So far the only way I found is to use a custom `compose` function, but I'd like to avoid to use it because it adds overhead and makes it difficult to compose on top of it.

Are there any solutions?

**Comment by pokorson** [comment]
There was some discussion previously on this topic, 
https://github.com/acdlite/recompose/pull/182#issuecomment-315214044

And you can check out https://github.com/neoziro/recompact

**Comment by wuct** [comment]
I'm going to close this issue because it might be better to discuss under #182.
