### ISSUE TITLE
mapPropsOnChange 

### ISSUE THREAD

**Issue by istarkov** [acdlite/recompose#60]
recompose does not allow to use most used pattern similar to `mapPropsOnChange`

What if I need to create computationally intensive work only if some props is changed, but pass other props as is. So I get all props online, and compute results of intensive tasks only when it needed.

For example I have property `x` and `data`, I need to make some intensive calculus if `data` changed but also I need to get current version of `x` in my component. With `mapPropsOnChange` I get the value of `x` on the moment `data` has changed. But every time I use this pattern I need new `x` values. 

This could be solved creating a HOC based on `mapPropsOnChange` but changing this line

https://github.com/acdlite/recompose/blob/master/src/packages/recompose/mapPropsOnChange.js#L23

on this

```javascript
return createElement(BaseComponent, {...this.props, ...this.childProps})
```

What are you think about
HOC with name and signature 

```
withPropsOnChange(
  depdendentPropKeys: Array<string>,
  propsMapper: (ownerProps: Object) => Object,
  BaseComponent: ReactElementType
): ReactElementType
```

**Comment by acdlite** [comment]
The `propsMapper` parameter of `mapPropsOnChange()` receives the entire props object, not just the dependent props. So you can achieve what you're looking for like so:

```js
mapPropsOnChange(
  ['foo', 'bar'],
  ({ foo, bar, ...rest }) => ({
    foobar: computationallyIntensiveFunction(foo, bar) // computed prop
    ...rest // rest of props
  }),
  BaseComponent
)
```

**Comment by istarkov** [comment]
This will not work!
propsMapper will be called only if `foo` or `bar` has changed,
but if changed something in the rest you will got the old childProps

**Comment by istarkov** [comment]
As I wrote the only way to make it work is to combine props with childProps at render
```
return createElement(BaseComponent, {...this.props, ...this.childProps})
```

**Comment by acdlite** [comment]
Oh... I see what you mean now. Need to write a failing test case.

**Comment by istarkov** [comment]
But looks like mapPropsOnChange is the good name for current behavior, 
it looks like for new behavior it will be better to create something like `withPropsOnChange`?

**Comment by acdlite** [comment]
Actually, probably need to rethink `mapPropsOnChange()` entirely. I don't like mapping the entire props object, but then mixing it back into the original props object.

**Comment by istarkov** [comment]
Sounds good, thank you!

**Comment by acdlite** [comment]
I dunno about `withPropsOnChange()` either... could work.

**Comment by acdlite** [comment]
Maybe we can avoid this confusion by having the `propsMapper` *not* receive the entire props object, only the dependent props. Then combine with the rest of the props at the end.

**Comment by istarkov** [comment]
This will work. There is no need in computation to use nondependent props. 

Like this?
```javascript
import { Component } from 'react'
import pick from 'lodash/object/pick'
import omit from 'lodash/object/omit'
import shallowEqual from 'recompose/shallowEqual'
import createHelper from 'recompose/createHelper'
import createElement from 'recompose/createElement'

const mapPropsOnChange = (depdendentPropKeys, propsMapper, BaseComponent) => {
  const pickDependentProps = props => pick(props, depdendentPropKeys)
  const omitDependentProps = props => omit(props, depdendentPropKeys)

  return class extends Component {
    childProps = propsMapper(this.props)

    componentWillReceiveProps(nextProps) {
      if (!shallowEqual(
        pickDependentProps(this.props),
        pickDependentProps(nextProps)
      )) {
        this.childProps = propsMapper(pickDependentProps(nextProps))
      }
    }

    render() {
      return createElement(BaseComponent, {...omitDependentProps(this.props), ...this.childProps})
    }
  }
}

export default createHelper(mapPropsOnChange, 'mapPropsOnChange')
```

**Comment by acdlite** [comment]
Yes except I'd change the implementation a bit so that

```js
this.childProps = {
  ...propsMapper(pickDependentProps(nextProps)),
  ...omitDependentProps(nextProps)
}
```

**Comment by istarkov** [comment]
You means props order, not moving omitted props into childProps?
(_moving props into childProps we got something like old behavior_)

**Comment by acdlite** [comment]
Oh duh, yes

**Comment by acdlite** [comment]
Forget my previous comment

**Comment by istarkov** [comment]
:+1: Thank you!!!
