### ISSUE TITLE
withProps type name === MapProps :|

### ISSUE THREAD

**Issue by Yauheni-blr** [acdlite/recompose#603]
HOC

```
withProps(({ isFormValid }) => ({
  checkedForm: Object.values(isFormValid).every(item => item),
}))
```

TEST
Don't pay attention to **getNestedTree**. It just helps to get deep nested tree.
```
const component = getNestedTree(
  nestingLevel,
  EnhancedCustomForm,
  { children: mockedChildren }
);

expect(component.type.name).toBe('WithProps');
```

RESULT
```
expect(received).toBe(expected)
    
    Expected value to be (using Object.is):
      "WithProps"
    Received:
      "MapProps"
```

P.S.
```
nodeType: 'component',
        type: 
         { [Function: MapProps] // name
           displayName: 'withProps(CustomForm)' }, // displayName
           ...

```

**Comment by istarkov** [comment]
Hello.
Wanna ask whats wrong? why you check internals? why we should care about react internal details, as I understand node structures are not documented and can be changed.
BTW withProps is just a tiny wrapper over mapProps.

**Comment by Yauheni-blr** [comment]
Hello, just noticed a small flaw.

> BTW withProps is just a tiny wrapper over mapProps.
True, I have seen at the implementation :)

P.S. nothing serious, nothing serious, just can be better :)

**Comment by wuct** [comment]
I am going to close this ticket because there is nothing we can do here. Please feel free to reopen it if you have further thought.
