### ISSUE TITLE
rx-recompose: props is `undefined` when trying to render HoC inside an array

### ISSUE THREAD

**Issue by ahlee2326** [acdlite/recompose#61]
```javascript
const List = ({ items }) => (
  <ul>
    {items.map(item => <EnhancedItem item={item} />)}
  </ul>
);
```

It will returns `props` is `undefined`.

**Comment by acdlite** [comment]
Can you show me the entire snippet, please?

**Comment by ahlee2326** [comment]
```javascript
const mapProps$ = props$ => {
  const items$ = props$
    .map(props => props.items)
    .startWith([]);

  return Rx.Observable.combineLatest([
    items$,
  ], (items) => ({
    items,
  }));
};

const Item = ({ item }) => (
  <li>Hello, my name is {item.name}.</li>
);

const EnhancedItem = observeProps(mapProps$)(Item);

const List = ({ items }) => (
  <ul>
    {items.map(item => <EnhancedItem item={item} />)}
  </ul>
);

const items = [{
  name: 'Bruce Lee',
}, {
  name: 'Brad Pitt',
}, {
  name: 'Leonardo DiCaprio',
}];

const TestPage = () => (
  <div>
    Featured celebrities subscribed to our site:
    <List items={items} />
  </div>
);
```

And it looks ok in React debugging tool.
![screen shot 2015-11-18 at 9 44 35 am](https://cloud.githubusercontent.com/assets/324418/11230401/8ac217c0-8dd9-11e5-9fcc-e81293741c71.png)

And here is the error message.
![screen shot 2015-11-18 at 9 47 26 am](https://cloud.githubusercontent.com/assets/324418/11230402/8ac9e7d4-8dd9-11e5-916a-e4b74d28c552.png)

**Comment by acdlite** [comment]
Huh, that's weird....

Maybe there's something funky going on with Babel. What happens if you change Item to:

```js
const Item = props => (
  <li>Hello, my name is {props.name}.</li>
);
```

If that still doesn't work, log the `props` object and see what's inside.

**Comment by ahlee2326** [comment]
`props` is undefined.

**Comment by ahlee2326** [comment]
Sorry, props has `{ items: undefined }` in `Item`

**Comment by ahlee2326** [comment]
Sorry is my typo for `mapProps` suppose to returns `item` not `items`. It works, but I will check again before close.

**Comment by acdlite** [comment]
Ah right, I see that now. Glad you figured it out.
