### ISSUE TITLE
Pass props as second argument to withState updater

### ISSUE THREAD

**Issue by diegohaz** [acdlite/recompose#610]
In order to be compatible with React `setState`, I think `recompose` needs to pass `props` as second argument to `withState` updater function.

Reference: https://reactjs.org/docs/react-component.html#setstate

I can open a PR if you guys agree.

**Comment by istarkov** [comment]
We have withStateHandlers for this.
 BTW having that it does not cover all use cases we will accept your PR :-) Thank you.

**Comment by diegohaz** [comment]
Thank you, @istarkov. I was having some weird issues with outdated state/props on a project I'm working on (https://github.com/diegohaz/reas). 

I think `withStateHandlers` can solve those problems.
