### ISSUE TITLE
A proposal to add a `switch`-like fn

### ISSUE THREAD

**Issue by miwillhite** [acdlite/recompose#611]
Borrowing from Ramda's [cond](http://ramdajs.com/docs/#cond), I'm looking to implement something like `switch` for Recompose:

```js
// where 
//   cond :: [[(Object -> Boolean), (HigherOrderComponent -> HigherOrderComponent)]]
//   True :: Any -> Boolean
const App = compose(
  cond([
    [isGreeting, sayItBoldly],
    [isValediction, sayItSoftly],
    [True, shoutIt], // like `default` in `switch`
  ])
)(props => <span>{props.title}</span>)

render(<App title="hello" />, document.getElementById('root'))
//=> <b><span>hello</span></b>
```
`cond` would take a list of tuples each with a _test_ fn that takes a props object. When the test is true, the matching stops and the second element of the tuple is a function applied to the `HigherOrderComponent`.

A naïve implementation may look something like this: 

[![Edit k9mpr5zzv3](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/k9mpr5zzv3)

**Comment by istarkov** [comment]
Hi, have u used search before ;-) https://github.com/acdlite/recompose/search?q=switch&type=Issues&utf8=✓

**Comment by istarkov** [comment]
https://github.com/acdlite/recompose/issues/386#issuecomment-301557841

**Comment by miwillhite** [comment]
@istarkov Derp…thanks for the reminder 😁
