### ISSUE TITLE
Eslint Does not Recognise setPropTypes

### ISSUE THREAD

**Issue by wellyal** [acdlite/recompose#612]
I am using lint configs from airbnb. Therefore lint is complaining about propTypes even though I had set with the setPropTypes (recompose). Is there a workaround for this?

**Comment by istarkov** [comment]
I dont think this is somehow matters here. Some tool comlplain :-) imo its tool issue.

**Comment by wuct** [comment]
There is a related issue in [eslint-react-plugin](https://github.com/yannickcr/eslint-plugin-react/issues/1357).
