### ISSUE TITLE
Performance optimizations have been removed

### ISSUE THREAD

**Issue by Siegrift** [acdlite/recompose#614]
There is a link to watch Andrew's talk on Recompose at React Europe (https://www.youtube.com/watch?v=zD_judE-bXk). However, performance optimizations he speaks about have been removed in #538.  

Maybe adding some info about this change under the link would help. 

also the [link](https://github.com/acdlite/recompose/blob/master/docs/performance.md) explaining the performance is outdated.

**Comment by wuct** [comment]
@Siegrift Thanks for bringing this up! Would you like to edit it?

**Comment by Siegrift** [comment]
I can try

**Comment by wuct** [comment]
Closed by #615
