### ISSUE TITLE
withProps doesn't seem to work for props.children

### ISSUE THREAD

**Issue by tallpants** [acdlite/recompose#617]
I'm not sure if I'm doing something wrong, but it seems like `withProps` doesn't want to work for `props.children`.

Both this:

```js
<div>
  {withProps({ onClick: mobileClicked })(props.children)}
</div>
```

... and this:

```js
</div>
  {withProps({ onClick: mobileClicked })(
    React.Children.only(props.children)
  )}
</div>
```

... and even _this_:

```js
<div>
  {withProps({ onClick: mobileClicked })(
    React.cloneElement(React.Children.only(props.children))
  )}
</div>
```
... don't seem to work.

But this works just fine:

```js
<div>
  {React.cloneElement(React.Children.only(props.children), {
    onClick: mobileClicked
  })}
</div>
```

**Comment by istarkov** [comment]
please take a look into examples docs, read about hoc. you are using recompose wrong. HIgher order component can be applied on Components not elements etc. Ill close this, please google its easy :+)

**Comment by tallpants** [comment]
Whoops. Yea my bad sorry! 😅
