### ISSUE TITLE
"withStateHandlers" generated component should not update its state after it has been unmounted.

### ISSUE THREAD

**Issue by akomm** [acdlite/recompose#622]
withStateHandlers does not generate a pure function component, so it should be possible to let the generated (wrapping) component track its "is-mounted" state via lifecycles and prevent stateUpdater calls, if it is not mounted anymore.

**Comment by istarkov** [comment]
React also can track `setState` calls and prevent calling setState of not mounted component, but it warns instead. Think about it ;-)

**Comment by akomm** [comment]
With this mind-set I should ignore it in the components and HOC I implement too, because react could prevent it, but it does not. I see no logic in this comparison.

**Comment by istarkov** [comment]
May be React does it for some reason? May be we do the same by the same reason? It's not too hard to search the answer using React issues.

**Comment by akomm** [comment]
"May be" is not a way to discuss. Let us stick to facts. 

React does not call `setState` for you. Therefore it can not know implementation details, therefore it can not make a decision for you.

You do implement the `setState` call, therefore the situation is absolutely different.

The `setState` call implenentation inside `withStateHandlers` __may be__ (sry, could not let it be ;P) does abstract the fact away from its wrapped component, that it actually has any state for a reason.

My component should not care about the fact, that the HOC handles its own state - you know, that top-down principle in a component tree. 

I'm open-minded if I missed something, but so far the only reply I got was "may be" and at best weird comparisons of two different situations. Let us stick to facts - as said, I'm open-minded.

**Comment by istarkov** [comment]
recompose is not intended to hide react implementation details or abstract them away. It's just a thin wrappers over ordinary React. 

> React does not call setState for you.

- recompose does not call handler (in which setState is called) for you. No difference. 

> Component should not care

- why your component should care when you write React code and should not care when recompose?


IMO the reason to allow call setState and warn on unmounted component is simple, that warning shows you that you didn't freed some resource well. Please read https://reactjs.org/blog/2015/12/16/ismounted-antipattern.html
I'll close this as we will not wrap setState in any kind of isMounted pattern.

**Comment by akomm** [comment]
> recompose is not intended to hide react implementation details or abstract them away. It's just a thin wrappers over ordinary React.

Where did I said that it hides away react? I said the implementation detail of using setState is an implementation detail of the HOC and the child should not bother about how its parent are implemented.

> recompose does not call handler (in which setState is called) for you. No difference.

It does not matter, if the fact that setState is called, is a detail of the HOC's implementation, and therefore not the business of the child.

> why your component should care when you write React code and should not care when recompose?

I kind of explained that. But when you cut out 3 words, this question indeed arises.
