### ISSUE TITLE
Use default value as prop, but allow to change it for given amount of time.

### ISSUE THREAD

**Issue by Tomekmularczyk** [acdlite/recompose#625]
I have few places in my app where I had to display some feedback to a user that his action has ended with success, e.g -> he clicks "save" button -> there is some indicator that action is pending -> when the action completes, show him a quick 3s status message like: "Your note has been saved!". 

I didn't want to involve redux so I created HOC that will keep the values in state and will manage side-effects of `setTimeout`.

I have created an example that would demonstrate it: https://codesandbox.io/s/3069qy2xq6 

What you guys think about introducing something like that?

**Comment by wuct** [comment]
IMHO the use case of `withTemporaryProp` is too specific and is better to be implemented in an app instead of a lib.
