### ISSUE TITLE
pure is useless for components with children

### ISSUE THREAD

**Issue by vzaidman** [acdlite/recompose#626]
as far as i understand, the "children" prop is always re-created and receives a new reference.

using the "pure" hoc on components with children is almost like writing `shallowEqual(...) || true` meaning we pay the price of `shallowEqual` but still always re-render.

so i suggest doing one of the two:
* add this information to the documentation
* add a `pureWithChildren` function that works like `useShallowEqual` from the following repository (that by the way explains the problem i raised in detail:
https://github.com/NoamELB/shouldComponentUpdate-Children

**Comment by istarkov** [comment]
may you just try before writing ;-) It is a good exercise why it works as expected. Ill close this as you are not right

**Comment by istarkov** [comment]
btw seems I got you, what if children passed from the top component, component must be rerendered its expected behaviour

**Comment by istarkov** [comment]
If you need behaviour from that lib please use that lib

**Comment by vzaidman** [comment]
was a little lazy to do it but here is a sandbox.
don't you think in this case the component should not re-render?

https://codesandbox.io/s/w2k4vlp1j5

i think people who make their components "pure" should at least be warned in the readme about this behaviour

**Comment by wuct** [comment]
The behavior of `pure` is same as `React.PureComponent`, so I think there is no need to add a warning. By the way, you might want to have a look at [this babel plugin](https://babeljs.io/docs/plugins/transform-react-constant-elements/).
