### ISSUE TITLE
Clarify initialProps in withHandlers

### ISSUE THREAD

**Issue by tonyxiao** [acdlite/recompose#629]
What is the purpose of `initialProps`? When is it expected to be different from the props passed to individual handlers? And when should library user care / use it? Could you please provide a bit of clarification?

**Comment by pokorson** [comment]
`initialProps` are the props that are passed to you component for the first time and `props` passed to handler are the ones that will be passed in each consecutive render.

In given example:
```
const Counter = compose(
    withState('counter', 'changeCounter', 0),
    withHandlers(initialProps => {
        return {
            handleEvent: props => event => changeCounter(props.counter + 1)
        }
    })
)(CounterComponent);

<Counter title="My Counter" />
```

initialProps will be always `{ counter: 0, title: "My Counter" }`
so if you would use it for `changeCounter` call you would always get `0 + 1` .

**Comment by wuct** [comment]
`initialProps` is passed just for convenience. You can use it to bootstrap handlers.

**Comment by tonyxiao** [comment]
Gotcha. Thank you for the clarification!
