### ISSUE TITLE
SHUTTER SOUND EFFECT OR SHUTTER VISUAL EFFECT

### ISSUE THREAD

**Issue by madebytilde** [acdlite/recompose#638]
We have done a lot of work with RN Animated library in our enhanced version of camera... but it does not look perfect because there is something too small and very essential that is missing… SHUTTER SOUND EFFECT OR SHUTTER VISUAL EFFECT… Without this small detail the whole screen looks like a mediocre… I have researched regarding this issue and I have seen your tendency to avoid such a topic… I do not know why… open the camera in any app that you have installed and take a picture… instagram, facebook, twitter, snapchat... when you click the button to take a picture you have to hear a sound and see an visual effect… In 2018 this is not luxurious, this is essential… 
We have also spoken in the link below regarding this issue… 
https://github.com/react-native-community/react-native-camera/issues/1378

**Comment by istarkov** [comment]
@madebytilde are you sure you write this in a right place
