### ISSUE TITLE
Invalid example of local state?

### ISSUE THREAD

**Issue by Maxim-Filimonov** [acdlite/recompose#639]
Hi,
I've just been reading through https://recompose.docsforhumans.com/local-state.html and tried to recreate the example in codesanbox:
[![Edit vvj8klrx43](https://codesandbox.io/static/img/play-codesandbox.svg)]
(https://codesandbox.io/s/vvj8klrx43)
I kept getting `Cannot read property 'apply' of undefined` even so I have just copy/pasted the code from example. 
Example code is wrong somehow? 
Also I was a bit confused that it's not possible to use props.setOpen directly as handler.

**Comment by Maxim-Filimonov** [comment]
Oops, I haven't realised that the book is no directly from here ::) 
For anyone who finds it later I have fixed the issue by renaming is `isOpen` to `open` and using proper syntax `props => e => // handler` over `props => // handler`
See https://codesandbox.io/s/pwlpxpl6w7

**Comment by bkonkle** [comment]
I'll make sure to update the book! Thanks!
