### ISSUE TITLE
Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by defdata** [acdlite/recompose#642]
I'm trying to compose two higher order components. One is connect and the other is a custom one I wrote for logging purposes. 

The following code below works:
`export default withLogger(connect(mapStateToProps, mapDispatchToProps)(CreateEditUserForm));`

However what I think should be comparable code with recompose below does not work:
````
export default compose(
    connect(mapStateToProps, mapDispatchToProps),
    withLogger()
)(CreateEditUserForm);
````

Below is the withLogger code:
````
import React from 'react';
import Logger from './logger';

const withLogger = (WrappedComponent) => {
    return class extends WrappedComponent {
        render() {
            return (
                <WrappedComponent {...this.props} logger={Logger} />
            );
        }
    };
};

export default withLogger;
````

The error is on the import for the Logger which seems weird, it's just a plain ES6 class with static methods.

**Comment by istarkov** [comment]
remove () from `withLogger` its hoc itself without call

**Comment by defdata** [comment]
@istarkov Thanks
