### ISSUE TITLE
setStatic with getDerivedStateFromProps API giving warning in console.

### ISSUE THREAD

**Issue by hh83917** [acdlite/recompose#648]
Was trying to use the new static `getDerivedStateFromProps` API to replace `componentWillReceiveProps`, it works, but giving me following warning: 

`Warning: lifecycle(Integrations): Did not properly initialize state during construction. Expected state to be an object, but it was undefined.`

Code:
```
const enhance = compose(
    withReducer('componentState', 'dispatch', reducer),
    withHandlers(handlers),
    setStatic(
        'getDerivedStateFromProps',
        (nextProps, prevState) => {
            if (prevState && (nextProps.data !== prevState.data)) {
                nextProps.dispatch({ type: 'SET_DATA', payload: nextProps.data });;
                return nextProps;
            }
            return nextProps;
        }
    ),
    lifecycle({
        componentDidMount() {
            const { dispatch, data } = this.props;
            dispatch({ type: 'SET_DATA', payload: data });
        },
    }),
);
```

**Comment by istarkov** [comment]
It shouldn't even it's static class method it can't work without initialized state in component constructor. So until you initialize state yourself in underlying class it will give you a warning.
(And having that you already will need to have class to initialize state, you can declare `getDerivedStateFromProps` there)

**Comment by hh83917** [comment]
I see, so in this case, I can:
1. leave it, since it works?
2. only use class component?
3. just move back to use `componentWillReceiveProps` ?

**Comment by hh83917** [comment]
I'm using the withReducer HOC reducer (imported from a separate file) to initialize state, so the component does have initial state, so my getDerivedStateFromProps static is working the same as the old componentWillReceiveProps. Just the `Did not properly initialize state...` warning shows up in console, other than that everything works like before.
