### ISSUE TITLE
Bug: `WithPropsOnChange` accesses `prevProps` on `prevState`

### ISSUE THREAD

**Issue by tdeekens** [acdlite/recompose#651]
Thanks for the great release of 0.0.27!

However, with the recent release of `0.0.27` we started using the improved lifecycle methods of React. I noticed a possible regression in introducing them in `withPropsOnChange`. 

https://github.com/acdlite/recompose/blob/936e49fbfd3a70f1beedc2578c39dbdabcf8ef99/src/packages/recompose/withPropsOnChange.js#L25-L30

I wonder how `prevProps` can exist on `prevState`. Furthermore, how it's meant to work in conjunction with the `propsMapper`

https://github.com/acdlite/recompose/blob/936e49fbfd3a70f1beedc2578c39dbdabcf8ef99/src/packages/recompose/withPropsOnChange.js#L13-L17

`getDerivedStateFromProps` will not have access to `this` in that it's a `static` method. As a result we should not be able to access the `prevProps` at all.

**Comment by istarkov** [comment]
About what bug are you talking? Can you reproduce it? Be sure we have tests on every enhancer in the library.

So every time this line https://github.com/acdlite/recompose/blob/936e49fbfd3a70f1beedc2578c39dbdabcf8ef99/src/packages/recompose/withPropsOnChange.js#L26 is true we update `prevProps` in a state.

And I know that it's slightly different from previous behaviour where we used real latest prepProps but I think that no one will be affected. If there will be issues I'll add `return {prevProps: nextProps}` into this line https://github.com/acdlite/recompose/blob/936e49fbfd3a70f1beedc2578c39dbdabcf8ef99/src/packages/recompose/withPropsOnChange.js#L33

As an example what worked before and will work not same now.

```
withPropsOnChange(({a}, {a: b} ) =>  a - b > 1, () => console.log(1));
```

before, if a increased by +1 each time, this will not be called on update
now it will be called on second update.

If this somehow affects you I'll change this to previous behaviour. 

BTW current looks more right to me - as we recalculating something only if state of previous calculation has changed.

**Comment by tdeekens** [comment]
Sorry for the too vague description of a potential but. The facts that prevProps is accessed from prevState looked stange to me. It‘s where our app „crashes“ with an exception that prevProps does not exist on prevState. 

I will have a more indepth look at both recompose and our application code. I will try to deduct a mininal repro case in eg a CodeSandbox. 

Thanks a lot for the quick response.

**Comment by tdeekens** [comment]
My feeling by debugging the `withPropsOnChange` is that we should return `return { prevProps: nextProps }`. Otherwise `prevState` can be `null` and hence `prevState.prevProps` fails as we try to access `prevProps` on `null`. 

I looked at the tests and they seem to cover it somehow or at least not catch it.

**Comment by istarkov** [comment]
please provide an example ;-) as returning null we just say to React to not update state.
see React docs
getDerivedStateFromProps is invoked after a component is instantiated as well as when it receives new props. It should return an object to update state, or null to indicate that the new props do not require any state updates.

**Comment by istarkov** [comment]
So lets check here 
https://codesandbox.io/s/o9v4xzj4lq
is an example with always false and all seems like fine React 16.3.x
As I see all is fine

**Comment by istarkov** [comment]
Here is https://codesandbox.io/s/z57v4009p is React 15.x all is fine

**Comment by tdeekens** [comment]
I also failed to have a deduced repo case on a CodeSandbox where everything seems to be always fine. 

I will investigate the our application and use next week to see what causes the error. I will close the issue in the meantime until I have plausible proof.

Thanks again for the help and quick feedback!
