### ISSUE TITLE
How do u "squash" Hight order components ?

### ISSUE THREAD

**Issue by burrack** [acdlite/recompose#652]
In Andrew Clark [talk](https://youtu.be/zD_judE-bXk?t=22m22s) about recompose, he talked about a way to "squash" high order components into one.
When i'm using recompose i always see in react dev tools all of the high order component instead of one.

Is there a way to squash component into one with recompose ?

Thanks!

**Comment by s14k51** [comment]
@burrack I have been searching for the same thing as you. Why is this issue closed? Did you find a way to "squash" the hocs into one? If so, can you provide an example? Thank you.

**Comment by s14k51** [comment]
Oops. I made a hasty comment. Forgot to look into #182
