### ISSUE TITLE
branch wont pass down component static defaultProps

### ISSUE THREAD

**Issue by weslleyaraujo** [acdlite/recompose#654]
I found a quite confusing behavior while playing with `branch` and `defaultProps`,
it will _not_ pass down a component static `defaultProps` to its test function.

For example:

```jsx
class Bar extends React.Component {
  static defaultProps = {
    foo: true
  }
  render() { ... }
}

const withStuff = isStuff => branch(isStuff, ...);
const Component = withStuff(props => props.foo /* <- undefined */)(Bar);
```

I would expect that `props.foo` to have the value of `true` since its been declared as a `defaultProps` on `Bar` component.

Another finding is that if instead of using `static defaultProps = {}` I switch to `recompose/defaultProps` I get the expected behavior:

```jsx
class Bar extends React.Component {
  render() { ... }
}

const withStuff = isStuff => branch(isStuff, ...);
const enhancer = compose(
  defaultProps({
    foo: true
  }),
  withStuff(props => props.foo /* <- true! */)
)(Bar);
```

I also have a codesandbox with both examples:

- https://codesandbox.io/s/p7l0xxxprm

is this expected? 🤔

**Comment by istarkov** [comment]
:thinking:

**Comment by hh83917** [comment]
According to the docs first argument in branch should be a test function.
https://github.com/acdlite/recompose/blob/master/docs/API.md#branch
```
const maybeThing = isThingy =>
  branch(
    () => isThingy, //should be a test function
    withProps({
        passed: true
    })
  );
```

**Comment by weslleyaraujo** [comment]
@hh83917 thats correct! but the "issue" is that the test function is not properly receiving `defaultProps` values, unless its defined by `@recompose/defaultProps` hoc

**Comment by istarkov** [comment]
Just found the time to look into example, 
have you just tried to write what you get, how defaultProps from sub component can be accesses at top component props? 
What's a HOC? Generally `Ext = HOC(Comp)` is a component which can (or can not) render a Comp,
Imagine
```
class Ext extend React.C... {
    render() {
          const someVars = blabla(this.props)
           return <Comp .../
    }
}
```

now how someVars could be dependent somehow of Comp defaultProps?
