### ISSUE TITLE
Direct imports don't include flow types

### ISSUE THREAD

**Issue by Leeds-eBooks** [acdlite/recompose#655]
Refers to this PR: https://github.com/acdlite/recompose/pull/649

If we do `import pure from 'recompose/pure'`, no flow types are included. Would it be possible to place the flow types alongside each helper file, rather than in one `index.js.flow` file?

**Comment by istarkov** [comment]
We want to deprecate direct imports, as recompose fully supports tree shaking. And imports directly from recompose can even reduce your bundle size

**Comment by Leeds-eBooks** [comment]
> And imports directly from recompose can even reduce your bundle size

Oh really? Can you explain why?

**Comment by Leeds-eBooks** [comment]
Ok thanks, I'll close this.
