### ISSUE TITLE
withPropsOnChange with react@16.3: Cannot read property 'hasOwnProperty' of undefined

### ISSUE THREAD

**Issue by bkniffler** [acdlite/recompose#657]
Hey, this error is thrown due to the pick utility getting an undefined instead, thus obj.hasOwnProperty throwing an error.

Looks like
```
WithPropsOnChange.getDerivedStateFromProps = function getDerivedStateFromProps(nextProps, prevState) {
        if (shouldMap(prevState.prevProps, nextProps)) {
          return {
            computedProps: propsMapper(nextProps),
            prevProps: nextProps
          };
        }

        return null;
      };
```
has `prevState.prevProps` undefined under certain circumstances.

**Comment by istarkov** [comment]
example?

**Comment by istarkov** [comment]
also see https://github.com/acdlite/recompose/issues/651 there no reproducible example were found

**Comment by ginifizz** [comment]
Same problem here : 
![image](https://user-images.githubusercontent.com/16579730/40645135-b9718fe6-6325-11e8-9750-54dd7990f11e.png)

**Comment by istarkov** [comment]
Hey its written here upper and in corresponding thread, please provide reproducible example.

**Comment by ginifizz** [comment]
I finally found the cause of my problem: it was caused by an old version of react-redux. I leave the reproducible example here in case it could help someone:
https://codesandbox.io/s/wwoxynpvx8

**Comment by bkniffler** [comment]
I suspect there might be different cases where prevProps is undefined, especially when you use decorators (I wasn't using redux, I was using withTheme from react-fela). 

Wouldn't it make sense to check for undefined in pick? Of course we can go and fix all potential decorators out there, but I think it would be easier to catch these cases in recompose.

https://github.com/acdlite/recompose/pull/686

**Comment by istarkov** [comment]
Without test with simple example what caused props to be undefined we will not accept such check.

**Comment by bkniffler** [comment]
Okay, I opened an issue with https://github.com/rofrischmann/fela/issues/571 since I think it is due to the static func hoisting + getDerivedStateFromProps. It seems like the only correct way is to fix this on react-fela side. 

So if anyone finds this through search: This should not be fixed on recompose side, but on other decorators when they implement hoisting incorrectly. https://github.com/mridgway/hoist-non-react-statics is recommended, they already support getDerivedStateFromProps.
