### ISSUE TITLE
renderNothing - type is too constrained

### ISSUE THREAD

**Issue by philipnilsson** [acdlite/recompose#659]
`renderNothing` currently has type 

```
declare export function renderNothing<A>(C: Component<A>): Component<A>
```

I believe this should be

```
declare export function renderNothing<A, B>(C: Component<A>): Component<B>
```

**Comment by istarkov** [comment]
renderNothing is useless without branch, its type constrained to work with branch and not as type it must be. I think its written inside source.

**Comment by istarkov** [comment]
https://github.com/acdlite/recompose/blob/master/src/packages/recompose/index.js.flow#L152

**Comment by philipnilsson** [comment]
Fair enough - I suppose this could give better type errors in some less corner cases. I'll just replace with `x => y => null`

**Comment by istarkov** [comment]
may be with modern flow it can be typed as is, there were problems with some typings. I think we need to revisit types soon as * type become deprecated in latests flow commits, and this can cause some changes
