### ISSUE TITLE
expose `createElement` and `createHelper`

### ISSUE THREAD

**Issue by joshacheson** [acdlite/recompose#66]
These two private/util methods are really useful. It might be nice to either publish them as separate libraries on npm or expose them to consumers of recompose. Seems to me that people wanting to create their own helpers wont be a rare case, and these utilities are a huge help in that process.

**Comment by acdlite** [comment]
I agree they could be useful to others. Currently they're available as

```js
import createElement from 'recompose/createElement'
import createHelper from 'recompose/createHelper'
```

but they should go on the main export, as well. Only roadblock right now is proper documentation.

**Comment by acdlite** [comment]
`createElement` is now `createEagerElement` and is exposed (in master, not released yet). Now that currying has been removed, not sure there's any value in making `createHelper` public. I'll keep it private for now.
