### ISSUE TITLE
Merge the updaters from multiple withState applications

### ISSUE THREAD

**Issue by idrm** [acdlite/recompose#661]
Is there a clean way to merge the updaters from multiple `withState` enhancements into a single state updater?

E.g.

```
compose(
  withState('a', 'setA', 'blabla'),
  withState('b', 'setB', 'yadayada'),
  withHandlers({
    someHandler: ({ setA, setB }) => () => {
      setA('the new A');
      setB('the new B');
      // ideally, the previous two lines would be replaced by a single 
      // set_A_and_B('the new A', 'the new B') call
    }
  })
)
```

One approach that comes to mind is to merge the `a` and `b` states into a single `{a, b}` state, but that couples the `a` and `b` concerns, and I'd rather have recompose (or some other functional pattern) provide the merged updater.

**Comment by istarkov** [comment]
see withStateHandlers

**Comment by idrm** [comment]
Upon further review, ignore this issue/question. React consolidates the two `setState`s into a single render.

**Comment by istarkov** [comment]
> I don't see how withStateHandlers can be used here

Just use it instead of multiple withState and withHandlers

> React consolidates the two setStates into a single render.

Only inside React event handlers, in all other cases it doesn't do this. see ReactDOM.unstable_batchedUpdates for more details.

**Comment by idrm** [comment]
Thanks for the pointers. 

I was aiming to keep the two states as separate concerns and avoid coupling them, hence the reason I'm going with two `withState` enhancements (and their separate auxiliary `withHandlers` and `withProps` complements), as opposed to merging them inside a single `withStateHandlers`. 

Re: batched updates in React event handlers only -- those are the critical scenarios I face for the time being. Batching state updates inside, say, network events hasn't been a critical requirement yet, and I can wait until the React devs implement state update batching in any type of event handler.
