### ISSUE TITLE
withStateHandlers does not rerender on state change

### ISSUE THREAD

**Issue by FrancisMurillo** [acdlite/recompose#675]
Hello,

I was making a collapsible accordion in a `react-native` app. I opted to use `withStateHandlers` since it seemed appropriate; however, the component does not rerender the new state despite logging the newly updated state. Strange, is that reverting to `withState` and `withHandlers` works instead.

Here is close replication of the code in question:

```
const accordion = withStateHandlers(
  {collapsed: {}},
  {
    onToggle: ({collapsed}) => (index) => {
      const indexValue = Boolean(collapsed[index]);

      Object.keys(collapsed).forEach((key) => {
        collapsed[key] = false;
      });

      collapsed[index] = !indexValue;

      return {collapsed};    
    }
  }
)
```

**Comment by istarkov** [comment]
Please provide codesanbox example to show an issue. 
BTW Im pretty sure that the problem is in your implementation above,
you mutate the state object directly breaking all possible components optimizations. In your case collapsed ref is always the same. As an advise - always use immutable way of changing state objects.

**Comment by istarkov** [comment]
For internal details why it not work see
https://github.com/acdlite/recompose/blob/master/src/packages/recompose/withStateHandlers.js#L30
we are comparing prevState and current using shallowEqual, and if state props references are same we does not update

**Comment by istarkov** [comment]
I'm pretty sure that this is written in React docs. Having that react state updates can be async, mutation state directly could cause a lot of issues like inconsistent state, loss of state, optimisation problems etc

React docs

https://reactjs.org/docs/react-component.html 

> The first argument is an updater function with the signature:
`(prevState, props) => stateChange`
prevState is a reference to the previous state. It should not be directly mutated. Instead, changes should be represented by building a new object based on the input from prevState and props

> Never mutate this.state directly, as calling setState() afterwards may replace the mutation you made. Treat this.state as if it were immutable
