### ISSUE TITLE
Can't declare function props that don't change when dependent props change

### ISSUE THREAD

**Issue by arfordweb** [acdlite/recompose#681]
Class declarations work better for creating event handlers than using a HOC like `withProps` because `withProps` declares a new function every time a prop changes.  `withPropsOnChange` isn't any better.  It still re-creates the function prop every time a dependent prop changes.  And declaring `withPropsOnChange` over and over again with different dependent props would be onerous anyways.

An explanation and example solution taken from a project I'm working on...

Details
=====
The problem: the [withProps HOC](https://github.com/acdlite/recompose/blob/master/docs/API.md#withprops) from `recompose` allows you to create new props based on existing props and their changes.  So, if you have a prop `x` that is set to `10`, you can tack on a `xIsGreaterThan10` prop that evaluates to `false`.  And if `x` is incremented to 11, `xIsGreaterThan10` would be reevaluated to `true`.  Example:

```
const enhance = compose(
    withProps(({ x }) => ({ xIsGreaterThan10: x > 10 })),
    mapProps(R.pick(['xIsGreaterThan10'])), // we only want `xIsGreaterThan10`, so don't map `x`
    pure // assuming `OldComponent` is a stateless function, we need this to optimize based on the above
)

const NewComponent = enhance(OldComponent)
```

The above is great because a re-render only happens when `x` goes from being `<= 10` to `> 10` or vice versa.  But the resulting prop doesn't change otherwise.  So, a re-render on a PureComponent doesn't take place.  But, what if we create a function based an incoming prop like:

```
const enhance = compose(
    withProps(({ x }) => ({ isXGreaterThan10: () => (x > 10) })), // Now, we create a function here
    mapProps(R.pick(['xIsGreaterThan10'])), // we only want `isXGreaterThan10`, so don't map `x`
    pure // assuming `OldComponent` is a stateless function, we need this to optimize based on the above
)

const NewComponent = enhance(OldComponent)
```
The above would re-render at the same time.  The problem is that it will re-render even if we don't call `isXGreaterThan10`.  That's a waste.  Imagine if we were doing this for `onClick` functions.  Lots of props coming in to the enhanced `NewComponent` may change, prompting that a new `isXGreaterThan10` be created for the new closure in which it is being declared.  That stinks for performance.

Note that `recompose` does have a [withPropsOnChange function](https://github.com/acdlite/recompose/blob/master/docs/API.md#withpropsonchange) that allows you to only recompute values when dependent values have changed.  This does nothing to help us in this and similar scenarios.

On to `withMethodProps`.  Here's an example:
```
const enhance = compose(
    withMethodProps({
        isXGreaterThan10() {
            return this.props.x > 10
        },
    }),
    mapProps(R.pick(['xIsGreaterThan10'])),
    pure
)

const NewComponent = enhance(OldComponent)
```
The above works somewhat like recompose's `lifecycle`.  You can't use an arrow function in `withMethodProps` because the functions being passed to the `withMethodProps` HOC need to be made methods of a class.  That's not possible if you've already bound them using an arrow function.

Now, for the benefit... In this example, `isXGreaterThan10` will only every be declared once.  When `x` changes, `isXGreaterThan10` does not change.  But it will still work with the value that is contained within `x` at the time it is called.

An Implementation
=============
This doesn't include all the ceremony it should.  But, it works.

```
/**
 * @description
 * HOC generator that accepts an object of methods, keyed by the props names to be passed to
 * the decorated component.  These methods will never be recomputed because of a props change,
 * so the props declared here will never trigger re-render in a component that receives them.
 *
 * @param {object} methods        The methods to attach to this component, which can accept any
 *                                arguments you wish to declare them as accepting
 * @param {Component} InComponent A Component that will have the method props passed to it
 *                                as functions that are bound to the OutComponent
 *
 * @return {Component}            A new component that will display the component passed to it
 *                                and pass props through to the InComponent.  The only difference
 *                                will be that additional props will be passed to InComponent
 *                                which can access props OutComponent receives via `this.props`.
 *                                Those methods can also call each other using `this.methodName()`
 */
export const withMethodProps = curry((methods, InComponent) => {
    if (typeof methods !== 'object') {
        throw Error(
            '`withMethodProps` should be called with an object '
            + 'of Component methods, indexed by prop names'
        )
    }
    class OutComponent extends React.PureComponent {
        constructor(props) {
            super(props)
            forEachObjIndexed(
                (method, methodName) => {
                    this[methodName] = method.bind(this)
                },
                methods
            )
        }
        render() {
            const outProps = {
                ...this.props,
                // these picked methods will be mounted to OutComponent, so InComponent
                // will receive them as props, but calling them will call them on OutComponent;
                // so, they can see ownerProps at `this.props` instead of via a HOC generator
                // function like `withProps` that allows you to get props from a parameter
                // function's `props` parameter
                ...pick(keys(methods), this)
            }
            return <InComponent { ...outProps } />
        }
    }
    return OutComponent
})
```

**Comment by arfordweb** [comment]
It may be that what I'm describing is already achievable with recompose.  But, I couldn't figure it out.  Can anyone think of why this would not be a useful addition?

**Comment by istarkov** [comment]
I reread few times, but havent got the problem you are solving.

**Comment by istarkov** [comment]
seems like something like withHandlers but Im not sure

**Comment by arfordweb** [comment]
Ah ok.  I’m not sure how I didn’t understand ‘withHandlers’ the first time I read it.  It solves the same problem I’m solving here.  It just uses a closure, more similar to ‘withProps’.  My solution uses an object literal with methods defined on it instead, more like ‘lifecycle’.  But the solutions appear to be equivalent, aside from accessing props via a parameter vs. using ‘this.props’ the way you would with ‘lifecycle’.

That does beg the question... could ‘lifecycle’ use a similar approach to ‘withHandlers’ so the API is more consistent in using a ‘props’ argument rather than ‘this.props’?  It’s also very confusing the first time you’re unable to use ‘this.props’ when you pass an arrow function to ‘lifecycle”.

**Comment by arfordweb** [comment]
Proposed solution is equivalent to ‘withHandlers’.  No need for two solutions to the same problem.
