### ISSUE TITLE
Why is bad the performance of "recompose with rxjs drag and drop"?

### ISSUE THREAD

**Issue by shallwefootball** [acdlite/recompose#688]
bad performance below.

https://codesandbox.io/embed/k9r9r2kjx5

good performance below.

https://codepen.io/shallwefootball/pen/GGmXqB

do shake fast both. then cursor will out of element in recompose.

why this?

**Comment by jaszczw** [comment]
@shallwefootball The difference is in the mousemove - notice that in rxJS version it is attached to the document and in the recompose to the targeted div.

https://codesandbox.io/s/01yvz6qjpp
