### ISSUE TITLE
Why was cache of withHandlers removed in v0.27.0

### ISSUE THREAD

**Issue by halvves** [acdlite/recompose#690]
Just out of curiosity, why was the cache removed [here](https://github.com/acdlite/recompose/pull/647/commits/ef59143f4ef9aa043011778118565a63cf1041b4)? I have some use cases (like using lodash debounce) that were broken by this. Is there a better/recommended way to use handlers without them being constantly recreated?

**Comment by ADagen** [comment]
+1, I am also wondering

**Comment by istarkov** [comment]
That cache updated on every property change, so usecases like debounce also disnt work well. (debounce was dependent on render whats bad) 
It didnt give much performance and had a lot of code, so was simplified.

**Comment by dlebedynskyi** [comment]
@istarkov  I get your point, but realistically what is the difference difference then between withHandlers and  withProps or mapProps now? 
Before main advantage of using withHandlers was to have same ref function always. Basically emulating class method, so that render could assume being pure.

**Comment by istarkov** [comment]
It has same refs now too. All tests were same. Why not just check it?

**Comment by istarkov** [comment]
To be clear - nothing changed at all, just internal cache was removed. We can do anything with internal implementation details.
