### ISSUE TITLE
Fiddle needs CDN update

### ISSUE THREAD

**Issue by jmargolisvt** [acdlite/recompose#691]
The fiddle that's linked from the docs has a dead CDN link to recompose.  It should be updated to https://cdnjs.cloudflare.com/ajax/libs/recompose/0.26.0/Recompose.js or similar.

**Comment by evenchange4** [comment]
Use new [umd](https://unpkg.com/recompose/dist/Recompose.umd.js) file should fix this problem. I created a PR #692 to update the fiddle link. :)

**Comment by wuct** [comment]
Thank for reporting!
