### ISSUE TITLE
Not being able to import fromRenderProps.

### ISSUE THREAD

**Issue by andreyluiz** [acdlite/recompose#698]
I have a simple React Native project I am trying to inject a render prop from a React Consumer with the `fromRenderProps` enhancer. But I am not being able to import it. 

I've also checked in the npm package after a fresh `npm i --save recompose` and it is indeed not being installed.

The source code and documentation refers to it, however.

My deps:

```
"react": "16.3.1",
"react-native": "https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz",
"recompose": "^0.27.1"
```

**Comment by evenchange4** [comment]
Duplicate of #696. Not yet released. :)

**Comment by andreyluiz** [comment]
Oh, thank you. Closing!
