### ISSUE TITLE
withState don't pass stateUpdaterName and stateName if already defined in props

### ISSUE THREAD

**Issue by istarkov** [acdlite/recompose#7]
In withState
if `stateUpdaterName` and `stateName` are already defined in the props, pass props only [here](https://github.com/acdlite/recompose/blob/master/src/withState.js#L23). 
(without local updater and value.)

It allows to create [controlled and uncontrolled components](http://facebook.github.io/react/docs/forms.html#controlled-components)

Like

Component source

```javascript
@withState('value', 'onChange', 0)
export default MyInput extends .... {
...
    this.props.onChange(newValue);
...
}
```

Uncontrollable usage

```javascript
<MyInput />
```

Controllable usage

```javascript
<MyInput value={0} onChange={(newVal) => this.setState(newVal)} />
```

PS:
As I understand it can be done with `branch` now.

**Comment by acdlite** [comment]
This should work

```js
@withState('value', 'updateValue', 0)
@mapProps(({ onChange, updateValue, ...rest }) => ({
  onChange: onChange ? onChange : updateValue,
  ...rest
}))
export default MyInput extends .... {
...
    this.props.onChange(newValue);
...
}
```
