### ISSUE TITLE
[Feature Request] Convert array into single fragment

### ISSUE THREAD

**Issue by rockmandash** [acdlite/recompose#701]
Hello, thank for this wonderful library.
I was wondering if you can add a utility which can convert array into single fragment, so you can ignore key prop.
I've implemented by myself.
```javascript
import React, { Fragment } from 'react';
export default arr => React.createElement(Fragment, null, ...arr);
```

Don't know if it is useful enough to add to your library.

**Comment by illuminist** [comment]
Just wondering why would someone want to avoid key prop? Are there any benefits of using Fragment over array with key?
