### ISSUE TITLE
[Feature Request] Add new HOC withWrappedMethods

### ISSUE THREAD

**Issue by retyui** [acdlite/recompose#704]
#### Base example here:
https://gist.github.com/retyui/ee43ac46d5b6c4d63b472bd0b832404b

**Comment by idrm** [comment]
You can implement the button in your example using `withHandlers` and `pure` like this:

```
const PureButtonWithItemIdClickHandler = compose(pure, withHandlers({ onClick: ({ onClick, itemId }) => evt => onClick(evt, itemId) }))('button');
```

A sample rendering would look like this: `<PureButtonWithItemIdClickHandler onClick={clickHandler} itemId={123} />`, where `clickHandler` is a function that expects an event object and an item ID as its arguments. As long as `onClick`, `itemId`, and any other props passed to the button remain the same (`===`) across renders of the enclosing component you will avoid a re-render of the button.
