### ISSUE TITLE
Feature Request - omitProps

### ISSUE THREAD

**Issue by StevePotter** [acdlite/recompose#705]
Hello, this is a great library that has made writing my HOCs so much nicer.  Yesterday I made two HOCs that had similar patterns.  First, I used `withContext` to grab something like my `react-router-dom` router, then used `withProps` to create some props to propagate down into my pure component. 

This has the side effect of adding the extra props created from `withContext`.  I could use `mapProps` of course to filter it out, but it would be cleaner if I could simply just call `omitProps('location', 'history')` instead and not have to bother with omitting via lodash or something.

We also use Flow heavily, which this library works like a charm with.  `omitProps` could use a proper Flow typed, which would result in the ideal Flow scenario in my visual components.  

Is this something you would consider?  If so, I'd be happy to write it.

**Comment by idrm** [comment]
`omitProps` is mentioned in the API docs. They use the `omit()` function from **lodash-fp**, but you can also `import omit from 'recompose/utils/omit'` (if you're OK with relying on a non-documented function).

**Comment by StevePotter** [comment]
@idrm I saw that too in the docs.  The biggest gain in a built-in function would be with Flow types.  The workflow for my HOCs is generally:
1. add some property, like using `withContext`
2. using property from step 1, add new properties for child components
3. remove properties added in step 1, as the only properties I want added to child components are in step 2 

For now, I'm just using `mapProps` for steps 2 and 3, but I have to fiddle with Flow typings on my HOC.  

If instead there was `omitProps`, I could use `withProps` and `omitProps` instead of `mapProps`, which would reduce my HOC logic and, most importantly, have Flow typing just work.  I hope that was more clear.

**Comment by StevePotter** [comment]
Closing it due to lack of interest.  Plus it's really only there for Flow.  I just ended up making custom Flow types for my HOCs
