### ISSUE TITLE
omitProps documentation example does not use `omit` correctly

### ISSUE THREAD

**Issue by claudiut** [acdlite/recompose#708]
Hi,

The `omit(keys, props)` snippet from the `omitProps` example in the docs is incorrect, is should be `omit(props, keys)`: https://lodash.com/docs/4.17.10#omit.

Docs reference: https://github.com/acdlite/recompose/blob/master/docs/API.md#mapprops

Thanks for this great lib!

**Comment by ralph-cheng** [comment]
The documentation example is correct.

It says in recompose doc
> `mapProps()` pairs well with functional utility libraries like [lodash/fp](https://github.com/lodash/lodash/tree/npm/fp).

It is a [functional](https://github.com/lodash/lodash/wiki/FP-Guide#lodashfp) of lodash, which has a lot of functions' parameters rearranged in a way they become
> auto-curried iteratee-first data-last

The fp version can do:
```
// FP version
const stripFn = _fp.omit(['a', 'c']); // returns a function
const result = stripFn(some_value);
```
but not the regular version
```
// Regular version
const stripFn = _.omit(['a', 'c']); // not function
const result = stripFn(some_value); // this is error
```

**Comment by claudiut** [comment]
Ahh.. sorry, I had not taken note of what `fp` is. Got it, thanks!
