### ISSUE TITLE
SetDisplayName (and SetStatic) modifies the original class properties.

### ISSUE THREAD

**Issue by jackmarketon** [acdlite/recompose#709]
SetDisplayName (and thus) SetStatic modifies the original class properties which can have unexpected consequences.

```
class TextInput extends Component {} // DisplayName is "TextInput"
const NewInput = setDisplayName('NewNameABC')(TextInput);

NewInput.DisplayName === 'NewNameABC'
TextInput.DisplayName === 'NewNameABC'
```

I would expect setting statics and especially the display name would not affect the original component.

**Comment by istarkov** [comment]
See docs https://github.com/acdlite/recompose/blob/master/docs/API.md#setstatic
its by design
