### ISSUE TITLE
onlyUpdateForPropTypes is not works

### ISSUE THREAD

**Issue by zjhiphop** [acdlite/recompose#711]
Hi, recently i try to use onlyUpdateForPropTypes to make sure component only render when prop changes. As following code, there three props: name, placeholder, id. I just wants to re-render when any of them changes. But it shows that when 'value' state changed, the component re-rendered again.

Example Code :
```
import React, { Component } from 'react';
import { Icon, Input } from 'antd';
import { onlyUpdateForPropTypes, compose, setPropTypes, withState, lifecycle, withStateHandlers } from 'recompose';
import PropTypes from 'prop-types';

const enhance = compose(
  onlyUpdateForPropTypes,
  withStateHandlers(() => ({
    value: '',
  }), {
      valueChange: ({ oldValue }) => (newValue) => ({
        value: newValue
      })
    }),
  setPropTypes({
    name: PropTypes.string.isRequired,
    placeholder: PropTypes.string.isRequired,
    id: PropTypes.string.isRequired
  })
);

const SuffixInput = enhance(({ value, name, placeholder, id, valueChange }) => {

  const suffix = value ? <Icon type="guanbi-copy" onClick={e => {
    this.userNameInput.focus();
    valueChange('');
  }} /> : null;

  return (
    <Input
      placeholder={placeholder}
      suffix={suffix}
      value={value}
      onChange={e => {
        valueChange(e.target.value);
      }}
      ref={node => { this.userNameInput = node }}
      name={name}
      id={id}
    />
  );
});

export default SuffixInput;

```

**Comment by ericaprieto** [comment]
In that case you should be using the `pure` hoc
https://github.com/acdlite/recompose/blob/master/docs/API.md#pure

This will make sure that the component only rerenders if a prop changes (any prop)

onlyUpdateForKeys should be used when you want to rerender only if specified props changes
```javascript
const enhance = compose(
  onlyUpdateForPropTypes(["userId"]),
  ...
)
```
In this case, the component will only rerender if the userId prop changes, any other props will be ignored.

https://github.com/acdlite/recompose/blob/master/docs/API.md#onlyupdateforkeys

**Comment by wuct** [comment]
I am going to close this ticket. Please read the [Getting Help](https://github.com/acdlite/recompose#getting-help) section in the README.
