### ISSUE TITLE
Missing utils/ folder in recompose 0.28.0

### ISSUE THREAD

**Issue by goto-bus-stop** [acdlite/recompose#717]
When using eg. `onlyUpdateForKeys`, utils/pick.js is imported, but it does not exist: https://unpkg.com/recompose@0.28.0/utils/pick.js

It looks like the source files in utils/ are being output into the package root, because there is a pick.js there: https://unpkg.com/recompose@0.28.0/pick.js

The reason I think is that the Babel CLI gets each source file as a command line argument and gets a single output directory. The CLI doesn't rebase paths in that situation, it just puts all files in that directory. Maybe rather than a list of files, it should just get the src/packages/recompose as input with a recurse flag, using the --ignore flag to exclude tests and such? I'm not sure if v7 still supports that, but it might work.

I don't have time to look more into it this week so I'm sorry for not PRing a patch!

**Comment by farism** [comment]
This PR may be related https://github.com/acdlite/recompose/pull/716

**Comment by goto-bus-stop** [comment]
Thanks for the patch @farism!
