### ISSUE TITLE
[Suggestion] Reorganizing some Parts of the Readme file

### ISSUE THREAD

**Issue by Mikerr1111** [acdlite/recompose#718]
I was looking over the Readme and I found some areas I feel should to be together and not separated. Specifically these two parts below.

![docs2](https://user-images.githubusercontent.com/18353476/43419519-edeac3b8-93f5-11e8-8a70-b269776faa05.png)

The section below right here is about halfway down the Readme file. Unless this was done for a specific reason I think it makes more sense to move it upwards the top of the Readme just under 'npm install recompose --save' line.
![docs](https://user-images.githubusercontent.com/18353476/43419521-ef25e56e-93f5-11e8-8d54-22c65e2fcc77.png)

This way everything from API docs, Flow support, and different language translations are all at the top of the Readme in a 'Getting Started section for recompose'.

**Comment by wuct** [comment]
It's a good suggestion. A PR is welcome :)
