### ISSUE TITLE
createElement does not pass context to functional components

### ISSUE THREAD

**Issue by joshacheson** [acdlite/recompose#72]
Per react docs, it is expected that a context will be provided to a stateless functional component: https://facebook.github.io/react/docs/context.html#referencing-context-in-stateless-functional-components

I'm not sure if there's another "point of failure" aside from createElement for this behaviour not being supported by recompose right now, but it seems liek the sort of thing that should be supported.

Personally, I love the getContext helper and am using it in production, but I think it's important that helpers don't strictly enforce the "context as props" model and support the idiomatic React behaviour as well.

Happy to do the work on this if you think it gels with the project vision/opinions - let me know what you think

**Comment by istarkov** [comment]
Can you give a failure example - for what situation you have none working context?

**Comment by istarkov** [comment]
```javascript
import React, {PropTypes} from 'react';
import compose from 'recompose/compose';
import withContext from 'recompose/withContext';

const tmpCheckState = (props, context) => (
  <div>
    {context.test}
  </div>
);
tmpCheckState.contextTypes = {test: PropTypes.number};

export default compose(
withContext({test: PropTypes.number}, () => ({test: 101}))
)(tmpCheckState);
```

output 101

All works as expected

**Comment by acdlite** [comment]
Thanks for submitting the issue. `createElement()` uses `isReferentiallyTransparentFunctionComponent()` to test if the component can be called like a function, which returns false if the component has `contextTypes`.

https://github.com/acdlite/recompose/blob/master/src/packages/recompose/isReferentiallyTransparentFunctionComponent.js
