### ISSUE TITLE
[1] Module not found: Error: Can't resolve './utils/pick' in '/mypath/node_modules/recompose'

### ISSUE THREAD

**Issue by finom** [acdlite/recompose#721]
I'm getting the same issue at two projects I develop after upgrading recompose to 0.28.0.  Downgrading to 0.27.1 fixes the issue. At node_modules/recompose there is no actually /utils folder.

![image](https://user-images.githubusercontent.com/1082083/43569848-664c72d2-9641-11e8-9858-eb3c90f305c2.png)

UPD: Noticed that the utils are there but in the root of the package.

![image](https://user-images.githubusercontent.com/1082083/43570015-f6a70d6a-9641-11e8-99b0-f2cc8368561c.png)

**Comment by istarkov** [comment]
plz check just released 0.28.1

**Comment by wuct** [comment]
Fixed by https://github.com/acdlite/recompose/commit/7f245ec2c7bca83129ed023d37a54085bc90ea6f

**Comment by finom** [comment]
It works now, thank you.
