### ISSUE TITLE
Cannot resolve @babel/runtime paths shipped with recompose

### ISSUE THREAD

**Issue by otakustay** [acdlite/recompose#723]
`recompose/dist/Recompose.esm.js` imports several modules from `@babel/runtime`:

```
import _extends from '@babel/runtime/helpers/builtin/es6/extends';
import _inheritsLoose from '@babel/runtime/helpers/builtin/es6/inheritsLoose';
import _objectWithoutPropertiesLoose from '@babel/runtime/helpers/builtin/es6/objectWithoutPropertiesLoose';
```

There is no `helpers/builtin/es6` directory under `@babel/runtime@7.0.0-beta.56`, instead it should be `@babel/runtime/helpers/esm/*.js`

**Comment by hanweifish** [comment]
same issue

**Comment by ls-endurance** [comment]
same issue

**Comment by rob2d** [comment]
also having the issue.

@Is-endurance not sure if you already know since patch version not mentioned, but `0.27.1` is the latest I see that seems to work, specifically 😃 
https://github.com/acdlite/recompose/releases

**Comment by firearthur** [comment]
I went into node_modules and did what @otakustay recommended and it fixed it!

**Comment by stevensacks** [comment]
Same issue here
```
./node_modules/recompose/dist/Recompose.esm.js
Module not found: Can't resolve '@babel/runtime/helpers/builtin/es6/extends' in '/project_folder_path/node_modules/recompose/dist'
```

**Comment by goyney** [comment]
I'd like to mark this issue as high-priority. The changes made here are trickling down to other, larger dependencies.

Additionally, this change breaks semver:

> MINOR version when you add functionality in a backwards-compatible manner

**Comment by istarkov** [comment]
The PR fixing this issue already exists, BTW we have issue with releases now, seems like something has seriously changed in babel. Just use 0.27 for now

**Comment by evgencode** [comment]
the same:
![image](https://user-images.githubusercontent.com/2129431/43723160-a47626dc-999f-11e8-8ffb-606cf9bb3c24.png)

**Comment by nfantone** [comment]
Just here to mention that this also happens with other `@babel/runtime` versions. Same behavior here with `@babel/runtime@7.0.0-beta.46` (default version on `create-react-app` 2.0, currently). So I'm guessing this has to be related to some meddling transitive dependency.

**Comment by anthonator** [comment]
0.28.2 seems to have fixed the issue for me.

**Comment by kennethlynne** [comment]
0.28.2 fixed it, thanks!

**Comment by orlov-vo** [comment]
I have same error:

```
Failed to compile.

./node_modules/recompose/dist/Recompose.esm.js
Module not found: Can't resolve '@babel/runtime/helpers/esm/extends'  in '.../node_modules/recompose/dist'
```

```-> % npm list recompose @babel/runtime
├─┬ react-scripts@2.0.0-next.3e165448
│ └── @babel/runtime@7.0.0-beta.46 
├─┬ recompose@0.28.2 
│ └── @babel/runtime@7.0.0-beta.56 
└─┬ yup@0.26.2
  └── @babel/runtime@7.0.0-rc.1 
```

**Comment by barbalex** [comment]
This has flamed back up in my project. I have spent a few hours trying out all kinds of combinations of different versions of @babel/runtime and recompose, including fixing them via yarn resolutions in package.json. And clearing out node_modules and yarn cache. Nothing seems to work any more :-(

**Comment by pzenger** [comment]
Yup, also seeing this again, sticking with `0.27` seems to be the solution for now.

**Comment by kserjey** [comment]
Any updates?

**Comment by istarkov** [comment]
1. Use latest
2. See that you have latest babel 7.0.0, install it properly, check that you don't have 10th versions of babel runtime etc

I'll close this, that except two minor versions this was fixed. And if you have any problems just check `npm ls`, `yarn why` etc why you have multiple babel runtime versions etc.
