### ISSUE TITLE
A little thought about README.md

### ISSUE THREAD

**Issue by yanglin5689446** [acdlite/recompose#727]
The example here uses `withState` along with `pure`  function, which seems a little bit weird.
If I understand correctly the `pure` function implements `shouldComponentUpdate` and compares only props, then what's the point to ship states with a pure component? 
https://github.com/acdlite/recompose#composition

**Comment by elxris** [comment]
It's perfectly fine, because map props may return a new reference of props but no new values. So pure will prevent the enhanced component to render with no changes.

`pure` only prevent renders with no changes on the data.

As the react.js documentation states: 

> If your React component’s render() function renders the same result given the same props and state, you can use React.PureComponent for a performance boost in some cases.

**Comment by yanglin5689446** [comment]
NVM.. I might have some misunderstanding about stateless component and pure component, thx for the reply!
