### ISSUE TITLE
invariant like HOC

### ISSUE THREAD

**Issue by istarkov** [acdlite/recompose#73]
The idea is to create '[invariant](https://github.com/zertosh/invariant) like' HOC to check properties at dev builds.

The signature:
```
invariant(
  propsValidator: (ownerProps: Object) => Bool,
  message: String,
  BaseComponent: ReactElementType
): ReactElementType
```

Realization example (uses invariant lib):

```javascript
import invariant from 'invariant';
import createHelper from 'recompose/createHelper';
import createElement from 'recompose/createElement';

const invariantHOC = (props2Condition, message, BaseComponent) =>
  props => (
    invariant(props2Condition(props), message),
    createElement(BaseComponent, props)
  );

export default createHelper(invariantHOC, 'invariant');
```

But may be for performance reasons instead of invariant behavior, fully throw away this checks at release builds.

What are you think?

**Comment by acdlite** [comment]
Good idea. Maybe we can call it `propsInvariant()`, since it's an invariant of the props?

**Comment by istarkov** [comment]
:+1:

**Comment by acdlite** [comment]
Realized that this functionality is covered by React's PropTypes, which allow you to specify a custom validator.
