### ISSUE TITLE
compose accepting `undefined`, `null`, or `false` ?

### ISSUE THREAD

**Issue by alansouzati** [acdlite/recompose#730]
I have a scenario where I want to use compose by conditionally passing a hoc.

for example:

```
export default compose(
  process.env.NODE_ENV !== 'production' && withDocumentation,
  withTheme,
)(
  RadioButton
);
```

this fails since `compose` is not accepting undefined.

My current solution is to move that to:

```
export default compose(
  withTheme,
)(
  process.env.NODE_ENV !== 'production' ? withDocumentation(RadioButton) : RadioButton
);
```

I can create a PR to add support for that if this is desirable.

**Comment by istarkov** [comment]
just use js
one of example

```javascript
compose(...[
  a ? b : null, 
  d, 
   undefined
].filter(Boolean))
```

**Comment by istarkov** [comment]
IMO It wouldn't be nice ;-) as compose here is an ordinary function composition,
and in case of filtering it will be not.
