### ISSUE TITLE
[Question]: Using stateUpdaterName of withState inside initialState

### ISSUE THREAD

**Issue by Ancinek** [acdlite/recompose#737]
I have been using `recompose` for quite a while, and it is great. Today I encountered a problem that I do not know how to solve.

I have a prop called `list` passed to a component and I convert it to state using `withState` function:

```javascript
withState('stateList', 'setStateList', ({ list }) => list)
```

I want my `list` te mapped before it becomes `stateList`, but this mapping would need an access to the `setStateList` function itself like:

```javascript
list.map((item, index) => ({
   ...item,
  onItemResize: () => setStateList(/*an updated list here where one item has different width */),
}));
```

My question - is it possible to access `stateUpdaterName` function inside the `initialState` method (where I can access the component's props)?

**Comment by istarkov** [comment]
add onResize in next hoc using withProps

**Comment by Ancinek** [comment]
It must be too late for me that I did not get it myself... Thanks a lot!
