### ISSUE TITLE
Package size concern over fbjs

### ISSUE THREAD

**Issue by oliviertassinari** [acdlite/recompose#742]
A picture worth a thousand words 2.74M is a lot (I'm trying to reduce Material-UI footprint):

![capture d ecran 2018-09-24 a 19 25 23](https://user-images.githubusercontent.com/3165635/45967902-a6d87680-c02f-11e8-8011-7c7df785043f.png)

https://packagephobia.now.sh/result?p=recompose

---

Most of this bytes seem to be coming from https://packagephobia.now.sh/result?p=fbjs. https://github.com/acdlite/recompose/blob/7d5adf7f49b21e3693f7d631551d282e5c8ef820/src/packages/recompose/shallowEqual.js#L1

I understand why it was added in the first place, to match React internals, but they have recently removed the fbjs dependency: https://github.com/facebook/react/pull/13046.
What do you think of using a lighter alternative?

@gaearon By any chance, do you have an advice for the replacement of shallow equal? Thanks!

**Comment by wuct** [comment]
Thanks for analyzing! I’d like to change it if there is a good alternative.

**Comment by gaearon** [comment]
>@gaearon By any chance, do you have an advice for the replacement of shallow equal, thanks?

Copy and paste

**Comment by prograhamer** [comment]
Is there any plan for a release containing these changes? Cheers!

**Comment by oliviertassinari** [comment]
I have personally removed this dependency from all my packages. Hooks should be enough now.
