### ISSUE TITLE
Recommending Hooks API before it is has been accepted in React

### ISSUE THREAD

**Issue by paultannenbaum** [acdlite/recompose#755]
First off, thank you for the great library. 

I realize that @acdlite is a core dev on the react team, but Is it smart to announce no future maintenance and recommending hooks when the feature is still a proposal and has not been accepted into the core react library? Would also love to see some examples on how you believe the new hooks api solves the same problems, as I personally am still not seeing the api to be as powerful as the composability of a library like recompose.

**Comment by istarkov** [comment]
Have u read this https://reactjs.org/docs/hooks-custom.html ?

**Comment by istarkov** [comment]
You would have much more freedom with hooks

**Comment by paultannenbaum** [comment]
I had not, you are right this could help a lot.

Isn't this still just a proposal? Which means it may not be added to React core.

**Comment by sorahn** [comment]
I think it's coming no matter what, but the names / implementation might change slightly.

Facebook said they've been using it in prod for a month already.

**Comment by gaearon** [comment]
Nothing is changing in practice. Andrew’s wording was too strong but he didn’t mean the library would suddenly become unsupported. Your code will continue to work, and new versions for newer React updates will continue to be released.

See my reply in https://github.com/acdlite/recompose/issues/756#issuecomment-438674573.

**Comment by paultannenbaum** [comment]
Thanks @gaearon. I am going to close this issue as #756 seems to be discussing the same thing.
