### ISSUE TITLE
Rethink over dismiss

### ISSUE THREAD

**Issue by hitmands** [acdlite/recompose#759]
Hi, 
I just wanted to share some thoughts about latest announcements (hooks, etc...), and get some opinion about them :)

That's what we can find in the [homepage](https://github.com/acdlite/recompose)

>Hi! I created Recompose about three years ago. About a year after that, I joined the React team. Today, we announced a proposal for Hooks. Hooks solves all the problems I attempted to address with Recompose three years ago, and more on top of that. I will be discontinuing active maintenance of this package (excluding perhaps bugfixes or patches for compatibility with future React releases), and recommending that people use Hooks instead. [...]

which is fair enough, but I think saying `Hooks solves all the problems [...]` is not entirely true in my opinion... 

`compose`, `withProps`, `branch`, just to name few, are high order functions that let you write clean and declarative components... The reason why I like recompose is that allows you to abstract all the behaviour into separate functions in order to have the JSX as clean as possible...

what is the reason to dismiss those HOCs along with the ones officially replaced by react hooks?

**Comment by zetekla** [comment]
I concur with hitmands and other opinions on deprecating the `recompose`. It is a great library to bring joy to React development. As for many existing React apps and corporates move slowly, we still have to use React version 16 and lower, not having Hooks features as an option. It will be very tedious to have to write class based components and couple the JSX view with the controller logic. For us, it has been the defacto way to build React apps in many projects, that the Container is seen as the Controller. The JSX/Dump Component is seen as the View. and of course the State data is the Model. 
Without recompose, It is hard to build React app the MVC way, and we have to rethink our development style, approach and model.

Such that, I want to say and ask if possible, our folks can lend a hand to keep the light on for recompose. As of now, we have the resource and will be looking forward to hearing back.
Thanks,
The App Assassin team.

**Comment by gaearon** [comment]
Nothing’s changing in practice. https://github.com/acdlite/recompose/issues/756#issuecomment-438674573
