### ISSUE TITLE
is it possible with withState to reset to initial default state?

### ISSUE THREAD

**Issue by ackvf** [acdlite/recompose#760]
Is it possible to easily reset the state to its initial value without having to pass the initial value around?

```
const enhance = withState('formState', 'saveFormState', {disabled: true, reset: null, submit: null});
```

Right now I need to call `saveFormState({disabled: true, reset: null, submit: null})` to achieve the desired result.

**Comment by istarkov** [comment]
withState by design is just a tiny wrapper around setState, with same methods and ideas. So no reset.

**Comment by echoes221** [comment]
See the example for [`withStateHandlers`](https://github.com/acdlite/recompose/blob/master/docs/API.md#withstatehandlers)
