### ISSUE TITLE
React.memo() is basically pure(), right?

### ISSUE THREAD

**Issue by AdityaAnand1** [acdlite/recompose#761]
Just wanted to confirm 😃 

It will be hard to say goodbye to recompose. Thank you @acdlite

**Comment by istarkov** [comment]
right

**Comment by nfantone** [comment]
@istarkov Except it doesn't always play along as well as `pure` with other HoCs. For example, `toClass` and `memo` are incompatible. If you try to wrap a `memo(Component)` with `toClass`, you'll get: `Uncaught TypeError: baseComponent is not a function`.

There might be other caveats like these scattered around.

**Comment by istarkov** [comment]
Yep but question was about not exact equality of both ;-)

**Comment by AdityaAnand1** [comment]
What exactly are the exact differences?

**Comment by chillyistkult** [comment]
So it is basically useless to use connect and memo together?

**Comment by JeffEmery** [comment]
@chillyistkult Why do you say that? I recently tried to use Formik connect with memo and found it didn't work as I expected. I dropped it because I couldn't figure out why.

**Comment by chillyistkult** [comment]
@JeffEmery connect already "pures" the component. Since `pure` is basically the same as `memo` its useless to do memo on top of connect.
