### ISSUE TITLE
Make use of Apollo Subscription

### ISSUE THREAD

**Issue by ChenLi0830** [acdlite/recompose#764]
I want to make use of the `Subscription` component https://www.apollographql.com/docs/react/advanced/subscriptions.html#subscription-component from Apollo in recompose. And I am not sure how to do it exactly. I was thinking to use `fromRenderProps`, but I am not sure how to pass in props such as `variables` into the `Subscription` component. 

Any suggestions?

**Comment by wuct** [comment]
This question is better to ask on StackOverflow. Please [Getting Help](https://github.com/acdlite/recompose#getting-help).
