### ISSUE TITLE
Flow: Cannot call `compose` because a callable signature is missing

### ISSUE THREAD

**Issue by crobinson42** [acdlite/recompose#769]
recompose version `0.30.0`
flow version `0.89.0`

I'm not sure what this is a result of but I only get it with `react-redux`'s `connect()` as an argument of `compose()`

`Flow: Cannot call `compose` because a callable signature is missing in statics of `StoreSetup` [1] but exists in `StatelessComponent` [2]`

![screenshot 2018-12-28 11 08 25](https://user-images.githubusercontent.com/5973579/50525553-f7c59400-0a90-11e9-87a9-1028dbb2b49c.png)

**Comment by evenchange4** [comment]
There are [new HOC type definitions](https://flow.org/en/docs/react/hoc/#toc-hocs-as-of-0-89-0) after upgrade to flow `0.89.0`.
