### ISSUE TITLE
Question: propTypes?

### ISSUE THREAD

**Issue by tvararu** [acdlite/recompose#77]
I love this.

My only question about using function components, how do you specify `propTypes`? For documentation purposes chiefly, but they also help catch stupid mistakes.

This works but it doesn't look that great:

```javascript
const Text = ({ children }) => 
  <p>{children}</p>
Text.propTypes = { children: React.PropTypes.string };
Text.defaultProps = { children: 'Hello World!' };
```

I saw that you use Flow type notation in the documentation. Is that a possible route? Replacing propTypes with Flow annotations entirely?

**Comment by mrblueblue** [comment]
At least for me, I like to have `propTypes` at the top of the file, so I've been writing my components this way.

```javascript
const _propTypes = { children: React.PropTypes.string };
const _defaultProps = { children: 'Hello World!' };

const Text = ({children}) => (
  <p>{children}</p>
);

export default compose(
  setPropTypes: _propTypes,
  setDefaultProps: _defaultProps
)(Text)
```

Where `setDefaultProps` is just function like so:
```javascript
const setDefaultProps = setStatic('defaultProps')

```

It makes more sense when you have a lot of `propTypes` you want to specify.

I'd be curious to see what other patterns people are using!

**Comment by tvararu** [comment]
> setPropTypes() - Assigns to the propTypes property on the base component.

I feel embarassed, I didn't see [this function in the API documentation](https://github.com/acdlite/recompose/blob/master/docs/API.md#setproptypes). Should have cmd+F'ed for `propTypes` before posting this.

Both your method and the one using the `setPropTypes` function do look fine. Keeping issue open for the sake of discussion, feel free to close it Andrew if you consider it resolved.

**Comment by acdlite** [comment]
I believe the long term plan for React is to deprecate `propTypes` and use Flow instead.

**Comment by ericwooley** [comment]
I know this is closed, but @acdlite do you have flow definitions somewhere?

**Comment by hannupekka** [comment]
I'd be interested also to know how to use for example `pure` with Flowtype. At the moment Flowtype does not warn me when component is missing a required prop.

**Comment by idris** [comment]
@acdlite is recompose now compatible with Flow's React integration? https://flow.org/en/docs/frameworks/react/

In other words, can we omit `propTypes` if we use Flow?

**Comment by wuct** [comment]
@idris I don't think so. We need flow type definition for recompose which is work-in-progress under #241.
