### ISSUE TITLE
mapPropsOnUpdate add childProps to propsMapper call

### ISSUE THREAD

**Issue by istarkov** [acdlite/recompose#8]
Add childProps to propsMapper call here
https://github.com/acdlite/recompose/blob/master/src/mapPropsOnUpdate.js#L19

Or allow additional check

Sometimes i need to do additional checks to decide do i need to recalculate props or can return previous value.

For example

```javascript
@mapPropsOnUpdate(
  ['a', 'b'],
  (props) => {
    if (a<b) { // it can be computationally intensive check 
        return {...props, result: I_WANT_TO_RETURN_PREV_RESULT} 
    }
    return {...props, result: calcNewResult(props)} 
  }
```

with childProps it will be easy

```javascript
@mapPropsOnUpdate(
  ['a', 'b'],
  (props, childProps) => {
    if (a<b) { // it can be computationally intensive check 
        return {...props, result: childProps.result} 
    }
    return {...props, result: calcNewResult(props)} 
  }
```

**Comment by acdlite** [comment]
`mapPropsOnUpdate()` is just a shortcut for `compose(shouldUpdate(...), mapProps(...))`. If you want more control over when to update, use that.

**Comment by istarkov** [comment]
It's not `compose` of `shouldUpdate` and `mapProps`
component may update and not recalculate some internal values.

Your code for `mapPropsOnUpdate` does not contain any `shouldComponentUpdate` calls.

And there is no method like 
`mapPropsOnUpdate(props => myCompareFn, props => newProps) `

**Comment by acdlite** [comment]
Ah you're right, clearly I don't my own library well enough :)

Let me think about this one for a bit.

**Comment by acdlite** [comment]
I know the implementation is slightly different, but is there any reason why `compose(shouldUpdate(...), mapProps(...))` wouldn't achieve the desired affect?

**Comment by istarkov** [comment]
I need to redraw but not to call again some intensive calculate function. 
And in redraw i need result of that function.
And if some props changed, i need to run calculate function again after some additional checks.

Animation - in my current task. 
I have map with svg tiles over it. 
Instead of full svg path points position recalculation i can use css transforms until some props changes.

For example i scale on zoom oversimplified map tiles until tiles for new zoom level arrived.
Tiles preparation for swg drawing is really intensive task.
Also I can't call recalculate until google map stop animation (otherwise it breaks animation)

So i check `shallow equality` on some props inside `componentWillReceiveProps`,
and if it `false` I make additional checks -  could i reuse previous calculation partially or need to make full recalc again.

It's something like `reduce` operation - take some new data, take previous result and create something new if needed.

**Comment by acdlite** [comment]
I have a mostly-finished `withReducer()` helper that I'll push soon. I think it may address your issue.

**Comment by istarkov** [comment]
Thank you!!! 
`recompose` is really fun library.

**Comment by acdlite** [comment]
Closed by https://github.com/acdlite/recompose/pull/10

**Comment by istarkov** [comment]
In combination with `doOnReceiveProps` as like as i need 
withReducer will cause `Warning: setState(...): Cannot update during an existing state transition (such as within `render`).`

Because of call to some parent setState inside child constructor.

Calls actions inside `componentWillReceiveProps` are OK but gives additional render.

IMHO this withReducer is good for most situations except mine.

All i need is this.
```javascript
const createReduce = (reducer, BaseComponent) => (
  class Reduce extends React.Component {
    static displayName = wrapDisplayName(BaseComponent, 'Reduce');

    constructor(props, context) {
      super(props, context);
      this.memo_ = reducer(undefined, props);
    }

    componentWillReceiveProps(nextProps) {
      this.memo_ = reducer(this.memo_, nextProps);
    }

    render() {
      return <BaseComponent {...this.props} {...this.memo_} />;
    }
  }
);
```
