### ISSUE TITLE
createEventHandler should accept a function as an argument

### ISSUE THREAD

**Issue by flowhamster** [acdlite/recompose#80]
When a FORM element submit event occurs, you need to return false and call event.preventDefault(). Otherwise the form will attempt to submit the form in the background before processing other event subscribers. 

The FuncSubject from https://github.com/fdecampredon/rx-react allows developers to define an immediate callback, which allows developers to prevent form submission. I'll can create a pull-request with the change.

Great work on this project, and your work in react-rx-component. Quite a beautiful way to build components.

**Comment by acdlite** [comment]
Sure, a PR would be greatly appreciated :)

**Comment by acdlite** [comment]
> Yeah after thinking about this, not sure why it's needed after all. Do you really need to return false to prevent a form from submitting? You can just do e.preventDefault(), right?

https://github.com/acdlite/recompose/pull/100#issuecomment-189455025

**Comment by acdlite** [comment]
See https://github.com/acdlite/recompose/pull/100#
