### ISSUE TITLE
observeProps surprising behavior

### ISSUE THREAD

**Issue by flowhamster** [acdlite/recompose#83]
When using observeProps, the props stream uses only the initial prop values for the first render. 

In my case, I am using Recompose.lifecycle to load or fetch some cached data.However when I had a cached value, ie `WORLD`, the template was still rendering with the default value `HELLO`

```
SmartFooTemplate = Recompose.compose(
  observeProps( (props$) ->
    foo$ = new Rx.BehaviorSubject("HELLO")
    return Rx.Observable.combineLatest(
      props$, foo$
      (props, foo) ->
        Object.assign {},
          props
          foo:foo
          foo$:foo$
    )
  )
  Recompose.lifecycle(
    (self) ->
       foo$.onNext('WORLD')
    (self) ->
       #Stuff I need to run when the component is unmounted.
  )
)
DumbFooTemplate = React.createClass
    render: ->
       @props.foo # = 'HELLO'
       @props.foo$.value #= 'WORLD'
````

**Comment by dralletje** [comment]
This is actually a problem from `lifecycle()`. Lifecycle() runs the setup function *in the constructor*, which is, I guess, in Reacts perfect world a pure function as well (only setting state once). Calling the constructor becomes 'part of' the render function of the parent component, so something that calls `.setState()` in a constructor is considered an error (impure render function). For that reason, observeProps doesn't call `.setState()` till it is rendered, but uses `.state = ...` instead. This, however, does not trigger a rerender, thus you'll end up with old state.

Either lifecycle has to be altered to trigger in `componentWillMount()` ( @acdlite what is the reason it is on the constructor right now? ) or you should move the fetching/not fetching into the `observeProps()` function itself :-)

**Comment by acdlite** [comment]
Closing because we got rid of `lifecycle()`.
