### ISSUE TITLE
Similar Library

### ISSUE THREAD

**Issue by arunoda** [acdlite/recompose#88]
Hi,

I wanted to build a container creation utility for React few weeks ago. I searched for an existing one, but I couldn't figure out a one.

> I didn't find this one.

So, I created a one on my own called [react-komposer](https://github.com/kadirahq/react-komposer) and I just discovered this one.

Surprisingly, core APIs are just like the same.

Just wanted to mention this. Feel free to close this issue.

**Comment by acdlite** [comment]
Cool! If there's any room for collaboration or cross-pollination, let me know. Thinking about putting together a 1.0 soon. :)
