### ISSUE TITLE
Testing for `createSink` result

### ISSUE THREAD

**Issue by jonathanj** [acdlite/recompose#9]
I have a component structured something like:

```javascript
const nothing = () => createSink(() => null)
const MyComponentContainer = branch(
  props => props.some_flag,
  withProps(...),
  nothing)(MyComponent)
```

Unfortunately testing this with `ReactShallowRenderer` seems a bit tough, here's the render result:

```javascript
{ '$$typeof': Symbol(react.element),
  type: [Function: Sink],
  key: null,
  ref: null,
  props: { some_flag: false },
  _owner: null,
  _store: {} }
```

I have no idea what kind assertion to make to determine whether this is in fact the "nothing" result.

**Comment by acdlite** [comment]
You could scry for `MyComponent` and assert that there are no results?

**Comment by acdlite** [comment]
Also, you really don't need a sink for this. You could do:

```js
const nothing = () => () => null;
```

Maybe we should call this `renderNothing()` and add it to Recompose.

**Comment by acdlite** [comment]
Closing this because it's a React TestUtils problem, not a Recompose problem. If you have a specific suggestion for how Recompose can make testing easier, let me know!
