### ISSUE TITLE
Update rx-recompose's recompose dependency to ^0.14.0

### ISSUE THREAD

**Issue by leesiongchan** [acdlite/recompose#90]
Is that safe to do so?

**Comment by ahlee2326** [comment]
Or perhaps not peerDependency? In my case I want to use the latest version of recompose and rx-recompose at the same time.

**Comment by acdlite** [comment]
The newest versions of all packages are always tested against each other, despite what the `peerDependency` says.

I need to update the release script to automatically bump dependencies when they change.

**Comment by wuct** [comment]
How is this issue going? I would like to help if there is still no progress.

**Comment by Nomeasmo** [comment]
Vote +1

**Comment by acdlite** [comment]
Fixed (manually) in latest release
